### ISSUE TITLE
zenska/meska odmiana

### ISSUE THREAD

**Issue by draath** [tjurczyk/arkadia-skrypty#100]
W kilku miejscach pojawia sie tylko odmiana meska. Zenskiego rodzaju (nie mowiac o nijakim) brak.
Np. podczas liczenia woreczkow przy tworzeniu bazy.

**Comment by draath** [comment]
Tyle znalazlem narazie:

- pattern na liczenie woreczkow przy herbs:build_db
- pattern w triggerze left_team
- pattern w liczenie_butli
- pattern w mutant_oxen
- pattern w no-new-mail
- w off_pausers jest taki pattern: "O dziwo tym razem nie spadles z krzesla, wiec podnosisz sie z niego w cywilizowany sposob"
- w off_pausers2 pattern
- w blockers2: "^[ >]*Schodzisz na dol po drabince, lecz w polowie drogi pomieszczenie okazuje sie byc zalane ciemna woda i jestes zmuszony zawrocic na gore.*"

**Comment by draath** [comment]
- patterny w gonienie i gonienie-panika
- w triggerach gonienie, gonienie_panika, uciekl_ci moznaby tez rodzaj nijaki dodac.

**Comment by tjurczyk** [comment]
Dzięki za wszystkie raporty, dodane od 3.1 (na Mudlet 3.0, wypuszczę wersję za około godzinę).
