### ISSUE TITLE
Paczka 3.1 - Autoustawianie lokacji przy zalogowaniu

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#106]
-- Automatyczne ustawianie postaci na lokacji
-- w 'name' uzyj odpowiedniego przypadku (tekst jaki Arkadia pokazuje)
-- w 'loc_id' uzyj ID lokacji, na ktorej ma cie ustawiac

Ta funkcja przestala dzialac.

**Comment by tjurczyk** [comment]
Działa poprawnie. Przed zalogowaniem się, trzeba włączyć mapper, aby zlokalizowała, z wyłączonym mapperem nie zadziała.
