### ISSUE TITLE
Blokery do dodania

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#108]
Bloker:
1.
Ogromny stwor blokuje dojscie do bramy.

2.
e
Jestes teraz zajety czyms innym. Musisz wpisac 'przestan' by moc zrobic to co chcesz.

3.
Jezeli jestesmy ogluszeni i probojemy uciekac to mapper idzie my oczywiscie nie. 
 " Jestes ogluszony i nie mozesz nic zrobic."

**Spec npcow ogluszajacych jest inny niz Barbarzyncy.**

daje kawaleczek Loga.

[   OGLUCH   ] ----- JESTES OGLUSZONY -----

[1/6] Ktos ledwo muska cie czarna zakrzywiona szabla, trafiajac cie w korpus.
W slepiach kogos pojawia sie nienawistny blysk, gdy zdecydowanym uderzeniem obosiecznego szerokiego 
miecza kaleczy ci prawe ramie.
u
Jestes ogluszony i nie mozesz nic zrobic.
> 
Ktos lekko kiwajac glowa spoglada na kogos.
[1/6] Ktos ledwo muska cie obosiecznym szerokim mieczem, trafiajac cie w lewe ramie.
Jestes w dobrym stanie.
[1/6] Ktos ledwo muska cie czarna zakrzywiona szabla, trafiajac cie w korpus.
Ktos lekko kiwajac glowa spoglada na kogos.
[1/6] Ktos ledwo muska cie obosiecznym szerokim mieczem, trafiajac cie w korpus.
[1/6] Ktos ledwo muska cie obosiecznym szerokim mieczem, trafiajac cie w korpus.
Ktos lekko kiwajac glowa spoglada na kogos.
d
Jestes ogluszony i nie mozesz nic zrobic.
> 
Ktos lekko kiwajac glowa spoglada na kogos.

[   OGLUCH   ] ----- KONIEC OGLUCHA -----

***************************************

**Comment by tjurczyk** [comment]
`Jestes teraz zajety czyms innym. Musisz wpisac 'przestan' by moc zrobic to co chcesz.`

tego nie można dodać, bo to tekst uniwersalny arkadii i będzie ci cofał jak będziesz chciał zrobić chociażby `kto`. To raczej pod pauser, więc musisz podać co to za czynność. Jakie triggery ją włączają i wyłączają.

Co do 3: czy na każdym ogłuchu nie można uciekać?

**Comment by animal793** [comment]
3. Jak dostaniemy od barbarzyncy oglucha mozemy uciekac.

Jak dostaniemy oglucha od npca nie mozemy.

**Comment by animal793** [comment]
Co do nr 2.

Wylapie konkretne sytuacje i podam.

**Comment by tjurczyk** [comment]
3 tworzy problem, bo nie mogą wyłączać mappera, skoro raz można uciekać, a raz nie. Nie mogę tez dodać blokera, bo komunikat: "jestes ogluszony" wyskoczy nawet jak będziesz robił "sp".
Ten zamykam, jak znajdzie się opisy do 2 to nowy ticket.
