### ISSUE TITLE
bledna komenda ataku po wskazaniu

### ISSUE THREAD

**Issue by ssnakey** [tjurczyk/arkadia-skrypty#11]
***************************************
*    Zaatakuj wskazany cel: CTRL+1    *
***************************************

klepniecie ctrl+1 zaatakuje ale standardowa komenda zamiast zdefiniowana w profilu postaci

**Comment by ftpd** [comment]
+1, fajnie byłoby mieć 'zabijcmd', żeby używać np gzzabij.

**Comment by ftpd** [comment]
W sumie tak samo do 'dobadz' - niektore zawody pozwalaja.

**Comment by ssnakey** [comment]
ftpd fajnie cie widziec :P ftpd jest to definiowane w pliku postaci juz

**Comment by ftpd** [comment]
Co jest definiowane w pliku postaci? Gdzie?

**Comment by tjurczyk** [comment]
@ftpd 

```
-- Ustawianie ataku do bindow zamiast zwyklego 'zabij'
-- Przykladowo: 
--
-- ateam.attack_command = "chzabij"
--
-- bedzie wykonywalo "chzabij" zamiast "zabij" w bindach skryptowych.
-- 
-- Jesli pozostawione nieruszone to bedzie zwykle "zabij"
ateam.attack_command = nil
```

w imie.txt.

**Comment by ftpd** [comment]
Ok, widzę w imie.txt z 2.14, w moim (z 2.10) nie było, a przegapiłem w changelogu. Przepraszam za zamieszanie.

**Comment by tjurczyk** [comment]
@ssnakey 

Możesz to jeszcze raz sprawdzić? Masz 2.14a?
https://i.imgur.com/XwMgo0P.png

U mnie zadziałało, możesz też sprawdzić:

`lua ateam.attack_command`

czy wyświetla prawidłową komendę.

**Comment by ftpd** [comment]
Ale @ssnakey pisze o tym, że po _wskazaniu_ nie binduje, a nie po załapaniu wroga.

**Comment by tjurczyk** [comment]
Aaa, faktycznie, źle zrozumiałem. Poprawione od 2.14c.
