### ISSUE TITLE
Bindy pod klawiszami "-" i "\"

### ISSUE THREAD

**Issue by filipbober** [tjurczyk/arkadia-skrypty#110]
Backslash być może nie jest zbyt przydatny, ale myślnik/minus przydaje się w konwersacji, więc przydałoby się zminić binda "-" na coś innego.

**Comment by tjurczyk** [comment]
Zastanawiam się na dodaniem nowych kombinacji do klawiszów tymczasowych:

=
CTRL + =
(może) ALT + = 

Myślnik chyba faktycznie możnaby z tych klawiszów usunąć.

**Comment by ftpd** [comment]
A nie można zamiast - i = (część z nas zdążyła się przyzwyczaić) zrobić ctrl- i ctrl=? Łatwiej do przesiadki.

**Comment by tjurczyk** [comment]
Cala funkcjonalnosc bedzie niebawem przepisana, zeby mozna sobie wybrac ktore klawisze chce sie miec. Mudlet to udostepnil, wiec stalo sie to mozliwe.

**Comment by tjurczyk** [comment]
To bedzie zalatwione w https://github.com/tjurczyk/arkadia-skrypty/issues/277
