### ISSUE TITLE
Okno kondycji nie widzi osob czarnoodzianych

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#112]
Aktywne okno kondycji nie dziala na osoby czarnoodziane,
Nie da sie klikac w nim zaatakowac/ wskazac/ czy cokolwiek innego jakby nie bylo ich na lokacji.

[1/6] Czarnoodziany rycerz chaosu ledwo muska xxx olbrzymim obosiecznym mieczem dwurecznym, 
trafiajac go w korpus.
Czarnoodziany rycerz chaosu jest ciezko ranny.
Nie widzisz zadnej takiej osoby.
 Wskaz [[na] kogo / co] [jako co] ?
 Rozkaz [komu] [co].

**Comment by animal793** [comment]
To samo nie bylem  w stanie go zaatakowac, do tego nie dalo sie z nim porownac w sumie zadnej akcji na nim wykonac.

Przy bramie.
Mozesz sie stad udac na poludniowy-wschod, wschod, poludnie, polnocny-zachod, polnoc, poludniowy-
zachod lub zachod.
Drewniana kolczasta maczuga, kosc, zab, czaszka i lopatka.
Czarnoodziany mezczyzna.
> 
Czarnoodziany mezczyzna z pelnym przebieglosci blyskiem w oku rzuca sie na ciebie!
Nie widzisz zadnej takiej osoby.
> 
[1/6] Czarnoodziany mezczyzna ledwo muska cie w korpus swoim opalizujacym runicznym toporem 
obosiecznym.

/por
Prawidlowa skladnia:
	'porownaj <ceche> z <osoba>' lub tez
	'porownaj <ceche> <osoby I> i <osoby II>'
> Prawidlowa skladnia:
	'porownaj <ceche> z <osoba>' lub tez
	'porownaj <ceche> <osoby I> i <osoby II>'
> Prawidlowa skladnia:
	'porownaj <ceche> z <osoba>' lub tez
	'porownaj <ceche> <osoby I> i <osoby II>'
> 
Czarnoodziany mezczyzna jest w dobrym stanie.

ocen czlowieka
Ogladasz dokladnie czarnoodzianego mezczyzne.

Jest to czarnoodziany mezczyzna.
Trzyma oburacz opalizujacy runiczny topor obosieczny.
Walczy z toba.
Zdaje sie byc w dobrym stanie.
Na szyi ma skomplikowany czarny tatuaz zawilych przeplatajacych sie linii.
Ponad jego lewym ramieniem widac przypiety czerniony debowy temblak.
Na plecach nosi zamkniety pakowny czarny worek.
Do pasa ma przytroczone podluzny buklak, podluzna olejna lampe, dwa zamkniete niezwykle woreczki ze 
skory szczura i zamknieta zdobiona czarna sakiewke ze srebrnym lancuszkiem.
Od stop do glow zakuty jest w stalowe plyty kruczoczarnego pelnego pancerza, na ktorego 
naramiennikach wygrawerowano symbole Tzeentcha, jednego z mrocznych bogow.
Na serdecznym palcu prawej dloni nosi czarna tajemnicza obraczke.
Na biodrach nosi podwojny klamrowy pas.
Na zbroje ma narzucona purpurowa gladka tunike.
Na jego piersi spoczywa zelazny osmioramienny amulet na lancuszku, ktorego najwieksze z ogniw 
przedstawia kolo z rozchodzacymi sie promieniscie osmioma strzalami.
Nosi dluga czarna szate.
Jego szata jest spieta ozdobna srebrzysta spinka.
> kondycja wszystkich
Jestes w swietnej kondycji. Atakuje cie czarnoodziany mezczyzna.

Czarnoodziany mezczyzna jest w dobrym stanie. Atakujesz go.
>

**Comment by ftpd** [comment]
Mam podejrzenie, że tak ma być. W sensie, że Arkadia nie wysyła po GMCP danych o osobach w szacie. Przynieś, potestujemy ;-)
