### ISSUE TITLE
Blokowanie.

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#113]
1. Zmienilem sobie dzwiek na to jak ktos mnie blokuje. Dziala swietnie.

2.  Zmienilem sobie dzwiek jak ktos przymierza sie do blokowania kogos. Dziala swietnie.
Niestety nie odroznia czy to ktos z mojej druzyny blokuje kogos. Czy wrog blokuje kogos z mojej druzyny.

I dudni tak i siak.

Czy jest mozliwosc jakas by wylapywal tylko jak wrog blokuje kogos ode mnie z teamu i olewa jak moj team zaklada blok?

2.  Proponuje dodac do paska dwie dodatkowe opcje.
BL : moze byc licznik ktory odliczalby i ilosc przymierzen do blokowania na nasza osobe.
Ruszenie sie z lokacji wroga badz nas kasowaloby licznik.

BL: 1 1 1 1 ( cztery osoby przymierzaja sie do blokowania nas)

Jesli to zbyt skomplikowane to poprostu info.
Ze ktos probuje nas blokowac.

BL:  Blok!

I analogicznie druga opcja ponizej na nasza druzyne.
BLdr : ten sam sposob

Jedna z osob juz proponowala to, ja rozwinalem to jedynie o opcje dla druzyny.

**Comment by Roslinek** [comment]
Masz wycinek kodu, nie każdy chce korzystać z tego. Mam np inne ustawienia kolorów niż Adremen i za dużo musiałbym zmieniać, o przyzwyczajeniach nie wspomnę.

local r,g,b;
selectString(matches[3],1)
r,g,b = getFgColor()

--echo("r"..r.." g"..g.." b"..b)

if r == 168 and g == 84 and b == 210 then -- cel ataku      177
then
 playSoundFile(SciezkaDzwiekowa..[[blok.wav]])
end
