### ISSUE TITLE
Bledny licznik postepów globalny

### ISSUE THREAD

**Issue by baranno** [tjurczyk/arkadia-skrypty#115]
Dlaczego jak wbije nieboty to pokazuje niebotyczne + nieznaczne?

| [   8] 2017/4/12   - 1 niebotycznych + nieznaczne       |
| [   9] 2017/4/13   - 1 niebotycznych + nieznaczne       |

**Comment by animal793** [comment]
cos dziwnego bo u mnie wskazuje normalnie


 [  29] 2017/3/29   - 1 niebotycznych + spore            |
| [  30] 2017/3/30   - bardzo male                        |
| [  31] 2017/3/31   - 1 niebotycznych + nieduze          |
| [  32] 2017/4/1    - bardzo duze                        |
| [  33] 2017/4/2    - bardzo male                        |
| [  34] 2017/4/3    - 2 niebotycznych + nieznaczne       |
| [  35] 2017/4/4    - gigantyczne                        |
| [  36] 2017/4/5    - 1 niebotycznych + znaczne          |
| [  37] 2017/4/6    - 1 niebotycznych + bardzo male      |
| [  39] 2017/4/7    - bardzo male                        |
| [  40] 2017/4/9    - 1 niebotycznych + gigantyczne      |
| [  41] 2017/4/10   - 1 niebotycznych + nieznaczne       |
| [  42] 2017/4/11   - gigantyczne                        |
**| [  43] 2017/4/12   - niebotyczne**                        |
| [  44] 2017/4/13   - 1 niebotycznych + male             |
| [  45] 2017/4/14   - zadowalajace

**Comment by baranno** [comment]
Zaraz jak wbije czystego niebota w danym dniu, odrazu mi dodaje nieznaka (bez przelogowania itp)

**Comment by tjurczyk** [comment]
@baranno Opisz dokładnie krok po kroku kiedy to występuje, nie bardzo wiem gdzie może być problem.

**Comment by baranno** [comment]
1.) Ide expic
2.) Wbija mi nieboty
3.) wpisuje postepy2 i widze:
niebotyczne + nieznaczne

Mimo ze tak na prawde wbilem tylko niebotyczne.

**Comment by animal793** [comment]
dodaj recznie 15 postepow do licznika i zobacz czy bedzie niebot czy niebot + nieznak.

U mnie jest niebot .

A potem sobie usun.

**Comment by tjurczyk** [comment]
@baranno która wersja? Pamiętam, że tam były z tym błędy, ale są naprawione. W 3.1 nie powinno tego być. Jeśli jest to zrób tak jak opisuje @animal793 - dodaj ręcznie niebotyczne i sprawdź co wyświetla.

**Comment by Walkir** [comment]
Może problem leży gdzie indziej, bo u mnie np nie zlicza poprawnie:

Licznik na dzien:
```

| nieznaczne      : 26/04 09:44:28    : czas 00:28    :  zabici 0/0      |
| bardzo male     : 26/04 10:17:40    : czas 33:11    :  zabici 30/30    |
| male            : 26/04 10:50:53    : czas 33:12    :  zabici 25/25    |
| nieduze         : 26/04 12:03:00    : czas 72:07    :  zabici 19/19    |
| zadowalajace    : 26/04 12:49:28    : czas 46:28    :  zabici 20/20    |
| spore           : 26/04 13:22:19    : czas 32:51    :  zabici 28/28    |
| dosc duze       : 26/04 15:58:52    : czas 156:32   :  zabici 21/21    |
```

Licznik globalny:
`| [  23] 2017/4/26   - znaczne                            |`

Postaram sie pokombinowac kiedy tak sie dzieje, podejrzewam ze w chwili gdy zerwie mi lacze i mam reloga.

**Comment by Walkir** [comment]
Jeśli przeładuję plik konfiguracyjny to dolicza mi do globalnych postępów.
W ciągu dnia coś tam nabiłem i teraz druga sesja oraz kolejne postępy.

```
/laduj imie
(skrypty): Ok, profil zaladowany
(skrypty): Ok, dodane do globalnego licznika
(skrypty): [28/04 18:37:23] Wlasnie wbiles postepy: nieznaczne
```

**Comment by tjurczyk** [comment]
@Walkir co do pierwszego posta: niekoniecznie. Mogłeś po północy poprzedniego wieczora bić i postęp wskoczył po północy.

Co do ostatniego posta: próbowałem zreprodukować ten błąd, nie jestem w stanie. Dodałem nieznaczne, zrobiłem `/laduj ...` i mam:

```
(skrypty): Ok, dodane do globalnego licznika
(skrypty): [07/05 13:50:43] Wlasnie wbiles postepy: nieznaczne
Drewniane drzwi klikaja cicho.
(...)
/laduj erkal
(skrypty): Ok, profil zaladowany
xxx usmiecha sie do ciebie.
```

**Comment by Walkir** [comment]
Rzeczywiście, mogłem mieć postępy z dnia wcześniejszego.
Teraz też testowałem ładowanie konfigu i wszystko wygląda OK. Jakby jeszcze się powtórzyło będę pisał.
