### ISSUE TITLE
Kropka na mapie nie przeskakuje przy działającym arkowym 'idz' z kilkoma wejsciami.

### ISSUE THREAD

**Issue by ftpd** [tjurczyk/arkadia-skrypty#118]
Nie wiem, jak to sensownie wytłumaczyć, dlatego najlepiej na przykładzie:

Na trakcie campo-krzyżówka przy wejściu na fimiry po wykonaniu arkowego 'idz' przechodzi się normalnie kolejną lokację traktem, ale kropka na mapperze stoi. Jest tak w każdym miejscu, gdzie 'idz' działa mimo faktycznie istniejących kilku wyjść.

**Comment by tjurczyk** [comment]
Ale tego nie ma jak rozwiązać. Aktualnie po naciśnięciu `idz`, mapper zobaczy z którego kierunku się przyszło, i jeśli są dwa wyjścia z lokacji to przeniesie na poprawną. Jeśli tak jak na krzyżówce są 3 wyjścia nie wiadomo gdzie przestawić kropkę.

Na początku chciałem zrobić, aby po każdym `idz` robiło sprawdzenie po GMCP, ale z tego co słyszałem, `idz` działa też na terenach bez GMCP, więc wtedy klops.

**Comment by ftpd** [comment]
Ok, to zamykaj z wontfixem i z głowy.
