### ISSUE TITLE
wejdz do baszty w drachen

### ISSUE THREAD

**Issue by ssnakey** [tjurczyk/arkadia-skrypty#12]
wejdz do baszty w drachen nie przenosi kropy do baszt

**Comment by tjurczyk** [comment]
Lokalizacja baszt się zmienia. Jest sens?
Jedyne możliwe rozwiązanie, które widzę na chwilę obecną to

Po wejściu do baszty, po opisie lokacji + wyjściach lokalizuj która to baszta, to samo przy wyjściu. Wydaje mi się, że te opisy+wyjścia nie będą w 100% unikalne

**Comment by ssnakey** [comment]
to olac to nie jest az tak istotne
