### ISSUE TITLE
Informowanie o kondycji dowodzacego

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#120]
Proponuje dodanie opcji szeptanie aktualnego stanu zmeczenia naszej postaci, prowadzacemu druzyne.
Pod jakims tam klawiszem.

typu...

Animal szepce do ciebie: nieco wyczerpany
Animal szepce do ciebie: wycienczony

**Comment by ftpd** [comment]
Lol, bociarze ;-)

**Comment by tjurczyk** [comment]
Dodane zostanie API, dzięki któremu będzie można sobie zrobić swoje aliasy do poszczególnego mówienie/szeptów do prowadzącego w stylu:

```
send("szepnij " .. ateam.get_team_leader_id .. " Jestem " .. scripts.get_fatigue_text, true)
```

ale to w przyszłości.
