### ISSUE TITLE
Nieudane otwieranie drzwi 

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#126]
Nieudane otwieranie drzwi przesuwa kropke mappera jakbysmy zrobili krok w bok.e

Probujesz otworzyc drewniane drzwi kluczem, ale nie udaje ci sie to.
 Probujesz otworzyc drewniane drzwi, ale nie udaje ci sie to.

**Comment by tjurczyk** [comment]
Potrzebne jest więcej informacji. Musi nie być lokacji za drzwiami, skoro została cofnięta.
