### ISSUE TITLE
brak gaga parowanie/unik

### ISSUE THREAD

**Issue by Walkir** [tjurczyk/arkadia-skrypty#128]
XXX wykonuje zamaszyste ciecie XXX mierzac w ciebie, lecz tobie udaje sie je zbic z linii ataku posrebrzanym dlugim mieczem.

XXX wyrzuca w przod swoja zwierzeca glowe, lecz caly impet zatrzymuje sie na kolczastej plytowej parze naramiennikow.

XXX wykonuje zamach lewym lokciem mierzac w ciebie, lecz tobie udaje sie oslonic wzmacniana drewniana tarcza.

XXX zamaszystym ciosem XXX probuje trafic cie w nogi, ale tobie w pore udaje sie uskoczyc przed rozpedzona bronia.

Z glosnym rykiem XXX naciera na ciebie, lecz jego XXX z hukiem trafia w twa wzmacniana drewniana tarcze.

W slepiach XX orka pojawia sie nienawistny blysk, gdy zdecydowanym uderzeniem lekkiego polkolistego topora przecina powietrze tuz przed twoja glowa. - nie jestem pewien czy to nie jest pudlo speca?

Nagle XXX wykonuje zamaszysty cios XX mieczem, lecz tobie udaje sie go uniknac.

Nagle XX wykonuje zamaszysty cios XX bulatem, lecz sprawnie parujesz go XX mieczem.

Trafiasz XXX czarnym obsydianowym mieczem w korpus, lecz caly impet uderzenia zostaje wyparowany przez XX kolczuge.

Wyprowadzasz szybkie pchniecie XX mieczem w XXX, lecz ten zbija je z linii ataku XX maczuga.

Szybkim pchnieciem XX szabli zbijasz na bok niespodziewany cios XX orka.

Nie udaje ci sie trafic XX orka XX mieczem.

Pazury XXX zeslizguja sie po twej czarnej matowej parze nareczakow.

Swoją drogą takie pytanko, jeśli nie gaguje to też licznik /stat nie zlicza tego poprawnie?

**Comment by tjurczyk** [comment]
Dodane od 3.3.
