### ISSUE TITLE
Spece GP.

### ISSUE THREAD

**Issue by ftpd** [tjurczyk/arkadia-skrypty#13]
Przydałoby się dodać spece GP, oto patterny:

'Wykorzystujac dogodny moment .*wyprowadzasz .*' - spec mój
'.*wykorzystujac dogodny moment .*wyprowadza .* (muskajac|raniac|masakrujac) cie .*' - spec we mnie
'.*wykorzystujac dogodny moment .*wyprowadza .* (muskajac|raniac|masakrujac)(?<! cie) .*' - spec w kogoś

Patterny do siły:

/def -mregexp -Fp2 -t'wykorzystujac dogodny .* lecz' spec_gp0 = /show_spec GP 0 6
/def -mregexp -Fp2 -t'wykorzystujac dogodny .*, ledwo muskajac' spec_gp1 = /show_spec GP 1 6
/def -mregexp -Fp2 -t'wykorzystujac dogodny .*, lekko raniac' spec_gp2 = /show_spec GP 2 6
/def -mregexp -Fp2 -t'wykorzystujac dogodny .*, raniac' spec_gp3 = /show_spec GP 3 6
/def -mregexp -Fp3 -t'wykorzystujac dogodny .*, powaznie raniac' spec_gp4 = /show_spec GP 4 6
/def -mregexp -Fp3 -t'wykorzystujac dogodny .*, bardzo ciezko raniac' spec_gp5 = /show_spec GP 5 6
/def -mregexp -Fp3 -t'wykorzystujac dogodny .*, masakrujac' spec_gp6= /show_spec GP 6 6

**Comment by tjurczyk** [comment]
Ok, były dodane ale był mały błąd w patternie, już powinny być ok.
