### ISSUE TITLE
bledy przy ladowaniu mapy

### ISSUE THREAD

**Issue by Walkir** [tjurczyk/arkadia-skrypty#130]
kozystam z najnowszej wersji mudleta i skryptow, przy ladowaniu mapy mam nastepujacy blad:

[ INFO ]  - Reading map (format version:16) file:
            "C:/Users/Walkir/.config/mudlet/profiles/Walkir/map_master3.dat",
            please wait...
[ INFO ]  - Sucessfully read the map file in 0.216783 seconds, checking some
            consistency details...
[ INFO ]  - Auditing of a loaded/imported/downloaded map starting...
[  OK  ]  - Auditing of map completed, in 0.238409 seconds. Enjoy your game...
[ ALERT ] - At least one thing was detected during that last map operation
            that it is recommended that you review the most recent report in the file:
            "C:/Users/Walkir/.config/mudlet/profiles/Walkir/log/errors.txt"
            - look for the (last) report with the title:
            "Loading map(1) "C:\Users\Walkir\.config\mudlet\profiles\Walkir/map_master3.dat" at 2017-04-
24T11:28:43 report".
(skrypty): Mapa zaladowana

gdy sprawdzam loga to jest tam:
################################ End of report ################################
Loading map(1) "C:\Users\Walkir\.config\mudlet\profiles\Walkir/map_master3.dat" at 2017-04-24T11:28:43 report
================================== Map issues ==================================
[ INFO ]  - Reading map (format version:16) file: "C:/Users/Walkir/.config/mudlet/profiles/Walkir/map_master3.dat".
[ INFO ]  - Sucessfully read the map file in 0.216783 seconds, checking some consistency details...
[ INFO ]  - Area id numbering is satisfactory.
[ INFO ]  - Room id numbering is satisfactory.
[  OK  ]  - Auditing of map completed, in 0.238409 seconds. Enjoy your game...
================================= Area issues =================================
--------------------------------- Area id: 60 ---------------------------------
[ ALERT ] - Area with this id expected but not found, will be created.
================================= Room issues =================================
----------------------------- Room id: 2835 "2835" -----------------------------
[ INFO ]  - Room had one or more surplus custom line elements that were removed: schody.
---------------------- Room id: 5517 "Mlyn, Campogrotta" ----------------------
[ INFO ]  - Room had one or more surplus custom line elements that were removed: wejdz za paki.
----------------------------- Room id: 5522 "5522" -----------------------------
[ INFO ]  - Room had one or more surplus custom line elements that were removed: wcisnij cegle.
----------------------- Room id: 5818 "Zielarz, Viadaza" -----------------------
[ INFO ]  - Room had one or more surplus custom line elements that were removed: przejdz na zaplecze.
----------------------------- Room id: 6478 "6478" -----------------------------
[ INFO ]  - Room had one or more surplus custom line elements that were removed: schody.
----------------------------- Room id: 6486 "6486" -----------------------------
[ INFO ]  - Room had one or more surplus custom line elements that were removed: schody.
---------------------------- Room id: 11916 "11916" ----------------------------
[ INFO ]  - Room had one or more surplus custom line elements that were removed: wejdz na gore.
---------------------------- Room id: 15121 "15121" ----------------------------
[ INFO ]  - Room had one or more surplus custom line elements that were removed: zejdz na dol.
---------------------------- Room id: 15228 "15228" ----------------------------
[ INFO ]  - Room had one or more surplus custom line elements that were removed: zejdz na dol.
---------------------------- Room id: 15451 "15451" ----------------------------
[ INFO ]  - Room had one or more surplus custom line elements that were removed: przeplyn na poludnie.

**Comment by tjurczyk** [comment]
Nic strasznego, zostanie poprawione przy następnym updatecie publicznej mapy. Do tego czasu można to zignorować, gdyż w żaden sposób nie wpływa na działanie mapy.
