### ISSUE TITLE
Róża wiatrów. - Nowy sposób działania.

### ISSUE THREAD

**Issue by Roslinek** [tjurczyk/arkadia-skrypty#131]
W pull request się nie udało to pisze tutaj.

Są takie miejsca gdzie mapper nie działa (lasek hobgoblinow, łąki quenless, ogólne zagubienie mappera po restarcie) i róża wiatrów robi się bezużyteczna. Proponuje dopisanie drugiego trybu jej działania. tzn:
- Branie wyjść z GMCP

Dzięki czemu wyjścia staną się bardziej widoczne i uchroni to może kogoś przed zgonem.

**Comment by tjurczyk** [comment]
> Są takie miejsca gdzie mapper nie działa (lasek hobgoblinow, łąki quenless, ogólne zagubienie mappera po restarcie) i róża wiatrów robi się bezużyteczna.

Ale jeśli nie działa, to czemu jej tam nie naprawić, tylko robić skomplikowany system?

Co do łąk Quenelles to z tego co wiem działa (branie wyjść z tego co Arkadia wyrzuca). Jeśli jest inaczej to potrzebny log.

**Comment by Roslinek** [comment]
zagubienie mappera po restarcie <- o to mi głównie chodzi

**Comment by tjurczyk** [comment]
Spróbuj zrobić `zerknij`, odświeży różę wiatrów.
