### ISSUE TITLE
bind na forme - pomysl

### ISSUE THREAD

**Issue by Walkir** [tjurczyk/arkadia-skrypty#133]
Taki pomysł, żeby dodać bind do użycia formy +k przy niskiej kondycji i +z przy zmęczeniu.
Najlepiej jakby byłoby to definiowalne bo ludzie mogą mieć różne preferencje.

**Comment by animal793** [comment]
Takie rzeczy mozna dodac samemu.

Wchodzisz w zakladke Keys i tam sobie dodajesz :)

To jak z aliasami kazdy robi sam sobie.

Robisz nowy folder nazywasz go i tam dodajesz np w keys . Wtedy one przy aktualizacji skryptow, nie sa usuwane.

**Comment by Walkir** [comment]
ah wybacz, myslalem ze jest to miejsce gdzie mozna zglaszac pomysly jesli uwazamy ze cos moze sie przydac wiekszemu gronu ;) w takim razie temat do zamkniecia

**Comment by tjurczyk** [comment]
@Walkir 

Tak jak pisał @animal793 , takie rzeczy najlepiej jest dodać sobie samemu. Ja w TODO mam projekt następujący:
poniższe paski będą klikalne (np: kon [4/5]) i przykładowo po naciśnięciu paska dwukrotnie w krótkim odstępie czasu, będzie robiona +kondycja. Nie wiem natomiast kiedy zostanie to dodane, dlatego szybciej będzie jak +z zrobisz sobie samemu.
