### ISSUE TITLE
[mapper] Blokery - Rinde

### ISSUE THREAD

**Issue by filipbober** [tjurczyk/arkadia-skrypty#136]
Znalazłem dwa błędy w ruinach Rinde.

- Przechodzenie z lokazji 19767 na 19133 chwilę trwa i w tym czasie możemy poruszać się po mapie, gubiąc kierunki. Poruszać się można od momentu otrzymania komunikatu: _Obolaly podnosisz sie powoli z podlogi._
- Na lokazji 19124 (tej z kratą) możemy poruszać się na wschód, pomimo zablokowanego przejścia i komunikatu: _Nie widzisz zadnego wyjscia prowadzacego na wschod._

**Comment by tjurczyk** [comment]
Dodane. Co do kraty, po prostu usunąłem to przejście, bo tamto lokalizowanie jest po opisie lokacji.
