### ISSUE TITLE
Gagowanie walki - dodatkowa opcja (request)

### ISSUE THREAD

**Issue by JNKNM** [tjurczyk/arkadia-skrypty#138]
Dodatkowa opcja jeszcze wiekszego gagowania walki:

[x/6] -> kogo
[JA x/8] -> kogo
[unik] -> przed kim
etc.

np:
[4/6] -> wyrosnietego bezwlosego pajaka
[unk] -> Wyrosniety jadowity pajak 
[JA 8/8] -> wyrosnietego bezwlosego pajaka 

Niektorzy rowniez bardzo sobie chwalili jeden z moich skryptow do gagowania walki w Mushu, gdzie dodalem mozliwosc calkowitego wygagowania wszystkich unikow i sparowan. (prosba od niewidomego gracza)

**Comment by tjurczyk** [comment]
@JNKNM Jeśli masz na to czas i chęci to śmiało :) Jak to zrobisz, będzie można dać jako opcjonalne do skryptów.
Tych opisów jest tyle, że dla mnie ta praca wydaje się bezsensowna. Uniki standardowe, zawodowe itp, to samo z ciosami, parowaniami etc.

Ja niestety nie znajdę czasu w najbliższym czasie na tę mrówczą pracę. Jak już siadam do Mudleta to poprawiam te istotniejsze błędy.

**Comment by JNKNM** [comment]
Heh. Zanim sie naucze kodowac cokolwiek pod mudlet to wiele wody w Pontarze uplynie ;) Nie jestem programista, a w Mushu bardziej przerabialem czyjes kody, ew. lepilem swoje rzeczy z fragmentow innych kodow.
Tak wiec teraz glownie bede w twoj kod patrzyl zeby odnalezc jakis wzor na robienie roznych rzeczy.

Z drugiej strony, moze to co juz wymodzilem w Mushu w jakis sposob ci sie przyda, wiec zostawiam moja malowana walke w zalaczniku. (oryginalnie plik .xml)
[subowana_walka.txt](https://github.com/tjurczyk/arkadia-skrypty/files/981857/subowana_walka.txt)

**Comment by tjurczyk** [comment]
Dodane do ewentualnych dodatków w przyszłości.
