### ISSUE TITLE
Ladna ocena broni, tarcz i zbroi z wygagowaniem opisu

### ISSUE THREAD

**Issue by JNKNM** [tjurczyk/arkadia-skrypty#139]
Hej,

Bylbym niezmiernie wdzieczny jakby udalo sie wprowadzic mozliwosc takiego (albo podobnego) gagowania oceny przedmiotow (z wywaleniem calego opisu przedmiotu):

ocen helm
 WYTRZYMALY CHITYNOWY HELM(lekka zbroja)  K:(MAX/7) $ 0mth 0zl 16sr 8md (200)
           cietymi:10/12, klutymi:5/12, obuchowymi:9/12  waga:2700, objetosc:770

ocen bronie
 BURSZTYNOWY PLOMIENISTY SZTYLET(sztylet) obrazenia:KC, dowolna reka, K:(MAX/7) $ 0mth 6zl 5sr 0md (1500)
           wywazenie:11/14, skutecznosc:9/14  waga:1100, objetosc:290
           Do wykonania tej broni uzyto srebra, bedzie wiec ona skuteczna przeciw wrogom odpornym na zwykle obrazenia.
 BURSZTYNOWY PLOMIENISTY SZTYLET(sztylet) obrazenia:KC, dowolna reka, K:(MAX/7) $ 0mth 6zl 5sr 0md (1500)
           wywazenie:10/14, skutecznosc:10/14  waga:1100, objetosc:290
           Do wykonania tej broni uzyto srebra, bedzie wiec ona skuteczna przeciw wrogom odpornym na zwykle obrazenia.
 CIEZKI OSZLIFOWANY MIECZ(miecz) obrazenia:KC, dowolna reka, K:(MAX/7) $ 0mth 5zl 0sr 0md (1200)
           wywazenie:9/14, skutecznosc:12/14  waga:4400, objetosc:1700

**Comment by JNKNM** [comment]
![ocenianie](https://cloud.githubusercontent.com/assets/8578942/25780772/27175f5e-332e-11e7-9267-9dc7ffc29470.jpg)
Tak to wygladalo kolorystycznie w Mushu.

**Comment by tjurczyk** [comment]
@JNKNM na 95% w najbliższym pół roku tego nie będzie, bo nie mam czasu na takie rzeczy, a przydatność jest praktycznie zerowa. W dodatku to dość drastyczna zmiana - sporo ludzi chce akurat długie opisy widzieć, dlatego musi to być jako opcjonalne gagowanie.

Jeśli masz czas na takie rzeczy, możesz napisać i podrzucić, chętnie wrzucę jako opcję do paczki.

**Comment by JNKNM** [comment]
No sam tego napewno nie napisze :) To akurat cos co dostalem swego czasu od Szydela i bardzo mi przypasowalo. Szczegolnie na kupcu jak mam mase sprzetu do przesortowania. Do tego stopnia jest mi to niezbedne, ze pewnie kupcem (jako ze niewiele nim walcze) bede gral na Mushu jak sie nie uda.

Swoja droga zostawie ci ten xml tutaj. A noz widelec natchnie cie kiedys do zrobienia czegos podobnego do mudleta. Oczywiscie jako opcja, bo czesc ludzi lubi sobie czytac opisy (ja to sobie robilem tak ze jak chcialem czytac opis to uzywalem ob zamiast ocen ;)
(W pliku jakos jeszcze sobie wrzucilem wyswietlanie pojemnikow, chyba dlatego ze rowniez korzysta z "bazy" typow broni)
Rowniez .xml, ale tym razem w lua:
[Ocenianie_Itemow.txt](https://github.com/tjurczyk/arkadia-skrypty/files/981862/Ocenianie_Itemow.txt)

**Comment by tjurczyk** [comment]
Dzięki, zapisałem sobie. Jak kiedyś będę coś takiego robił to będę pamiętał.
