### ISSUE TITLE
Custom eventy

### ISSUE THREAD

**Issue by baranno** [tjurczyk/arkadia-skrypty#14]
Hej,

Można liczyć na dodanie customowych eventów przy zakończeniu chodzika, mam tu na mysli ten fragment:

  -- if the same location as current, don't run
  if amap.walker == false and (table.size(speedWalkPath) == 0 or amap.curr.id == speedWalkPath[table.size(speedWalkPath)]) then
    amap:print_log("Chcesz isc do aktualnej lokacji?")
    raiseEvent("WALKER_FINISH")
    return
  end

i ten:

  if not curr_move then
    -- no index in speedWalkDir, end the walker
    amap.walker_dest = nil
    amap:stop_walker()
    raiseEvent("WALKER_FINISH")
    return

**Comment by tjurczyk** [comment]
Tak, można, będą dodane. Musze tylko spisać jakoś sensownie dokumentację do tego.

**Comment by Akshuurg** [comment]
Oo elegancko. Kiedy mozna spodziewac sie aktualizacji? To strasznie ulatwi zycie.

**Comment by gangbang69** [comment]
też by mi się przydały te eventy...

**Comment by Akshuurg** [comment]
@tjurczyk: dzieki za czas i zaangazowanie, skrypty wygladaja lepej z kazdym updatem!
Brakuje juz tylko eventow po zakonczeniu chodzika :/

Pozdro!

**Comment by tjurczyk** [comment]
Więcej eventów do chodzika będzie w następnej wersji, czyli najprawdopodobniej jutro polskiego czasu.

**Comment by tjurczyk** [comment]
Dodane od 2.18 (update dostępny 15 lutego)

```
- "amapWalkerTerminated"

  Event podniesiony gdy chodzik zostanie przerwany (niezaleznie od przyczyny: bloker, ruch manualny, '/stop').

- "amapWalkerFinished"

  Event podniesiony gdy chodzik dotrze do celu.

- "amapBlockerFired"

  Event podniesiony gdy ktorys z blokerow zostal odpalony

- "amapPauserStarted"

  Event podniesiony gdy zadzialal pauser (czyli tymczasowo wylaczyl mapper)

- "amapPauserStopped"

  Event podniesiony gdy pauser zostal wylaczony (czyli wlaczyl mapper z powrotem)
```

@Akshuurg @gangbang69 @baranno
