### ISSUE TITLE
mudlet 3.1

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#140]
Na stronie mudleta nie ma juz wersji 3.0 do pobirania tylko 3.1

problem jest z plikiem konfiguracyjnym imie.txt.

mozna go ustawic , ale nie zapamietuje by ladowac go automatycznie i trzeba za kazdym razem recznie.

**Comment by ftpd** [comment]
U mnie działa. Pokaż swój trigger na ładowanie? U mnie wygląda tak: https://i.imgur.com/1cG7ugg.png (olej te expandAliasy, to moje bzdurki). No i: jesteś pewien, że trigger ładujący jest _pod_ skrypty_master?

**Comment by Nookie87** [comment]
Dzięki Werbat, mnie pomogło!
