### ISSUE TITLE
gag-owanie walki ?

### ISSUE THREAD

**Issue by jorhni** [tjurczyk/arkadia-skrypty#141]
Widok z 2 roznych postaci ...

> 4/6] Powaznie ranisz brzuchatego kosmatego kilmulisa dlugim zdobnym czekanem, trafiajac go w lewa 
lape. Brzuchaty kosmaty kilmulis umarl.

> [JA 7/7] Ruszasz do przodu, w pol kroku wyprowadzajac szybkie uderzenie prostym polyskliwym mieczem, 
ktore z potworna moca tnie brzuchatego skoltunionego stwora doslownie w pol. Brzuchaty skoltuniony stwor umarl.

Czyżby współprowadzący miecznika inaczej to widział? Gracz mówi, że nie widzi specy miecznika.

**Comment by tjurczyk** [comment]
Nie wiem. Potrzebne są konkretne opisy.
