### ISSUE TITLE
Okno kondycje nowe funkcje

### ISSUE THREAD

**Issue by Nookie87** [tjurczyk/arkadia-skrypty#142]
Czy dałoby się wstawić albo gdzie pogrzebać aby sprawić, że w oknie kondycji kiedy nakierujemy kursorem na healthbar ### byłaby komenda dla legionisty "gzwycofaj sie za" ?

Funkcja ta już istnieje dla wrogów, jest tam inna komenda po prostu, a dla członków drużyny obecnie nic tam nie ma, więc myślę że to kwestia przekopiowania i delikatnej zmiany kilku linijek.
Jeśli nie masz czasu to jak mógłbyś wskazać gdzie szukać a sam spróbuje to ustawić.

Kolejna rzecz - gdzie można zmienić liczenie kondycji na pasku dolnym (obok róży wiatrów). Obecnie jest 6, a chciałbym mieć ustawione 7.

**Comment by ftpd** [comment]
Ale taka prośba: niech jeden ticket będzie o jednej sprawie, a nie 'kolejna rzecz' i w jednym tickecie cała litania ;-)

**Comment by tjurczyk** [comment]
Od 3.4. Tak jak pisał ftpd, jedna rzecz = jeden issue.
