### ISSUE TITLE
podliczenie wartosci wszystkich kamieni

### ISSUE THREAD

**Issue by Walkir** [tjurczyk/arkadia-skrypty#145]
Widziałem, że niektóre skrypty mają podliczanie wartości wszystkich ocenionych kamieni.
Możnaby coś takiego tutaj zakodować?

**Comment by animal793** [comment]
jest

/ocenkamienie

**Comment by Walkir** [comment]
rzeczywiscie, dzieki, szukalem w pomocy do ekwipunku a jest w aliasach :)
