### ISSUE TITLE
gmcp nie łapie po zalogowaniu z innej sesji

### ISSUE THREAD

**Issue by ftpd** [tjurczyk/arkadia-skrypty#147]
Po zalogowaniu się mudletem na już zalogowaną postać (
Twoja postac jest juz w grze. Przejmujesz nad nia kontrole) nie łapie się nic z gmcp. Paski n'shit.

**Comment by baranno** [comment]
Mi zazwyczaj pomaga: /walka_restart

**Comment by ftpd** [comment]
Poradzić to ja sobie umiem, zgłaszam dla porządku ;-)

**Comment by tjurczyk** [comment]
U mnie działa. Jak to zreprodukować?

**Comment by ftpd** [comment]
Zaloguj się z telnetu, włącz mudleta, lognij sie.

**Comment by tjurczyk** [comment]
U mnie zadziałało. Zrób screenshot jak to wygląda. I sprawdź czy na 3.3 też to się dzieje.

**Comment by ftpd** [comment]
Nawet Ci filmik nagrałem: https://insomniac.pl/f/logowanie.mov. Specjalnie jest ~20 sekund 'nic się nie dzieje' po zalogowaniu, żebyś zobaczył, że się automagicznie nie naprawia. A potem dopiero smaczek.

**Comment by ftpd** [comment]
Pomogło włączenie MSDP.
