### ISSUE TITLE
Pomarańczowa kropka przy mapperze nie znika przy wylogowaniu.

### ISSUE THREAD

**Issue by ftpd** [tjurczyk/arkadia-skrypty#148]
Jeśli zakończę np. siedząc i nie wyłączając mudleta zrobię 'reconnect', pomarańczowy indicator przy mapie (bloker? pauser?) zostaje, przez co po zalogowaniu kropa się nie porusza. Powinno być to resetowane przy disconnect/connect.

**Comment by tjurczyk** [comment]
Naprawione w 3.3.
