### ISSUE TITLE
Alias do kolorowania tekstu.

### ISSUE THREAD

**Issue by ctarx** [tjurczyk/arkadia-skrypty#15]
Dodałbym możliwość tymczasowego kolorowania tekstu według zadanego wzoru.
Przykładowo `/moj_alias ogromn[a-z]* agresywn[a-z]* troglodyt[a-z]*`
Kolor wyróżnienia mógłby być ustalany w pliku imie.txt

**Comment by ftpd** [comment]
+1

**Comment by tjurczyk** [comment]
Dostępne powyżej 2.15.
https://i.imgur.com/Kr5ggln.png
