### ISSUE TITLE
specyk

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#152]
Na Legionie na misterku wylapuje speca partka

[PAR 1/7] Z oszczednego zamachu XXXX uderza swym misternym obosiecznym toporem w wypolerowanego 
blyszczacego golema, nieznacznie raniac jego nogi.

**Comment by Nookie87** [comment]
To nie jest spec legiona, a opis ciosu misterka.

**Comment by animal793** [comment]
zle sie wyrazilem:) edytuje:)
