### ISSUE TITLE
Gag

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#155]
Szkarlatne luski rogatej tarczy XXX dzwiecza cicho, gdy ten oslania sie nia przed uderzeniem 

Szkarlatne luski dzwiecza cicho, gdy oslaniasz sie swoja rogata tarcza przed uderzeniem dynamicznego wypolerowanego golema.

mozna dodac [Par Tarcza]

**Comment by tjurczyk** [comment]
Nazywaj te tickety jakoś sensowniej, żeby od razu było wiadomo o co chodzi.
Dodałem od następnej wersji.
