### ISSUE TITLE
Wyróżnienie stuna.

### ISSUE THREAD

**Issue by ftpd** [tjurczyk/arkadia-skrypty#16]
Patterny:

(Powoli osuwasz sie na ziemie|Potem robi sie ciemno|Sila uderzania zamroczyla cie|czujesz, ze tracisz przytomnosc|Nagle czujesz jak na glowe spada ci ciezki sznur|Nagle czujesz, ze tracisz kontrole nad swym cialem| wali cie na odlew.*chwiejesz|ze swiat przed twoimi oczami niknie|Przymroczony tym uderzeniem czujesz jak nogi|Swiat przed twoimi oczami ciemnieje. Czujesz, ze tracisz wzrok!)

Ewentualnie możnaby wykorzystać do czegoś pole Alert: na pasku - stun i wytrącanie wydaje się idealnym pomysłem. Dla pewności daję patterny na koniec stuna:

(Powoli dochodzisz do siebie|Czujesz jak slabosc po zadanym ciosie w glowe mija|Udaje ci sie uwolnic z sieci|Powoli odzyskujesz swobode ruchow)

**Comment by tjurczyk** [comment]
Dodane od 2.14c.
