### ISSUE TITLE
innych_parowanie

### ISSUE THREAD

**Issue by Walkir** [tjurczyk/arkadia-skrypty#161]
Mam ustawione:
  ["innych_parowanie"] = 1,
jednak gdy przeciwnik osłoni się tarczą albo cios zostaje wyparowany przez zbroje to opis nie jest gagowany. Widzę, że gagi są porobione ale z jakiegoś względu nie są aktywne.

**Comment by tjurczyk** [comment]
Na opcję 1 trzeba trochę poczekać. Tamte regexpy były robione dość dawno. Trzeba sprawnie przekopiować regex z `color` do `delete`. To pewnie zrobię za jakiś miesiąc-dwa.

**Comment by tjurczyk** [comment]
Mam na to ticket: https://github.com/tjurczyk/arkadia-skrypty/issues/266
