### ISSUE TITLE
mapper nie przemieszcza kropy na rzece u drucholi

### ISSUE THREAD

**Issue by ssnakey** [tjurczyk/arkadia-skrypty#17]
`
> rzeka
Wchodzisz do wody.
Na rzece pod skalistym brzegiem.
Mozesz stad poplynac na polnoc i zachod.
Osiem nadgnilych czerniejacych pni i cztery rozgalezione zlamane konary.
> podplyn do pnia
Cicho podplywasz do nadgnilego pnia i lapiesz sie go. Jest zimny i sliski, ale ulatwi utrzymanie sie na wodzie, zarazem kryjac przed wzrokiem obserwatorow.
Utrzymujesz sie na powierzchni wody.
popchnij pien na n
Skryty za nadgnilym czerniejacym pniem zaczynasz plynac na polnoc.
Przeplywasz, kryjac sie za nadgnilym czerniejacym pniem.
Na powierzchni wartkiej rzeki.
Mozesz stad poplynac na polnoc, zachod i poludnie.
Nadgnily czerniejacy pien.
Utrzymujesz sie na powierzchni wody.
`

Mapper nie przesuwa kropki po mapie chyba najwygodniej byloby to zrobic nie tyle dla komendy
_popchnij_ pien/konar/zwloki na n/s/e/w

a do takiego patternu z odpowiednim kierunku np:
`
^{|> }Skryty za * zaczynasz plynac na polnoc.$
`

**Comment by tjurczyk** [comment]
Dodane powyżej 2.15.
