### ISSUE TITLE
Wytrącanie broni w Blaviken (zjawy)

### ISSUE THREAD

**Issue by Nookie87** [tjurczyk/arkadia-skrypty#177]
z 1 osoby:
Czujesz ze dzierzona przez ciebie bron zaczyna podrygiwac, wpadajac w dziwny rezonans z narastajacym w komnacie niskim, grobowym dzwiekiem. Nagle potezna magia wyrywa ci ja z dloni i rzuca gdzies w glab korytarza!

z 3 osoby:
Dzierzona przez XXX bron zaczyna podrygiwac, wpadajac w dziwny rezonans z narastajacym w komnacie niskim, grobowym dzwiekiem.

Można by jakiś alert zrobić, tak że też inni członkowie drużyny widzieli, że komuś wytrąciło

**Comment by tjurczyk** [comment]
Dodane od 3.5.
