### ISSUE TITLE
ciosy jataganem

### ISSUE THREAD

**Issue by Walkir** [tjurczyk/arkadia-skrypty#178]
```
Jasniejaca luna znaczy powietrze, gdy dlugim cieciem jasniejacego zdobionego jatagana masakrujesz
Nagly blysk rozswietla cale otoczenie, gdy szybkim pchnieciem jasniejacego zdobionego jatagana ranisz
Swietlista smuga przecina powietrze, gdy szybkim pchnieciem jasniejacego zdobionego jatagana ledwo muskasz
```

Początek jest inny ale wszystkie opisy obrażeń wyglądają normalnie.

**Comment by animal793** [comment]
Jakby dalo sie zrobic by wszystkie opisy roznych broni czy opisow walki gdzie wystepuje ledwo muskasz/lekko ranisz/ranisz/powaznie ranisz/bardzo ciezko ranisz/masakrujesz

Wylapywalo jesli wystepuje i gagowowalo 1/6 
2/6
I tak dalej zaoszczedzilo by to sporo roboty.

Nie wiem czy to da sie zeobic.

Byloby fajnie.

Bo jak walkirr pisze. Nawet opisy zabojcow mimo ze obfite zawieraja te standardowe wyroznienia obrazen.

Nie trzeba by wtedy pojedynczo wylapywac i dodawac.


Rzucam jak propozycje jakas tam do rozwazenia.


Oczywisice broni takich jak miecze arlekina to nie wylapie ale sporo rzeczy i owszem

**Comment by tjurczyk** [comment]
Dodane od 3.5.
