### ISSUE TITLE
sklad druzyny komenda /obecni

### ISSUE THREAD

**Issue by ssnakey** [tjurczyk/arkadia-skrypty#18]
Arkadia skrypty, ver 2.14a

'druzyna
'Druzyne prowadzi Crer i oprocz ciebie sa w niej jeszcze: Atrain, Gotfried, Terum, Celeste, Orrgar, Rimi, Ferd, ''Zeep, Numeron, Othis, Balwur, Luinarienn i Hasandara.
'Jako cel obrony wskazany zostal Crer.
'> /obecni
'(skrypty): Brakuje: Brygu

Pomimo ze Bryga nie ma w druzynie dalej wywala ze go brakuje.

**Comment by tjurczyk** [comment]
Poprawione na 2.14c.
