### ISSUE TITLE
Okno kondycji : osoby neutralne

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#180]
sytuacja...

wchodze na lokacje ... 

gracz jest ciezko ranny walczy z dwoma orkami

Okno kondycji nie pokazuje mi z kim walczy kto jego atakuje, do tego nie jestem w stanie go zaslonic klikajac w oknie bo nie ma takich mozliwosci.

czy mozna rozszerzyc dzialanie skryptow i na osoby "neutralne"

**Comment by tjurczyk** [comment]
Ale zasłona zadziała: `/zas 2` zasłoni przed przeciwnikiem z id 2, niezależnie kogo ten przeciwnik bije. Czy nie o to chodzi?

**Comment by animal793** [comment]
No rozchodzi sie o to by na oknie koncji jesli to mozliwe bylo widac kto z kim walczy i by dalo sie zaslonic z okna osobe neutralna poza teamem

**Comment by tjurczyk** [comment]
To raczej nie jest możliwe na chwilę obecną.
