### ISSUE TITLE
Okno kondycji - focus

### ISSUE THREAD

**Issue by baranno** [tjurczyk/arkadia-skrypty#182]
Istnieje mozliwosc wybrania sposobu osadzenia tego okna? Nie ukrywam po staremu bylo lepiej, teraz jak klikam w oknie to glowne okno mudleta traci focus (okno kondycji mam nie zadokowane), przez co musze ponownie klikac w pasek do komend za kazdym razem jak klikam cos w oknie kondycji

**Comment by animal793** [comment]
no to tylko u ciebie wystepuje to bo u mnie simga i nic nie musze przeklikiwac.

**Comment by baranno** [comment]
Czy ty sie k*** w kazdym zgloszeniu musisz udzielac? To ze u Ciebie to nie wystepuje to w cale nie znaczy ze u innych tez nie. Nic nie wnosisz do dyskusji, pewnie nawet nie przetestowałeś odpowiednio, a sie udzielasz. Zapytalem o mozliwosc przelaczanie sie miedzy starym sposobem wyswietlania tego okna a nowym.

**Comment by animal793** [comment]
Czytaj ze zrozumieniem tekst pisany.

**Comment by tjurczyk** [comment]
@baranno 
Ale jeśli chcesz tak jak po staremu, to nie możesz okna trzymać wbudowanego po prawej stronie pod/nad mapperem? Kwestia powrotu focusa jest chyba obecnie nierozwiązywalna, bo nie ma żadnego API do powrotu do głównego okna. Zapytam na forum Mudleta, czy jest szansa/możliwość zrobienia tego.

Stary sposób trzymania okna był tymczasowych hackiem właśnie do momentu naprawienia zapamiętywania ustawienia okien, więc on już nie wróci. Niepotrzebna komplikacja kodu.
