### ISSUE TITLE
Mapper (pomaranczowy kwadrat): Golem w Kurhanie z Espadonem 

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#183]
Pomaranczowy kwadrat nie gasnie jesli przeszukujemy szczatki golema i nic nie znajdziemy.
Jesli znajdziemy jest ok.

=================

 Podziemna krypta.
Sa tutaj trzy widoczne wyjscia: zachod, wschod i poludnie.
Spora kupka kamieni.
 przeszukaj kamienie
Zaczynasz przeszukiwac spora kupke kamieni.
Jednak nie znalazles niczego interesujacego.

**Comment by tjurczyk** [comment]
Dodane od 3.5.
