### ISSUE TITLE
Mapper: Brak Blokera : Poludniowy kurhan 

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#184]
Kurhan z pulapke z pnaczem za pulapka stoi golem

 e
Probujesz isc w glab korytarza, lecz zwalisty szarawy golem zastepuje ci droge. 
 w
Probujesz isc w glab korytarza, lecz zwalisty szarawy golem zastepuje ci droge. 
 /lok
(mapper): ID lokacji: 16436

Mimo ze blokuje kropka wedruje swobodnie jakbym poszedl dalej.

**Comment by tjurczyk** [comment]
Poprawione od 3.5.
