### ISSUE TITLE
Pomaranczowy kwadrat

### ISSUE THREAD

**Issue by jorhni** [tjurczyk/arkadia-skrypty#189]
Jak w temacie, nie znika:
Szafa, jak znajdziemy:
>przeszukaj szafe
>Zaczynasz przeszukiwac szafe.
>W srodku, wsrod kurzu i pajeczyn znajdujesz posepny cylindryczny kapelusz i dluga wzmacniana kapote 
z kolnierzem.

Szafa, jak nic nie ma:
>przeszukaj szafe
>Zaczynasz przeszukiwac szafe.
>W srodku nic jednak nie znajdujesz.

Szmaty, jak znajdziemy:
>przeszukaj szmaty
>Zaczynasz przeszukiwac szmaty.
>Przepatrujesz wiszace na scianie zwoje lin, powrozow, brudnych placht oraz pek duzych hakow, gdy 
nagle jeden z nich spada na ziemie, najwyrazniej niezamocowany jak pozostale na grubym koluchu. 
Podnosisz go i zabierasz.

Szmaty, jak nic nie ma:
>przeszukaj szmaty
>Zaczynasz przeszukiwac szmaty.
>Przepatrujesz wiszace na scianie zwoje lin, powrozow, brudnych placht oraz pek duzych hakow, nic 
ciekawego tam jednak nie znajdujesz.

**Comment by tjurczyk** [comment]
Dodane od 3.7.
