### ISSUE TITLE
/licz_poziom

### ISSUE THREAD

**Issue by Walkir** [tjurczyk/arkadia-skrypty#190]
Przy epikach źle liczy.
przy epiku powinien dodać 5 podcech

**Comment by animal793** [comment]
Walkir zaden licznik nie liczy powyzej epikow.

**Comment by Walkir** [comment]
ten liczy:
https://licznik-arkadia.rhcloud.com/licznik

chodzi o to żeby chociaż dodawał te cechy zamiast odejmować, raczej nie jest to straszna rzecz do zaprogramowania

**Comment by tjurczyk** [comment]
Powinno dzialac od 3.7.
