### ISSUE TITLE
Odliczanie po wycofce legionisty

### ISSUE THREAD

**Issue by Nookie87** [tjurczyk/arkadia-skrypty#195]
Wycofka legionsity korzysta z tego samego timera co 'zaslanianie'. Można by uwzględnić to przy odliczaniu czasu na dolnym pasku.

[udana]
Unosisz swoja xxx xxx tarcze i szybko przesuwasz sie za XXX, kryjac sie przed atakami XXX.

[nieudana]
Unosisz swoja xxx xxx tarcze i przesuwasz sie w strone XXX, bezskutecznie probujac skryc sie za nim przed 
atakami XXX.

**Comment by chlebik** [comment]
+1 zglosilem, ale pozniej

**Comment by tjurczyk** [comment]
Od 3.7 dodane w zaslonach.
