### ISSUE TITLE
brak obslugi depozytu - Scala, Guleta, Rinde

### ISSUE THREAD

**Issue by jorhni** [tjurczyk/arkadia-skrypty#196]
Brak obslugi depozytu w:
1/ Scala - Izba celna (lokacja 893)
2/ Rinde - Bank, Rinde (lokacja 1999)
3/ Guleta - Przestronny magazyn ( lokacja 8059) - tu nie wystarczy dopisac do listy depozytow, nie dopisuje poprawnie jego zawartosci do bazy:
> /depozyt
> przejrzyj depozyt
> Zazywny elegancki mezczyzna pokazuje ci zawartosc twojego depozytu. Twoj depozyt 
> zawiera grawerowany kompas.
> Jesli chcesz, mozesz swobodnie wkladac i wyjmowac przedmioty ze swojej skrytki, zostanie ona z 
> powrotem zabezpieczona, kiedy tylko opuscisz pomieszczenie.
> 
> (skrypty): Ok, depozyt 'guleta' uaktualniony

Mimo informacji o poprawnym wpise, po komendzie /depozyty Gulety nie ma.

**Comment by tjurczyk** [comment]
Poprawione od 3.7, powinno wszystko dzialac.
