### ISSUE TITLE
Dublowanie binda ataku

### ISSUE THREAD

**Issue by Roslinek** [tjurczyk/arkadia-skrypty#198]
Zauwazylem, ze jak ma sie szesciu przeciwnikow to szesc razy pokazuje 

[1] [  >#  ] Motaro [PRZYBYWA] [ ZE ] [  E ]!

   F1 atak   F2 przelam obrone   F3 zablokuj

Dalo by sie to zrobic zeby pokazywalo ostatniego zbindowanego ? Czy jakos tak?

**Comment by tjurczyk** [comment]
Nie da sie tego zrobic w dosc prosty sposob, bo te bindy dzialaja z GMCP. Jakiekolwiek sztuczne opoznienia nie zadzialaja, bo (1) arkadia jest asynchroniczna i (2) ludzie maja rozne pingi do arkadii.
