### ISSUE TITLE
Ocenianie zbroj

### ISSUE THREAD

**Issue by Roslinek** [tjurczyk/arkadia-skrypty#199]
Mozna by zrobic cos takiego:

Jakosc zbroi = (waga zbroi / calkowita jakosc zbroi) * (ilosc chronionych lokacji/5)

I gdzies podawac na dole oceny

Chyba ze ktos wymysli lepszy wzor.

**Comment by tjurczyk** [comment]
Nie rozumiem, co to ma na celu?

**Comment by tjurczyk** [comment]
Zamykam, bo nie zostalo to sprecyzowane.
