### ISSUE TITLE
Powozy - maribor

### ISSUE THREAD

**Issue by barrinek** [tjurczyk/arkadia-skrypty#2]
Poprawić wsiadanie do powozów:
Kolyszac sie przybywa otwarty jadacy powoz.
Otwarty jadacy powoz powoli zatrzymuje sie.

bind [: wem;wsiadz do wozu;wlm

Woznica oznajmia gromkim glosem: Postoj, przystan powozowa.
Woznica poprawia ulozenie lejcow na kozle.
wem
wsiadz do wozu
wlm
Bierzesz wiele zlotych monet, piec srebrnych monet i 31 miedzianych monet z otwartej wyszywanej 
skorzanej sakiewki.
> Do czego zamierzasz wsiasc?

**Comment by tjurczyk** [comment]
Od jakiegoś czasu jest to poprawione, na pewno masz nową wersję?

https://i.imgur.com/4FDCoYU.png

Jeśli nie jesteś na 2.14a to się zaktualizuj.
