### ISSUE TITLE
Ogluszanie druzyny

### ISSUE THREAD

**Issue by filipbober** [tjurczyk/arkadia-skrypty#200]
Jest wykrywanie ogłuszenia, ale przydałaby się możliwość jakiegoś wyróżnienia w wyraźny sposób, gdy ktoś z drużyny zostaje ogłuszony - podobnie jak z przełamywaniem, żeby prowadzący przypadkiem nie uciekł z lokacji zostawiając nieszczęśnika.
Dodatkowo pojawiająca się opcja z bindem na zasłonięcie ogłuszonego też byłaby przydatna.

**Comment by tjurczyk** [comment]
Binda na zasloniecie ogluszonego nie bedzie, bo to duplikowanie `/za [id]`.
Co do wykrywania ogluszania, potrzebne sa dokladne opisy.

**Comment by tjurczyk** [comment]
Zamykam, bo nie pojawily sie opisy. Jak beda, mozna zalozyc ticketa z konkretnymi opisami.
