### ISSUE TITLE
Brak skryptu na zazywanie ziol

### ISSUE THREAD

**Issue by filipbober** [tjurczyk/arkadia-skrypty#201]
Być może przeoczyłem i skrypt jest, ale nie znalazłem. Jesli tak, to można zamknąć od razu.

Przydałby się skrypt na zażywanie ziół - licznik kiedy można zażyć po przerwaniu walki, potem opuszczenie broni zgodnie z imie.txt (tak chyba najpewniej), wzięcie konkretnej mieszanki z woreczków (zdefiniowanej np. w imie.txt) i dobycie z powrotem broni. Wersja pro mogłaby jeszcze szacować kiedy możemy ponownie użyć mieszanki.

Wyszło z tego całkiem sporo roboty, ale myślę, że wielu graczom coś takiego bardzo by się przydało.

**Comment by Walkir** [comment]
masz może policzone te czasy? z tego co wiem różne zioła, można ponownie stosować w różnych odstępach czasu?

**Comment by filipbober** [comment]
Nie mam niestety. Zwykle na oko zażywam. Faktycznie, chyba jest różnie w zależności od zioła. Mandragora jakoś strasznie długo, podobno.

A zażywać można chyba równo po 3s od walki.

**Comment by tjurczyk** [comment]
Taki skrypt to temat na dluzsze przemyslenie. Przede wszystkim do ticketa warto wrzucic jakis poczatkowy plan.

W liscie TODO jest ulepszenie calego skryptu ziol, to dosc duzy projekt.
