### ISSUE TITLE
dobywanie/opuszczanie broni

### ISSUE THREAD

**Issue by Walkir** [tjurczyk/arkadia-skrypty#202]
niestandardowe dobycia broni:

```
Dobywasz XXX zaciskajac dlon na rekojesci. Suchy trzask stawow mowi ci, ze odteraz stanowicie swe dopelnienie. Jedno jest niczym bez drugiego.

Pewnym chwytem dobywasz XXX.

Gdy dobywasz XXX, klinga broni rozgrzewa sie do czerwonosci.

Niechetnie opuszczasz swoj zlowrogi orez.

Zamaszystym ruchem wznosisz wielki kamienny kafar do gory, by wesprzec go na ramieniu.

Czujesz, jak przez twoje palce przebiega delikatne, elektryzujace drzenie, jakby bulawa witala sie z uteskniona dlonia. Po sekundzie nagle orientujesz sie, ze znajdujesz sie wewnatrz oszalalej burzy i dzieki sile swojej woli wypychasz ja ze swojego umyslu, wiezac wewnatrz nabijanej cwiekami glowicy.

Gdy rozluzniasz chwyt na iskrzacej zdobionej bulawie, pomiedzy cwiekami na glowicy broni przestaja rzeskakiwac iskry.

Z lekkoscia dobywasz jasniejacego zdobionego jatagana, a ten rozblyskuje jeszcze mocniejsza poswiata.
Szybkim ruchem opuszczasz jasniejacy zdobiony jatagan, a luna wokol broni nieznacznie przygasa.
```

**Comment by filipbober** [comment]
To ja jeszcze dopiszę do tematu inną kwestię związaną z dobywaniem. 

Przydałoby się , żeby bronie chowano domyślnie w odwrotnej kolejności do dobywania, bo w obecnym stanie na dualu zamienia co dobycie pierwszą broń z drugą, przy ustawieniu:
scripts.inv.main_weapons_action = { 1, 2 }

Czyli mielibyśmy zamiast obecnego
/db
podobadz broni z pierwszej pochwy
podobadz broni z drugiej pochwy
/ob
powsun bron do pierwszej pochwy
powsun bron do drugiej pochwy

Takie coś
/db
podobadz broni z pierwszej pochwy
podobadz broni z drugiej pochwy
/ob
powsun bron do drugiej pochwy
powsun bron do pierwszej pochwy

**Comment by tjurczyk** [comment]
@Walkir @filipbober Dodane w 3.11.
