### ISSUE TITLE
Zerowanie postepow nie zeruje numeracji

### ISSUE THREAD

**Issue by filipbober** [tjurczyk/arkadia-skrypty#204]
Komenda '/postepy2_reset' resetuje postępy, ale numeracja pozostaje, więc pierwszy postęp po resecie ma kolejny numer, tak jakby resetu nigdy nie było.

**Comment by tjurczyk** [comment]
Tak musi pozostac, poza tym jest jedna baza na wszystkie postacie, dlatego nie jest mozliwe wyczyszczenie postepow na postac i nagle wyzeruje calosc. 
Jesli chcesz globalny reset to: wylacz mudleta, usun `Database_improvee.db` w katalogu profilu i wlacz mudleta, licznik bedzie od 0.
