### ISSUE TITLE
Bind w kurhanie na bagnach jest niekompletny

### ISSUE THREAD

**Issue by filipbober** [tjurczyk/arkadia-skrypty#205]
Przechodząc z lokacji 16435 na lokację 1636 (na bagnach w Wissenlandzie) jest bind 'przeskocz pulapke', a powinno być 'zlap za pnacze;przeskocz pulapke'. W obecnej formie można łatwo zezgonić. Dodatkowo komenda 'wejdz w otwor' pojawia się jako bind w poludniowo-wschodnim kurhanie, ale mapa nie jest aktualizowana.

Przy okazji: w kurhanie z espadonem bezpieczniej byłoby, gdyby oprócz specjalnego wyjścia 'przeczolgaj sie na polnoc' rowniez odpowiednio 'n' i 's' po obydwu stronach kurhanu omijało pułapkę. W przeciwnym razie można przez przypadek stracić głowę...

**Comment by tjurczyk** [comment]
W nowej mapie to bedzie dodane.
