### ISSUE TITLE
Przemykanie na niestandardowe kierunki

### ISSUE THREAD

**Issue by filipbober** [tjurczyk/arkadia-skrypty#208]
Przmykanie nie działa, gdy przemykamy na niestandardowe (tj. inne niż kierunki z róży wiatrów) kierunki. Dotatkowo mapa gubi się, kiedy ręcznie przejdziemy na lokacje, np. 'przemknij namiot' albo 'przemknij wyjscie'.

Wydaje mi się, że jeżeli w gmcp.room.info.exits jest wyjście z lokacji, to powinno również działać przemykanie w danym kierunku.

**Comment by tjurczyk** [comment]
Dodane w 3.11.
