### ISSUE TITLE
Blokery pocztowe cd.

### ISSUE THREAD

**Issue by ftpd** [tjurczyk/arkadia-skrypty#21]
Wpisanie 'e' - "Zaden list nie zostal zaznaczony do skasowania."
Wpisanie 'n' - "Nie mozesz zgrac listu, gdyz nie masz go gdzie zapisac."
Wpisanie 'd' przy skasowanym liście - "Nie zaznaczono nowych listow do skasowania."
Wpisanie 'u' przy od-skasowanym liście - "Nie odznaczono zadnych listow od skasowania."

Ogólnie to bardziej enhancement niż bug, trzeba by przemyśleć wyłączanie skryptów w trybie poczty może?
Ewentualnie po prostu te 3 patterny jako blocker i powinno być ok.

**Comment by tjurczyk** [comment]
Z tym jest taki problem, że niekoniecznie każdy z tych wyrażeń zawsze jest blokerem. Przykładowo:

`Wpisanie 'e' - "Zaden list nie zostal zaznaczony do skasowania."`

Jeśli jest lokacja na 'e', wszystko ok, ale jeśli nie ma to mapper cofnie niepotrzebnie lokację. Te patterny nie podpadają pod normalną idee blockerów. Można myśleć o tym wyłączaniu, chociaż to trochę słabe rozwiązanie, chciałbym unikać rozwiązań, gdzie odcinam chodzenie.

Ewentualnie trzeba zebrać patterny, które oznaczają początek interfejsu listowego i jego koniec i wtedy wyłączać/włączać podążanie mapy. Trzeba się zastanowić czy ma to sens.

**Comment by ftpd** [comment]
W mapperze thornaga oprócz blokerów (które cofały) istniała też instytucja 'pauserów', że po prostu po włączeniu pauzy się mapper nie poruszał. Może coś w ten deseń?

**Comment by tjurczyk** [comment]
Takie coś ma sens. Trzeba tylko postanowić jaki keybind będzie do przełączania, żeby był łatwo dostępny. Może to być "\", który jest teraz używany tylko do brania butelki jak się skończy. W sumie i tak miało to być przeniesione do ']'.

**Comment by ftpd** [comment]
Nie no, tam się pausery same odpalały.

**Comment by tjurczyk** [comment]
No to trzeba zebrać wszystkie wzorce do stopowania i wznawiania. A najlepiej wziąć je od Thornaga. Ja nie mam jego skryptów.

**Comment by ftpd** [comment]
Ja mam trochę, chociaż z pewnością nie wszystkie: https://bitbucket.org/ftpd/tf-scripts/src/master/arkadia/map.tf

**Comment by tjurczyk** [comment]
Pausery są już dodane. Gdyby były jakieś niedodane należy zgłaszać w nowym tickecie.
