### ISSUE TITLE
Zmiana kolorow dla poprawnego wycofania sie legionisty

### ISSUE THREAD

**Issue by chlebik** [tjurczyk/arkadia-skrypty#210]
Obecnie przy poprawnym wycofaniu sie legionisty za kogos (z perspektywy 1 os.) komunikat jest 'na szaro'. Daloby sie go zrobic na troche bardziej widoczny kolor? Najlepiej nie zielony/czerwony bo te juz sa w komunikatach uzywane. Cyan? Yellow?

**Comment by tjurczyk** [comment]
https://github.com/tjurczyk/arkadia-skrypty/issues/195

**Comment by tjurczyk** [comment]
Od 3.7.
