### ISSUE TITLE
Brak odliczania dla niepoprawnego wycofania legionisty

### ISSUE THREAD

**Issue by chlebik** [tjurczyk/arkadia-skrypty#211]
Kiedy legionista sie wycofuje bez powodzenia/z powodzeniem nie odpala sie licznik dla kolejnego manewru.

**Comment by tjurczyk** [comment]
https://github.com/tjurczyk/arkadia-skrypty/issues/195

**Comment by tjurczyk** [comment]
Dodane w 3.7.
