### ISSUE TITLE
Mapa przestaje sledzic gdy usiadziemy na hustawce

### ISSUE THREAD

**Issue by filipbober** [tjurczyk/arkadia-skrypty#212]
'usiadz na hustawce'
Siadasz z usmiechem na zawieszonej przenosnej eleganckiej hustawce.
'wstan'
Zeskakujesz z zawieszonej przenosnej eleganckiej hustawki.

Gdy wstaniemy musimy użyć '/zlok', żeby mapa zaczęła ponownie śledzić nasze położenie.

**Comment by tjurczyk** [comment]
2.6
