### ISSUE TITLE
Mapper gubi sie na wejsciu do warowni

### ISSUE THREAD

**Issue by chlebik** [tjurczyk/arkadia-skrypty#215]
MApper sie gubi przy wejsciu do warowni Poitiers z lasu. W sensie 'zostaje' na lokacji lasu.

**Comment by chlebik** [comment]
Nie mam jak tego teraz sprawdzic, ale z perspektywy czasu wydaje mi sie, ze to nie jest problem z gubieniem sie mappera per se, ale uzywania binda na podazanie. 

W pliku konfiguracyjnym jest ustawienie:  **ateam.special_follow_bind_mode** i jak ustawi sie to na wartosc 2 wowczas jak np. ktos z druzyny zaczyna sie gdzies wspinac/plynac/przechodzic to jest podpinany bind na to.

Wydaje mi sie, ze w takich sytuacjach wlasnie mapper sie gubi. Daje sie to tez zaobserwowac np. przy zejsciu do skavenow w KV - kiedy daje '[' by podazac za czlonkiem druzyny/prowadzacym to schodzac na dol/idac w gore mapper sie gubi. Natomiast jak po prostu nacisne niestandardowe wyjscie w mapperze (pojawiajace sie przy rozy wiatrow) to wszystko jest w porzadku.

Zatem mysle, ze to nie jest problem konkretnie mappera w tej jednej lokacji, ale calosciowego systemu podazania przy wcisnieciu binda.

**Comment by tjurczyk** [comment]
Mapper nie gubi się przy wejściu do warowni, było to już wielokrotnie testowane, nie podejrzewam, aby Ci się tam zgubił.

Bardziej prawdopodobne jest to, że zgubił Ci się mapper jak prowadzący szedł przez las i nie było widocznych kierunków ('podaza w las', 'podaza we mgle', itp). 
Bind na wspinanie się pokazał i jak go wcisnąłeś to mapper nie był na poprawnej lokacji (pod warownią), więc mapper nie poszedł do warowni. W następnej aktualizacji jest to poprawione w taki sposób, że na górze po wspinaczce jest ustawiony GPS po shorcie/wyjściach lokacji. Obstawiałbym taki scenariusz.

Ale jak będziesz miał takie przypadki to zawsze zbieraj logi. Poza tym

**Comment by chlebik** [comment]
Spoczko, to w takim razie mozna wstepnie ticket zamknac.
