### ISSUE TITLE
opcjonalne skrocone opisy w oknie kondycji

### ISSUE THREAD

**Issue by Walkir** [tjurczyk/arkadia-skrypty#216]
Da się zrobić żeby w oknie kondycji wiersze się zawijały? Bo często opis wroga jest za długi i nie widzę kto kogo bije.

**Comment by tjurczyk** [comment]
Co prawda zawijania sie nie da, ale dobrym pomyslem byloby zrobienie opcjonalnej wersji skroconych shortow w oknie kondycji.

**Comment by tjurczyk** [comment]
Dodane od nastepnej wersji:

```
-- Zawijanie wierszy w oknie kondycji.
-- Procentowa wartosc. 0.95 (domyslnie) to 95%
-- 0.8 bedzie 80%, itp.
scripts.ui.states_window_p_width = 0.95
```
