### ISSUE TITLE
Dodatkowy tryb 'co zrobic po zaslonie'

### ISSUE THREAD

**Issue by chlebik** [tjurczyk/arkadia-skrypty#218]
Czesto jest tak, ze przeciwnicy, z ktorymi walczymy po zaslonieciu przelamuja i wtedy na zaslonietego rzuca sie cala ekipa (przed ktorymi zostala dana postac zaslonieta). Moze byloby fajnie dorzucic na pasek (tak jak np. jest z trybem ataku/zbierania z cial) wartosc booleanowska - przestan zaslaniac po zaslonie. Ustawiamy na TRUE i od tej pory po kazdej udanej zaslonie od razu ja puszczamy. Jesli jest FALSE to zaslona jest trzymana ile wlezie.

**Comment by tjurczyk** [comment]
Od 3.7 w configu:

```
-- Ustawianie puszczania zaslon
-- w mudlecie do zmiany sluzy komenda '/puszczaj_zaslony'
-- 
-- Dozwolone wartosci:
-- true - beda puszczane
-- false - nie beda puszczane
ateam.release_guards = false
```
