### ISSUE TITLE
Wliczanie 'minimalnych' do tablicy postepow

### ISSUE THREAD

**Issue by chlebik** [tjurczyk/arkadia-skrypty#219]
Tak jak w temacie - obecnie po /postepy widzimy postepy od nieznakow. Ale to dalej niewiele mowi ile zajelo nam wbicie tych nieznakow - bo liczy od zalogowania, a nie od rozpoczecia bicia.

**Comment by tjurczyk** [comment]
Wbicie nieznakow powinno dzialac od momentu pierwszej smierci wroga. Jestes pewien, ze to nie dziala w ten sposob? Jesli zabiles chociazby krolika, a za 2h zaczynasz expienie, to czas nieznakow pokaze wlacznie z tymi 2h. Mozna dodac cos w stylu `/exp_start`, aby wymusic manualny start expeinia, just in case.

**Comment by chlebik** [comment]
Stestuje dla pewnosci. Ja dosc czesto zostawiam kompa wlaczonego przez noc i Mudleta tez. Tym samym moze tutaj w zwiazku ze zmiana daty sa jakies krzaczki. Sprawdze to na spokojnie na dniach bo troche mam weekend daleko od arki.

**Comment by chlebik** [comment]
Ok po stestowaniu na zrestartowanym mudlecie faktycznie dziala. Issue zamykam.
