### ISSUE TITLE
"Wieczne" bindy [ i ] i niektóre komunikaty o alertach.

### ISSUE THREAD

**Issue by ftpd** [tjurczyk/arkadia-skrypty#22]
Kolejne 'do przemyślenia': aktualnie bindy [ albo ] mają ustawiony timer i po N sekundach przestają działać. Nie mogłyby trwać 'wiecznie' albo 'do pierwszego naciśnięcia'? Sytuacja hipotetyczna: naprawiam się u kowala, dostaję broń, binduje ] na dalszą naprawę - a w tym czasie się zagapiłem i zacząłem oglądać [nagie kotki w Internecie](https://www.youtube.com/watch?v=eWEjvCRPrCo), wracam, a bind jest już nieaktualny. Przy prostych komendach spoko, ale IMHO mogłoby czekać na naciśnięcie/powrót z idla.

**Comment by ftpd** [comment]
Samoczynne znikanie alertów - niefajnie.

Widzę tutaj dwa usercase:
1) dostajesz alert o evencie, który mija po czasie/wykonaniu akcji (np. ogłuszenie albo wytrącenie broni) - wtedy znika po tym czasie/wykonaniu akcji*;
2) dostajesz alert o evencie, który wystąpił, ale "sam nie przejdzie", na przykład złamana broń - wtedy powinno się ręcznie dawać jakieś ACK (na przykład klikając), że user jest świadomy problemu i sobie z nim poradził/olał go.

* - przy dobywaniu alert nie powinien byc czyszczony prz komunikacie "bol w dloni staje sie mniej odczuwalny", tylko raczej przy "dobywasz" (ja mialem tak, ze przy wytraceniu bylo WYTRACENIE, przy bol staje sie mniej odczuwalny bylo DOBADZ BRONI, a czyscilo sie dopiero od "dobywasz", ale to juz jak chcesz).

**Comment by tjurczyk** [comment]
Od następnej wersji znika czasowa aktywność bindów. Znikanie alertów po kliknięciu lub z nadejściem nowego. Niektóre alerty mają bindowaną akcję po kliku (np dobywanie).
