### ISSUE TITLE
zabici2

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#220]
proponowalbym by segregowaly sie liczebnoscia  od najwiekszej liczby do najmniejszej.

jak jest dwuczlonowa nazwa wroga np. straznik wiezy ... to w zabici 2 wyswietla sie jako "wiezy"
czy zywiolak wody wyswietla na liscie tylko "wody"

**Comment by tjurczyk** [comment]
"zywiolak wody" - aby cos takiego naprawic, trzebaby miec wszystkie dwuczlonowe npce na arkadii. Takiego zestawienia nie mam. Jesli go zdobedziesz, wtedy mozna to poprawic.
