### ISSUE TITLE
kompas

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#221]
Obcialbym ten tekst do jakies krotkiej informaji

< zerkasz na kompas> / < zerka na kompas>

zamiast tego spamu co lokacje

XXX uklada grawerowany kompas na wyprostowanej dloni i przez pare chwil wstrzymuje oddech.
Nastepnie przyglada sie dokladnie urzadzeniu i bacznie sie rozglada dookola.

Ukladasz urzadzenie na wyprostowanej dloni i przez pare chwil wstrzymujesz oddech, by pozwolic
kompasowi pokazac kierunek polnocny. Uwaznie przygladasz sie ulozeniu wskazowki i na jej podstawie 
ustalasz pozostale kierunki swiata.

===

Widzisz jak szkielko grawerowanego kompasu peka, a cale urzadzenie po prostu rozpada ci sie w rekach.

To tez mozna jakos wyroznic.

**Comment by CrerZS** [comment]
Poprosze takze o dodanie jakiegos trybu z automatycznym sprawdzaniem drogi kompasem. np. pod ~, razem z trybami przemykania.

**Comment by tjurczyk** [comment]
Obcinanie mozesz sobie zrobic sam, niektorzy chca widziec cale opisy.
Wyroznienie kompasu mozna dodac choc nie wiem czy jest uniwersalne dla wszystkich kompasow. Trzeba to zebrac.

@CrerZS nie rozumiem o co chodzi. Poza tym jeden ticket = jednak rzecz.

**Comment by tjurczyk** [comment]
Brak typow kompasow, zamykam. Jesli zbierzesz, zrob nowy ticket.
