### ISSUE TITLE
ALT+ CTRL +

### ISSUE THREAD

**Issue by CrerZS** [tjurczyk/arkadia-skrypty#222]
Proponuje dodanie:
1, alt + ID gracza z druzyny w celu zasloniecia go.
2. ctrl + ID gracza z druzyny w celu wydania rozkazu obrony.

**Comment by tjurczyk** [comment]
Gracze maja litery alfabetu, wiec jesli myslisz o ctrl + 1, ... to nie jest to obecnie mozliwe.
