### ISSUE TITLE
Gagi

### ISSUE THREAD

**Issue by CrerZS** [tjurczyk/arkadia-skrypty#223]
Obecnie mamy dostepne:
-- Konfiguracja gagow
--
-- Ponizej jest opcja co ma byc robione:
-- 
-- '0' - nic, wyswietlane beda taki tekst jak przychodzi z arkadii
-- '1' - bedzie usuwana dana linia (nie bedzie w ogole informacji, ze przyszla)
-- '2' - bedzie gagowana z tagiem, np [bron] _oryginalna_linia_ 
--       (konfiguracja kolorow ponizej)

Proponuje dodac opcje 3: forma skrocona np. tylko [par] bez dalszej linii. Zapobiegnie to zamazywaniu obrazu walki

**Comment by tjurczyk** [comment]
Warte przemyslenia, choc czasochlonne. Trzeba przemyslec, czy jest to warte.
