### ISSUE TITLE
okno rozmów vs. okno do walki

### ISSUE THREAD

**Issue by pprraavv** [tjurczyk/arkadia-skrypty#224]
Na forum wspomniano, że planowane jest wydzielenie okna dla rozmów. 
Super sprawa, ale może lepiej zamiast wydzielania okna rozmów odwrócić problem i wydzielić okno walki?

Pomysł chciałem poddać pod dyskusję, bo chyba łatwiej (a w rezultacie szybciej) jest przerzucić wyświetlanie opisów walki do osobnego okna (i tak są już gagowane), niż skryptować nowe okno z rozmowami i emocjami (są raczej nierozłączne).

Jeśli chodzi o mój punkt widzenia to idea rozdzielenia walki i rozmów jest taka, aby natłok opisów ciosów i uników nie zaciemniał rozmów i opisów czynności, które podczas walki mają miejsce (prośba o zasłonienie, polecenie wycofania się, omówienie dalszych kroków,...). Więc oba pomysły są ok, ale okno walki jest (chyba) prostsze do implementacji.

**Comment by animal793** [comment]
Cokolwiek Adr wybierze prosze by to bylo opcjonalne. Ja np lubie miec wszystko w jednym oknie.

**Comment by jorhni** [comment]
Jesli mi sie dobrze wydaje, to by to pewnie robil w oparciu o GMCP, wiec samo wydzielenie komunikatow do innego okna jest takie samo w obu przypadkach (pisze w oparciu o cmuda, na ktorym to robilem). Ale zgodze sie z animal793, ze najlepszym rozwiazaniem by bylo zalaczanie opcjonalne tego. Sa rozne preferencje. Ale to i tak zdecyduje Adr ;) Ja tam czekam z utesknieniem na odrebne rozmowy.

**Comment by animal793** [comment]
pamietam ze ma cmudzie jak wydzielili walke do innego okna to zaczal sie problem z logowaniem walki.

**Comment by tjurczyk** [comment]
Zapomnialem o tym :)
Dodam w nastepnej aktualizacji, bedzie do wyboru. Mozna zrobic wydzielenie rozmow, lub walki, lub oby dwoch jesli ktos bedzie chcial.

**Comment by tjurczyk** [comment]
@pprraavv w zasadzie, jest to juz do zrobienia. Mozna sobie skonfigurowac, aby dac walke do okna. 
Wydaje mi sie jednak, ze to teraz zbedne. Jak rozumiem chcesz wydzielic walke i wyeliminowac ja z okna glownego? Na razie jest to niemozliwe. Zglosilem na forum Mudleta brak logowania innych okien niz glowne: https://github.com/Mudlet/Mudlet/issues/1507

Tymczasowo to zatem zamykam, bo w 3.9 bedzie mozna zdefiniowac, aby walka tez szla do osobnego okna.
