### ISSUE TITLE
Alias i skrypty na obserwacje grupki wrogow

### ISSUE THREAD

**Issue by chlebik** [tjurczyk/arkadia-skrypty#226]
W powergamingu czesto kiedy przeciwnicy sa w grupce robi sie szybki przeglad przeciwnikow i patrzy sie na to jaka maja bron/zbroje/itp. Mozna by zrobic alias, ktory podobnie jak '/sprzet' pokazal by co nosza na sobie przeciwnicy? 

Dla przykladu wchodze na lokacje, wpisuje '/sprzetwrog' i dostaje:

FIMIR:
bron: noz
tarcza: brak
zbroja: ciezka zlocista kolczuga

FIMIR2:
bron: naginata
tarcza: brak
zbroja: brak

Ulatwilo by to expa w malych grupach gdzie takie rzeczy jak to kogo sie bije i w jakiej kolejnosci robi roznice.

**Comment by tjurczyk** [comment]
Dobry pomysl, warty zakodowania. Jaka komenda oceni wszystkich przeciwnikow? `ocen wrogow` zadziala zawsze i wszedzie?

**Comment by tjurczyk** [comment]
Poza tym trzeba zebrac opisy, ktore pokazuja co wrogowie maja na sobie/czym walcza. Jesli to zbierzesz, mozna zrobic.

**Comment by chlebik** [comment]
A tego nie da sie wyjac z GMCP? Albo po prostu jak idzie numerowanie NPCow na lokacji to dac na kazdym 'ob obiekt_333', sparsowac 'Trzyma XXXX i XXX' oraz 'ma na sobie', split po przecinkach i tyle.

Nie wiem na ile to jest uniwersalne, a na ile nie - ja moge dostarczyc jak cos np. schemat tego na expach, na ktorych bywam dosc regularnie.

**Comment by tjurczyk** [comment]
Byc moze sie da z gmcp. 
Trzeba miec wiecej przykladow, aby to zrobic w miare uniwersalnie.

**Comment by tjurczyk** [comment]
@chlebik Jest cos takiego na chwile obecna:

<img width="336" alt="screen shot 2018-03-04 at 10 36 49 pm" src="https://user-images.githubusercontent.com/1749428/36960717-17f8a44e-1ffd-11e8-9cd0-bc3aa91889f3.png">

Bedzie w nastepnej wersji.
