### ISSUE TITLE
Kondycja takze przy zerknij

### ISSUE THREAD

**Issue by CrerZS** [tjurczyk/arkadia-skrypty#227]
Obecnie uzywajac komendy zerknij mamy cos takiego:

Wypalone Pustkowia.
-----: NE SE E S N SW W
Cialo czarnego oszalalego dzika.
Brudny szkaradny ork.
Walczysz z brudnym szkaradnym orkiem.
> Jestes ranny. Atakuje cie brudny szkaradny ork.

Czy tu nie mogloby byc kondycji graficznej jak w okienku kondycji?
Wygladalo by to czytelniej.
np. [--XXXXX] <--- brudny szkaradny ork

**Comment by tjurczyk** [comment]
Nie, gdyz kazdy preferuje tego typu kombinacje i teksty inaczej w innym stylu, w innych kolorach, w innym wymiarze itp. Od wizualnej kondycji jest okno kondycji na chwile obecna.
