### ISSUE TITLE
Wyroznienie : Wieza Zywiolakow - Wyrzucenie z lokacji

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#229]
Mozna by tutaj dac jakies wyroznienie w nawiasie by bylo widoczne jak kogos wywali z lokacji

Drzewiasty chrzeszczacy zywiolak ziemi wsciekle wymachuje poteznymi ramionami.
Jedno z nich, zakonczone omszalym glazem trafia wprost w ciebie! Bezwladnie odrywasz sie od ziemi i
wymachujac rekami przelatujesz dosc spory kawalek, by gruchnac o ziemie. Czujesz, jak wszystkie 
bebechy wywrocily sie w twoim ciele.

Drzewiasty chrzeszczacy zywiolak ziemi wsciekle wymachuje poteznymi ramionami.
Jedno z nich, zakonczone omszalym glazem trafia wprost w XXX! Widzisz, jak bezwladnie odrywa sie
od ziemi i wymachujac rekami przelatuje dosc spory kawalek, by tam gruchnac o ziemie.

**Comment by tjurczyk** [comment]
Dodane od nastepnej wersji.
