### ISSUE TITLE
Mapper Pajaki - Leze Morgenstern

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#230]
gdy przeszukujemy leze i nie znajdujemy nic w nim zapala sie Pomaranczowy kwadrat i juz nie znika i blokuje mapper

Postaram sie wylapac ten tekst lub jak ktos go ma niech wklei.

**Comment by tjurczyk** [comment]
Nie ma tekstu = ticket zamkniety. Prosze o zakladanie ticketow tylko jak masz pelne informacje. Jak zdobedziesz opis, wtedy mozna to zrobic.

**Comment by animal793** [comment]
Rozrywasz lepkie, zbite pajeczyny, przeszukujac leze. Niestety procz przezartych przez rdze resztek ekwipunku jakich nieszczesnikow nie znajdujesz tu nic interesujacego.

**Comment by tjurczyk** [comment]
Duplikat https://github.com/tjurczyk/arkadia-skrypty/issues/237
