### ISSUE TITLE
kasowanie listow i wznowienie lazika

### ISSUE THREAD

**Issue by Walkir** [tjurczyk/arkadia-skrypty#232]
```
[1-1 adefFhHmnpqrsRux.!?] (aktualny: 1) -- d
d
Zaznaczono do skasowania: 1.
q
[1-1 adefFhHmnpqrsRux.!?] (aktualny: 1) -- 
Kasuje listy...
Kasuje: 1.
```

Po takiej czynności, gdy robię to szybko, łazik nie wznawia podążania. Muszę wpisać i potwierdzić jeszcze raz 'q'.

**Comment by tjurczyk** [comment]
U mnie dziala albo zle rozumiem. Sprawdz wersje 3.6 jak wypuszcze bo sporo zmienialem. Jesli cos bedzie nie tak, zglos ponownie z jasniejszym opisem.
