### ISSUE TITLE
Sprawdzenie magikow przed zakonczeniem

### ISSUE THREAD

**Issue by chlebik** [tjurczyk/arkadia-skrypty#236]
Sytuacja, ktora sie kazdemu pewnie przydazyla. Przez przypadek w plecaku czy w rece zapodzial sie magik, dajemy 'zakoncz', pufff, nie ma magika. Moze zrobic sprawdzajke na komende 'zakoncz', przeorac ekwipunek w poszukiwaniu magikow i ew. dac komunikat?

**Comment by Walkir** [comment]
tutaj może być pomocna komenda 'przetrwaja' bo sprawdza cały ekwipunek

**Comment by tjurczyk** [comment]
Sugeruje zrobic sobie taki alias:

<img width="803" alt="screen shot 2018-10-01 at 10 57 43 pm" src="https://user-images.githubusercontent.com/1749428/46331595-7499bc80-c5cd-11e8-8164-6ce79fd910ee.png">
