### ISSUE TITLE
Mapper Pajaki - Leze Morgenstern

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#237]
gdy przeszukujemy leze i nie znajdujemy nic w nim zapala sie Pomaranczowy kwadrat i juz nie znika i blokuje mapper

Rozrywasz lepkie, zbite pajeczyny, przeszukujac leze. Niestety procz przezartych przez rdze resztek ekwipunku jakich nieszczesnikow nie znajdujesz tu nic interesujacego.

**Comment by tjurczyk** [comment]
A jesli cos znajdujemy to czy znika? Jesli nie, potrzebny jest tez pattern do tej sytuacji. Chyba, ze jesli cos znajdujemy to wylapuje.
