### ISSUE TITLE
Brakujący bloker

### ISSUE THREAD

**Issue by jorhni** [tjurczyk/arkadia-skrypty#239]
Brak:
Musisz najpierw zejsc z podestu

**Comment by tjurczyk** [comment]
Kiedy to wystepuje?

**Comment by jorhni** [comment]
Lokacja 22497 (Obserwatorium astronomiczne). Jest możliwość wejścia na podest, ale mapper nie blokuje ruchu, mimo, że na tym podeście jesteśmy i nie zeszliśmy z niego.

**Comment by tjurczyk** [comment]
Dodane od 3.7.
