### ISSUE TITLE
Wykonanie rozkazu

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#24]
[ ROZKAZ DEF ] XXXX wydaje ci rozkaz zasloniecia jego samego.

[ N ZASLANIA ] Na rozkaz XXX  YYYY probuje zaslonic go przed ciosami dynamicznego pancernego 
golema, jednak nie jest w stanie tego uczynic.
**Na rozkaz XXXX zaslaniasz go przed ciosami naoliwionego pancernego golema.**

**DO WYROZNIENIA TEKST:**
Na rozkaz XXX zaslaniasz go przed ciosami naoliwionego pancernego golema.

**Comment by ssnakey** [comment]
ludzie takie wyroznienia to sami sobie mozecie zrobic bez przesady... jeden lubi miec rozowe drugi lubi miec inny kolor.

**Comment by animal793** [comment]
ssnakey po pierwsze to nie dla ciebie to wklejam.
Wiec nic mnie nie obchodzi, twoja opinia na ten temat.

Nie ty tez bedziesz decydowac co bedzie dodane do skryptow a co nie.

**Comment by tjurczyk** [comment]
Dodane powyżej 2.15.
