### ISSUE TITLE
Dodawanie skrotow z cyfra w tytule

### ISSUE THREAD

**Issue by chlebik** [tjurczyk/arkadia-skrypty#241]
Przy probie utworzenia skrotu w mapperze zawierajacego w nazwie cyfre skrypty sie wysypuja - w sensie dostaje 'Slucham?' od arki. 

> /dodaj_skrot 15081 lokacja2 jakis tam opis

Nie wiem czy to zamierzona sytuacja.

**Comment by tjurczyk** [comment]
Od 3.7 poprawione.
