### ISSUE TITLE
Mapper zgubiony u Xaviera

### ISSUE THREAD

**Issue by chlebik** [tjurczyk/arkadia-skrypty#244]
(mapper): mapper zgubiony, przeslij dzordzykowi: last curr.id: 6226, spe: `east`

(mapper): mapper zgubiony, przeslij dzordzykowi: last curr.id: 6226, spe: `XXXX na wschod`

Mozliwe, ze trzeba pokonac Xaviera by tam wejsc.

**Comment by tjurczyk** [comment]
Ta lokacja nie wydaje sie byc poprawna. Na niej nie ma wyjscia na wschod.
