### ISSUE TITLE
Najnowszy Update: Problem z Mapperem

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#246]
Odpalajac mudleta Mapa jest jakby schowana i nie zapamietuje ustawienia okien.
Kiedys wrzucalismy w konsole jednorazowo

lua saveWindowLayout()

i problem znikal.

Teraz za kazdym razem musimy odpalac mape z paska na gorze by ja wlaczyc.

**Comment by tjurczyk** [comment]
Na chwile obecna tak trzeba bedzie zrobic, automatyczne otwieranie mapy ma zniknac z API mudleta, wiec go juz usunalem. Trzeba po wlaczeniu mudleta klikac na gorze ikone mapy.
Jesli zrobia API do otwierania mapy, to zostanie to dodane.
