### ISSUE TITLE
Najnowszy update: Problem z Mapperem #2

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#247]
Po wczytaniu mapy wszystkie tereny expowiska trakty byly w kolorze bialym.
( Windows 7 Mudlet 3.4 )
Jednak wystarczy na dole mappera ( kolo Rooms mamy EXITS z wartoscia 10 )tam kliknac i zmienic wartosc  nie wazne na jaka wystarczy ruszyc i mapper jakby sie odblokowywal i wracal do normy kolorystycznej.

Oczywiscie to sie nie zapisuje i za kazdym razem trzeba to powtarzac.

**Comment by tjurczyk** [comment]
To dalej wystepuje? Na Macbooku tego nie ma.

**Comment by animal793** [comment]
Po zrobieniu aktualizacji.. tak ten problem nie zniknal.

**Comment by tjurczyk** [comment]
Nie jestem w stanie tego zreplikowac. Moze to byc problem z Mudletem na Windowsa. Polecam zainstalowac 3.7.1 i sprawdzic.
