### ISSUE TITLE
Dodatkowa informacja w /licz_poziom

### ISSUE THREAD

**Issue by ctarx** [tjurczyk/arkadia-skrypty#248]
Proponuję dodać linijkę informującą o sumie wszystkich podcech.
Czyli przykładowo:
`(skrypty): Twoj aktualny poziom to ktos kto zwiedzil caly swiat (159) i brakuje ci do nastepnego 7 podcech (ktos wielce 
doswiadczony)`

**Comment by tjurczyk** [comment]
Dodane od 3.7.
