### ISSUE TITLE
tasak

### ISSUE THREAD

**Issue by Walkir** [tjurczyk/arkadia-skrypty#252]
Część z tego ma podświetlenie ale nie wszystko:

```
Powolne, pozbawione sily ruchy wroga zagrzewaja cie do walki, dodajac zapalu.
Z kazdym kolejnym ciosem nabierasz nowej sily do walki.
Kazdy kolejny charczacy oddech opadajacego z sil przeciwnika tylko daje ci nowy zapal do walki.
Widok slabnacego wroga tylko dodaje ci sil.
```

**Comment by tjurczyk** [comment]
`Kazdy kolejny charczacy oddech opadajacego z sil przeciwnika tylko daje ci nowy zapal do walki.` sie podswietla, bo `daje ci` sa podswietlane w przypadku jak ktos cos podaje.
Jak i dlaczego te teksty mialyby byc podswietlane?

**Comment by Walkir** [comment]
to sa "spece" tasaka, mozna podswietlic ale nie trzeba w sumie, jak cos to sam sobie to dodam ;)

**Comment by tjurczyk** [comment]
A co one robia?

**Comment by tjurczyk** [comment]
@Walkir Mozesz powiedziec co one robia? Jak je oznaczyc?

**Comment by jsenny** [comment]
Zwiększają zmęczenie u atakowanego przy każdym wyświetleniu w/w komunikatu.

**Comment by tjurczyk** [comment]
Dodane w 3.11.
