### ISSUE TITLE
Poprawki w GPS - dylizans Wyzima Oxenfurt

### ISSUE THREAD

**Issue by jorhni** [tjurczyk/arkadia-skrypty#259]
Już jakiś czas temu zostały zmienione komunikaty przy dyliżansie na tej trasie, te powinny załatwić sprawę:

> Postoj - wies na podgrodziu Oxenfurtu
> Postoj - rozdroza niedaleko Piany
> Postoj - plac w centrum Bialego Mostu
> Postoj - wies Anchor
> Postoj - pod Wyzima

**Comment by tjurczyk** [comment]
Od 3.7 poprawione.
