### ISSUE TITLE
Wycofka Legiona - lampa - pare pierdolek

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#26]
Tekst do wyroznienia:

**XXX unosi swoja wzmacniana drewniana tarcze i szybko przesuwa sie za ciebie, kryjac sie przed 
atakami brudnego kamiennego trolla.**

dac np 
[ WYCOFKA ZA CIEBIE] przed tekstem.

====
Ponizej daje jeszcze te ktore mozna by jakos zaznaczyc.Do rozwazenia.

XXX przestaje zaslaniac XXX.
XXX wychodzi zza twojej zaslony.
XXX przestaje cie zaslaniac przed ciosami wrogow.

=======
Lampa

bind ctrl+4: napelnij lampe olejem

ten komet wyskakuje co minute.
Lampa pali sie 5 min nim zgasnie

Mozna by dac by wyswietlala Solidna oddzielona widoczna komende  czwartej minucie. potem 30 sekund poznije i tyle.

by dopelnic i nie spamowac nam co minute "napelnij lampe"

Ten spam jest irytujacy bo czlowiek dopelnia lampe co minute odrucho gdy widzi bind wyskakujacy.

**Comment by tjurczyk** [comment]
Wycofanie dodane, w lampie nie ma sensu zbędnego kombinowania. Zmieniam jedynie komunikat na co 75 sekund.
