### ISSUE TITLE
Problem z mapperem

### ISSUE THREAD

**Issue by DarkTriss** [tjurczyk/arkadia-skrypty#261]
Tak jak pisałam - mapper się gubi jeśli podążamy za kimś w normalnym kierunku, a opis przejścia jest inny niż standardowy. Na razie znalazłam tyle, ale pewnie takich miejsc jest więcej. Przy czym cześć tych lokacji jest dodana przeze mnie...
Imiona wyiksowane, bo nie wiem czy by sobie zainteresowanie życzyli ;)

(mapper): mapper zgubiony, przeslij dzordzykowi: last curr.id: 22753, spe: `X przez 
przeszklone drzwi do srodka dworku`
(mapper): mapper zgubiony, przeslij dzordzykowi: last curr.id: 542, spe: `X do wyjscia`
(mapper): mapper zgubiony, przeslij dzordzykowi: last curr.id: 539, spe: `X do wnetrza dworu`
(mapper): mapper zgubiony, przeslij dzordzykowi: last curr.id: 544, spe: `X przez przeszklone 
drzwi do ogrodu`
(mapper): mapper zgubiony, przeslij dzordzykowi: last curr.id: 61, spe: `down`
(mapper): mapper zgubiony, przeslij dzordzykowi: last curr.id: 542, spe: `X przez drzwiczki 
za kontuar`
(mapper): mapper zgubiony, przeslij dzordzykowi: last curr.id: 543, spe: `X przez drzwiczki 
na korytarz`
(mapper): mapper zgubiony, przeslij dzordzykowi: last curr.id: 11686, spe: `X w strone innych kramow`
(mapper): mapper zgubiony, przeslij dzordzykowi: last curr.id: 4552, spe: `X na most`
(mapper): mapper zgubiony, przeslij dzordzykowi: last curr.id: 4297, spe: `X sciezka w 
kierunku ruin`
(mapper): mapper zgubiony, przeslij dzordzykowi: last curr.id: 64, spe: `X na balkon, przechodzac 
przez lewa czesc okna`
(mapper): mapper zgubiony, przeslij dzordzykowi: last curr.id: 9852, spe: `X na zachod, 
zanurzajac sie w ciemnosc skalnego pekniecia`
(mapper): mapper zgubiony, przeslij dzordzykowi: last curr.id: 1426, spe: `X droga w dol`

**Comment by tjurczyk** [comment]
Dzieki. Rewelacyjna robota. Dodaje i mapke wypuszcze niebawem.

**Comment by Walkir** [comment]
```

(mapper): mapper zgubiony, przeslij dzordzykowi: last curr.id: 6461, spe: `XXX przez brame na polnocy`

(mapper): mapper zgubiony, przeslij dzordzykowi: last curr.id: 6465, spe: `XXX przez brame na poludniu`

(mapper): mapper zgubiony, przeslij dzordzykowi: last curr.id: 6527, spe: `XXX na rynek`

(mapper): mapper zgubiony, przeslij dzordzykowi: last curr.id: 6430, spe: `XXX do zajazdu`

(mapper): mapper zgubiony, przeslij dzordzykowi: last curr.id: 24335, spe: `XXX przez brame na polnocy`

(mapper): mapper zgubiony, przeslij dzordzykowi: last curr.id: 6489, spe: `XXX do wyjscia na poludniu`

[2] Podazasz za XXX po drewnianej drabince na gore.
(mapper): mapper zgubiony, przeslij dzordzykowi: last curr.id: 6491, spe: `up`
```

**Comment by tjurczyk** [comment]
@Walkir Kazde takie zgloszenie = osobny issue.
Praktycznie wszystkie te zgloszenia (za wyjatkiem dwoch ostatnich) nie zawieraja docelowej lokacji, do ktorej mapper powinien sie przemiescic. Bez tego nie jestem w stanie nic zrobic.
