### ISSUE TITLE
Stojaki, kosze etc

### ISSUE THREAD

**Issue by DarkTriss** [tjurczyk/arkadia-skrypty#262]
Na stan obecny skrypty robią listę tylko z zawartosci skrzyń. Przydałyby się rownież stojaki, kosze, koszyki, szafy i inne ;)

**Comment by animal793** [comment]
musisz wkleic ich opisy pelne bo kazdy z nich czesto jest unikatowy

**Comment by tjurczyk** [comment]
Potrzebne sa opisy brakujacych przedmiotow. Czyli cale `ob cos`, i wkleic.

**Comment by jorhni** [comment]
Otwarty pekaty gnomi sejf zawiera xxx

**Comment by tjurczyk** [comment]
@jorhni to sa dokladne itemy na Arkadii? `sejf`, `sekretarzyk`? Nie sadze :)
Przeslij prosze dokladne opisy.

**Comment by jorhni** [comment]
Moze Cie zaskocze, ale odnosnie tych dwoch:
`Otwarty pekaty gnomi sejf zawiera dwa masywne matowe berdysze, dwa filcowe kapelusze z `
`Debowy wysoki sekretarzyk zawiera zdobiona oprawna ksiege, trzy srebrnoniebieskie`
Temat juz troche temu wywolany. Ogolnie dzieki znajomym zebralo sie takich pojemnikow wiecej, tyle, ze sa to pojemniki, ktore nie sa ogolnodostepne (pojemniki gildiowe etc). 
Juz jakis czas temu pomyslalem, ze moze lepszym rozwiazaniem bedzie dopisanie sobie ich "recznie" przez te parenascie osob, w zaleznosci, co im potrzeba.

**Comment by DarkTriss** [comment]
otwarty wytrzymaly wiklinowy koszyk
otwarty duzy wiklinowy koszyk
otwarta debowa zdobiona skrzynia
otwarta obszerna szafa

Tyle znalazłam na razie takich co nie dzialaja

**Comment by jorhni** [comment]
Ogólnodostępne
`Otwarty marynarski plocienny worek zawiera zamkniety zamszowy woreczek, dwie butelki oleju,
poczerniona krasnoludzka tarcze i grawerowany kompas.`

**Comment by tjurczyk** [comment]
Dodane w 3.11.
