### ISSUE TITLE
szybkie pisanie listu blokuje mappera

### ISSUE THREAD

**Issue by Walkir** [tjurczyk/arkadia-skrypty#267]
Czasami cały list wpisuje w jednej linii i poszczególne komendy rozdzielam ; Wcześniej takie pisanie nie blokowało mappera, teraz muszę jeszcze raz dać 'q' żeby odblokować śledzenie mapy.

np:

`> napisz list;dzordzyk;skrypty; ;Jak tak napisze list to sie mapper zablokuje;**`

**Comment by ftpd** [comment]
U mnie czasami przy normalnym pisaniu też się tak dzieje.

**Comment by tjurczyk** [comment]
@ftpd logi w kazdym wystapieniu, bo czasami umkna mi jakies patterny, ktore powinny odblokowywac.
@Walkir to co zglosiles tutaj poprawione w 3.8.
