### ISSUE TITLE
Gryf mahakamski - kilka poprawek.

### ISSUE THREAD

**Issue by ftpd** [tjurczyk/arkadia-skrypty#27]
1) nowy tekst do stuna i wytrącenia:
"Nie mogac zniesc natezenia tego dzwieku, przerywasz walke i opuszczasz bronie zaslaniajac uszy."
tutaj w sumie po zejściu ogłuszenia przydałby się bind na 'dobadz wszystkich broni'

2) bloker mappera:
"Probujesz przecisnac sie przez otwor na dach, ale ze wzgledu na brak miejsca, zmuszony jestes wrocic na dol."

3) teleport pod wiatrak:
"Bez wiekszego problemu potwor zrzuca cie z platformy!"

**Comment by tjurczyk** [comment]
Wszystko dodane, będzie po 2.15.
