### ISSUE TITLE
Zaslona straznika

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#271]
Do Uzupelnienia:

XXXX staje u twego boku, gotow w kazdej chwili zaslonic cie przed nadchodzacym niebezpieczenstwem.

XXX z wprawa staje pomiedzy XXXX a nerwowym plamiastym hobgoblinem i brutalnym zoltoskorym
hobgoblinem, przyjmujac na siebie nadchodzace ciosy.

**Comment by tjurczyk** [comment]
Dodane w 3.8.
