### ISSUE TITLE
pomaranczowy kwadrat

### ISSUE THREAD

**Issue by jorhni** [tjurczyk/arkadia-skrypty#273]
Po zakonczeniu przeszukania (bez wzgledu na wynik) nie zdejmuje blokady:
`przeszukaj otwor`
`Zaczynasz przeszukiwac otwor.`
`Przeszukujesz otwor za drzwiczkami sciennego zegara i znajdujesz maly, blyszczacy przedmiot.`

`przeszukaj otwor`
`Zaczynasz przeszukiwac otwor.`
`Nie znajdujesz nic w otworze sciennego zegara.`

**Comment by tjurczyk** [comment]
Dodane od 3.8.
