### ISSUE TITLE
Spece Barba

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#274]
Po ostatniej aktualizacji wylapuje kogos spece z zawodem barba tez jako moje

[BAR OGL] [BAR 1/6] [JA OGL] [JA 1/6] Nie przebierajac w srodkach XXX z calej sily wali
jaskiniowego kamiennego trolla na odlew srebrzystym kanciastym mlotem bojowym, obijajac mu przy tym 
tulow. Nieprzyjemne chrzakniecie i metny wzrok przeciwnika swiadcza, ze dobrze wymierzony cios 
musial trafic w jakies wrazliwe miejsce.

[BAR OGL] [BAR 2/6] [JA OGL] [JA 2/6] Nie przebierajac w srodkach XXX z calej sily wali
jednookiego kamiennego trolla na odlew srebrzystym kanciastym mlotem bojowym, tlukac mu przy tym 
tulow. Nieprzyjemne chrzakniecie i metny wzrok przeciwnika swiadcza, ze dobrze wymierzony cios 
musial trafic w jakies wrazliwe miejsce.

**Comment by tjurczyk** [comment]
Poprawione w 3.8.
