### ISSUE TITLE
Parowanie Lewak

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#276]
Takze tych opisow nie wylapuje, do uzupelnienia.

Szlachetna stal dzierzonego przez XXX zdobionego dlugiego lewaka spiewa dzwiecznie, gdy udaje mu
sie sparowac cios postawnego zawzietego mezczyzny.

XXX wprawnie przyjmuje cios postawnego sniadego hobgoblina na szeroki jelec swojego zdobionego
dlugiego lewaka.

XXX sklada wprawnie zastawe by sparowac cios postawnego zawzietego mezczyzny swym zdobionym dlugim
lewakiem.

Szybkim pchnieciem zdobionego dlugiego lewaka XXXX zbija na bok niespodziewany cios postawnego
sniadego hobgoblina.

**Comment by tjurczyk** [comment]
Dodane od 3.8.
