### ISSUE TITLE
Parowanie + Spec Partyzana (Straznik)

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#278]
Kolejne braki wylapane:

XXX wykorzystujac brak broni u przeciwnika, z wyuczona wprawa wyprowadza cios adamantytowa
szpiczasta partyzana mierzac w krostowatego bladoskorego mezczyzne. Wypracowane uderzenie zostaje 
jednak sparowane przez niego drewniana poreczna tarcza.

Szybkim pchnieciem adamantytowej szpiczastej partyzany XXX zbija na bok niespodziewany cios
nerwowego plamiastego hobgoblina.

**Comment by tjurczyk** [comment]
Dodane od 3.8.
