### ISSUE TITLE
Ciosy ZT do uzupelnienia

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#279]
ledwie musnac
ledwo muskajac
ledwo muskasz
ledwo muska
ledwie musnac
lekko rani
lekko ranisz
lekko go raniac
Ranisz
rani
raniac
raniac dotkliwie
powaznie go rani
powaznie go raniac
powaznie rani
powaznie go raniac
masakrujesz

Dobijajace ciosy:

Zwijasz sie w naglym uniku, po czym wyprowadzasz uderzenie gigantycznym granitowym mlotem z
szerokiego zamachu. Idealnie wymierzony cios trafia krostowatego bladoskorego mezczyzne w lewe ramie,
masakrujac staw barkowy - jego reka opada bezwladnie. Nie zwlekajac ani chwili, wykorzystujesz 
okazje i posylasz diabelnie silne uderzenie prosto w klatke piersiowa przeciwnika, gruchoczac zebra 
i miazdzac pluca. Czlowiek rzezac osuwa sie na ziemie u twych stop.

Przesuwasz rece na trzonku swej broni, po czym uderzasz gigantycznym granitowym mlotem, wkladajac w
to cala swa sile. Cios dosiega jasnowlosego mlodego mezczyzny, z glosnym chrupnieciem miazdzac 
klatke piersiowa. Czlowiek gwaltownie osuwa sie na ziemie.

Dlugim susem przeskakujesz w bok, zachodzac przeciwnika z flanki, po czym uderzasz gigantycznym
granitowym mlotem, wykorzystujac przechyl swego ciala. Cios dosiega postawnego zawzietego mezczyzny 
prosto w glowe, z chrupnieciem trafiajac w czaszke i miazdzac caly bok glowy. Czlowiek gwaltownie 
osuwa sie na ziemie.

Robisz szybki wypad do przodu, skracajac dystans do przeciwnika, po czym blyskawicznie uderzasz
gigantycznym granitowym mlotem. Twoj cios precyzyjnie trafia brutalnego wytatuowanego hobgoblina tuz 
miedzy obojczyk a szyje, w miekka tkanke, w mgnieniu oka prawie oddzielajac glowe od tulowia. 
Hobgoblin momentalnie pada martwy u twych stop.

Parowanie:

Gargantuiczny plomiennooki smoczy ogr dosc nieporadnym ciosem ceremonialnego dwurecznego multona
probuje cie ogluszyc. Nie dajesz sie jednak zaskoczyc swojemu przeciwnikowi, w pore sie oslaniajac 
gigantycznym granitowym mlotem.

Robisz krotki wypad do przodu, skracajac dystans do przeciwnika, i szybko przyklekasz na jedno
kolano, po czym wyprowadzasz gigantycznym granitowym mlotem gwaltowne uderzenie, jednak 
gargantuiczny plomiennooki smoczy ogr sprawnie unika twego ciosu.

**Comment by tjurczyk** [comment]
```
ledwie musnac
lekko go raniac
Ranisz
raniac dotkliwie
powaznie go rani
powaznie go raniac
masakrujesz
```

co to jest?

**Comment by animal793** [comment]
wylapalem z gestych opisow ciosow poziomy obrazen.
np 
1/6 ciosy maja sprecyzowane opisy obrazen w gaszczy calego opisu ciosu.
ledwie musnac
ledwo muskajac
ledwo muskasz
ledwo muska
ledwie musnac

np mlotowi udalo sie ledwie musnac
mlot ledwo muskajac uderza
ledwo muskasz gobila
udaje ci sie ledwie musnac mlotem...

**Comment by tjurczyk** [comment]
Trzeba raczej zebrac pelne i kompletne opisy i je uporzadkowac poziomami ([3/5], [4/5] itp)
Watpie jednak, bym zajal sie tym w najblizszym czasie. W kolejce jest sporo innej pracy, jeszcze sprzed miesiecy.
