### ISSUE TITLE
Spece korsa

### ISSUE THREAD

**Issue by Noisehammer** [tjurczyk/arkadia-skrypty#281]
Spece korsa widziane z trzeciej osoby nie są gagowane:

X oszczednym wypadem do przodu ATAKUJE zwinna biala wietrzyce, dzgajac ja swym jasniejacym zdobionym jataganem, a uderzenie to pozostawia gleboka
rane w ciele jego przeciwnika.

X blyskawicznym wypadem do przodu ATAKUJE masywna biala wietrzyce, a jego jasniejacy zdobiony jatagan, dzierzony w wyciagnietej rece, trafia w jej
cialo przebijajac je na wylot. Gwaltownie wyszarpniety orez z glosnym mlasnieciem wychodzi z ciala ciagnac za soba krwawy warkocz smierci.

X plynnym wypadem do przodu ATAKUJE dzika jasna wietrzyce i napierajac calym cialem dzga ja swym jasniejacym zdobionym jataganem, ktory przechodzi
prawie na wylot przez jej cialo, powodujac ogromne obrazenia.

**Comment by tjurczyk** [comment]
Dodane od 3.8.
