### ISSUE TITLE
Zdobiony Jasniejacy Mlot Ciosy

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#282]
**Jesli ktos jeszcze cos wylapal dodawajcie:**

Niecelny cios zdobionego jasniejacego mlota bojowego XXX przeszywa powietrze tuz przed nosem
krostowatego bladoskorego mezczyzny!

W momencie kiedy pelen sily cios zdobionego jasniejacego mlota bojowego XXX uderza w krostowatego
bladoskorego mezczyzne, obuch rozblyskuje plomieniem oslepiajacego swiatla, dotkliwie parzac glowe 
jego przeciwnika.

W momencie kiedy pelen sily cios zdobionego jasniejacego mlota bojowego XXX uderza w jaskiniowego
kamiennego trolla, obuch rozblyskuje plomieniem oslepiajacego swiatla, dotkliwie parzac leb jego 
przeciwnika.

XXX dosiega krostowatego bladoskorego mezczyzne silnym ciosem zdobionego jasniejacego mlota
bojowego, kaleczac mu glowe jego jarzacym sie jasnym swiatlem obuchem.

Oczy XXXX rozblyskuja blaskiem dzierzonej przezen broni, gdy poteznym ciosem rozswietlonego obucha
zdobionego jasniejacego mlota bojowego wstrzasa cialem swego przeciwnika, potwornie go raniac.

trafiajac cie w korpus.
Szybkim pchnieciem zdobionego jasniejacego mlota bojowego XXX zbija na bok niespodziewany cios
postawnego sniadego hobgoblina.

XXX niczym szarzujacy tytan zniszczenia konczy wiazaca go z postawnym sniadym hobgoblinem walke
przerazajacym ciosem zdobionego jasniejacego mlota bojowego, krwawo rozstrzaskujac korpus swojego 
przeciwnika, definitywnie konczac starcie. Pulsujacy nieziemskim blaskiem obuch dzierzonego przez 
zwyciezce oreza wydaje sie nieco uspokajac, mimo tego swiatlo nie zanika, jak gdyby mlot nie mogl 
juz doczekac sie kolejnego wyzwania...
Pulsujaca glowica zdobionego jasniejacego mlota bojowego XXXX rozblyska nagle luna bladego,
zlocistego swiatla!
Gdzies w oddali spostrzegasz rozblysk nieziemskiego, zlocistego swiatla!

**Comment by tjurczyk** [comment]
Brakuje znacznikow, tj: [?/?].

**Comment by tjurczyk** [comment]
Brak znacznikow, zamykam.
