### ISSUE TITLE
Kruczoczarny miecz ciosy

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#283]
**Jesli ktos jeszcze cos wylapal dodawajcie:**

XXXX zwraca ostrze kruczoczarnego misternego miecza w kierunku poteznego zielonkawego trolla.
Krotkim wymachem trafia go w leb rozcinajac skore i pozostawijac niewielka rane, z ktorej wyplywa 
waska struzka krwi.

XXX unosi kruczoczarny misterny miecz lekko do gory i wykonuje efektowne ciecie. Krawedz
opadajacego z duza predkoscia ostrza trafia w nogi poteznego zielonkawego trolla pozostawiajac tam 
paskudna, gleboka rane, z ktorej niemal natychmiast zaczyna sie saczyc ciemna, gesta krew.

XXX wykonuje obszerny zamach wyprostowana w lokciu reka. Sprawnie manewrujac nadgarstkiem mija
obrone ogromnego czerwonookiego trolla i trafia go w tulow. Twarz jego przeciwnika wykrzywia grymas 
bolu gdy rozpedzone, niczym nie zatrzymane ostrze kruczoczarnego misternego miecza zaglebiajac sie w 
jego cialo tnie napotkane na swej drodze tkanki.

XXXX blyskawicznie opuszcza i cofa do tylu reke dzierzaca kruczoczarny misterny miecz i w dogodnej
chwili zaczyna kreslic bronia niewielki luk prowadzac ja w kierunku ciezkiego zielonkawego trolla. 
Rozpedzone ostrze dosiega jego przeciwnika i rozcinajac od dolu cialo ciezkiego zielonkawego trolla 
pozostawia za soba tryskajaca krwia fontanne.

XXXX wykonuje zamaszyste ciecie niemal w calosci zaglebiajac glownie swego kruczoczarnego
misternego miecza w ciele ciezkiego zielonkawego trolla, ktory nie mogac dluzej utrzymac sie na 
nogach bezwladnie osuwa sie na ziemie. XXXX przykleka nad przeciwniekiem, z ktorego ust, przy 
kazdym oddechu wydobywa sie glosne charczenie, unosi skierowany ostrzem w dol miecz i w chwili, gdy 
z impetem przeszywa cialo wroga przybijajac je do podloza klejnoty na rekojesci miecza rozblyskuja 
oslepiajacym, czerwonym swiatlem.

XXXX unosi kruczoczarny misterny miecz wysoko do gory skad wyprowadza blyskawiczne ciecie.
Przecyzyjnie wymierzony cios uderza w nogi poteznego szarawego trolla pozostawiajac rane, w ktorej 
zaglebia sie krawedz lsniacego ostrza. Struga krwi rozlewa sie po ciele poteznego szarawego trolla, 
ktory z widocznym wysilkiem utrzymuje sie na nogach.

XXXX wykonuje obszerny zamach wyprostowana w lokciu reka. Sprawnie manewrujac nadgarstkiem mija
obrone poteznego czerwonookiego trolla i trafia go w nogi. Twarz jego przeciwnika wykrzywia grymas 
bolu gdy rozpedzone, niczym nie zatrzymane ostrze kruczoczarnego misternego miecza zaglebiajac sie w 
jego cialo tnie napotkane na swej drodze tkanki.

**Comment by tjurczyk** [comment]
Brakuje znacznikow, tj: [?/?].

**Comment by tjurczyk** [comment]
Brak znacznikow, zamykam.
