### ISSUE TITLE
Zgubiony mapper

### ISSUE THREAD

**Issue by Stokrotka2** [tjurczyk/arkadia-skrypty#284]
(mapper): mapper zgubiony, przeslij dzordzykowi: last curr.id: 24205, spe: `XXX na zewnatrz`

powinien się przemieścić do 15520

Ustawiłem lokację na właściwą, ale po wejściu do innej chatki czy namiotu znowu się zgubił przy wychodzeniu:

(mapper): mapper zgubiony, przeslij dzordzykowi: last curr.id: 24196, spe: `XXX na zewnatrz`
do 15522

**Comment by DarkTriss** [comment]
To ja się podepnę, skoro miałam w końcu czas:
(mapper): mapper zgubiony, przeslij dzordzykowi: last curr.id: 542, spe: `X do wyjscia` -  powinno wykonac "wyjscie" do 541
(mapper): mapper zgubiony, przeslij dzordzykowi: last curr.id: 539, spe: `X do wnetrza dworu` powinno pojsc na n do 542
(mapper): mapper zgubiony, przeslij dzordzykowi: last curr.id: 544, spe: `X przez przeszklone drzwi do ogrodu` - powinien pójść na n do 22753 (lokacja chyba dodana przeze mnie)
(mapper): mapper zgubiony, przeslij dzordzykowi: last curr.id: 22753, spe: `X przez przeszklone drzwi do srodka dworku` powinno pojść na s do 544
(mapper): mapper zgubiony, przeslij dzordzykowi: last curr.id: 542, spe: `X przez drzwiczki za kontuar` - powinien pójść na w do 543
(mapper): mapper zgubiony, przeslij dzordzykowi: last curr.id: 542, spe: `X przez drzwiczki na korytarz` - powinien pójść na e do 542
(mapper): mapper zgubiony, przeslij dzordzykowi: last curr.id: 11686, spe: `w strone innych kramow` - powinien wykonać "targ" do 4481 (to jest stragan w Gelibolu, przypuszczalnie błąd dotyczy ich wszystkich)
(mapper): mapper zgubiony, przeslij dzordzykowi: last curr.id: 64, spe: `X na balkon, przechodzac 
przez lewa czesc okna` - powinien pójść na n do 66 (obie lokacje dodane przeze mnie)
(mapper): mapper zgubiony, przeslij dzordzykowi: last curr.id: 66, spe: ` X przez oszklone drzwi do wnetrza dworku. - powinien pójść na s do 64 (obie lokacje dodane przeze mnie)
