### ISSUE TITLE
Brakujacy Bloker mappera

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#286]
Na drodze staje ci wyszczerzony gnijacy szkielet.

Mimo Bloka kropka na mapie przesuwa sie

**Comment by tjurczyk** [comment]
Czy to nie jest pewnie miejsce w Tilei, gdzie szkielety blokuja? Jesli tak, czy wystapi tylko jeden taki komunikat? Bo jesli wystapi ich kilka (tyle, ile szkieletow jest na lokacji) to jest to ciezsze do zrobienia.
Czy jak wbije sie nieistniejacy kierunek to pojawi sie ten sam komunikat, czy pojawi sie `Nie widzisz wyjscia na ...`?
