### ISSUE TITLE
Lasek hobgoblinow Mapper 

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#289]
gdy pojdziemy w kierunku ktorego nie ma.

wyswietla sie taki kominukat

Ruszasz razno na poludniowy-zachod, lecz po kilku krokach grzezniesz w krzakach.
Ruszasz razno na polnoc, lecz po kilku krokach grzezniesz w krzakach.
i tak dalej...

mozna by go dodac by nie pozwalal kropce wtedy sie przesunac.

**Comment by tjurczyk** [comment]
Czy jesli jestesmy na lokacji, na ktorej nie ma wyjscia na zachod, a klikniemy zachod. Czy pojawi sie wtedy taki sam komunikat, czy pojawi sie standardowe "Nie ma wyjscia na zachod"?
