### ISSUE TITLE
Ogolnie o bindach i keyach :)

### ISSUE THREAD

**Issue by ssnakey** [tjurczyk/arkadia-skrypty#29]
Witam,
Kazdy z nas napewno jest przyzwyczajony do innych KEYsow, ja akurat jestem przyzwyczajony do zeby
jednym klawiszem napic sie na lokacji gdzie trzeba, tym samym klawiszem otworzyc brame, czy podazyc za prowadzacym druzyne, czy wejsc na statek,  inni natomiast maja inne przyzwyczajenia i w zaden sposob tego nie neguje, jednak po kazdej aktualizacji musze zmieniac te KEY'e od poczatku, nie dalo by sie tego jakos wywalic poza aktualizacje np do pliku postac.txt? W tym kliencie jest jeszcze bardzo malo klawiszy  wykorzystanych i bardzo dobrze ze wszystko jest w sumie na aliasach bo bardzo latwo potworzyc wlasne macra wg potrzeb i przyzwyczajen.

**Comment by baranno** [comment]
Mudlet nie pozwala tworzyć binda z poziomu skryptu i tu jest pies pogrzebany. Teoretycznie można zmapować wszystkie klawisze i przypisać do nich zmienne. ALE niestety miałem sytuacje kiedy na danym kompie trzeba było przypisać klawisz na nowo, bo nie działał.

**Comment by ftpd** [comment]
A czemu 'musisz je zmieniać'? Ja sobie po prostu swoje rzeczy dodałem i trzymam je na liście niżej niż skrypty główne. Tak samo z redefami tego, co chciałbym mieć inaczej - w zakładce 'Scripts' mam swój kawałek kodu wyłączający powodujące konflikty aliasy/triggery/bindy (robi się to tak: https://i.imgur.com/SEA5YqQ.png) plus dodałem swoje zamienniki i działa jak złoto.
