### ISSUE TITLE
Feluka Novi-Blavi-Daevon

### ISSUE THREAD

**Issue by Stokrotka2** [tjurczyk/arkadia-skrypty#290]
GPS nie działa ani przy porcie, ani po zejściu ze statku.

**Comment by animal793** [comment]
Prom z piany tez.

**Comment by tjurczyk** [comment]
@Stokrotka2 @animal793 poproszę o logi.

**Comment by tjurczyk** [comment]
Zamykam, bo nie otrzymalem logow.
