### ISSUE TITLE
Braki w specu barbarzyńcy.

### ISSUE THREAD

**Issue by ctarx** [tjurczyk/arkadia-skrypty#292]
Brakuje speca [0/6] z opisem:

`Nie tracac czasu na zbedne manewry probujesz walnac dlugorogiego trupiobladego zwierzoczleka na odlew ciezka kamienna maczuga
, jednak przeciwnik w pore wykonuje unik, uciekajac poza zasieg broni.`

**Comment by animal793** [comment]
dorzuce Finisher barba

Wykonujesz potezny zamach czernionym porecznym mlotem rycerskim i wkladajac w cios cala swa sile,
uderzasz na odlew koscistego ponurego orka. Twa bron ze zlowrogim jekiem rozrywanego powietrza 
tlucze jego cialo otwierajac gleboka, tryskajaca krwia rane. Przeciwnik probuje jeszcze ustac, 
walczac o kazda sekunde, po chwili jednak osuwa sie martwy na ziemie, a zapach swiezej posoki dodaje 
ci sil do dalszej walki.

**Comment by tjurczyk** [comment]
@ctarx @animal793 Dzieki, dodane w 3.8.
