### ISSUE TITLE
Zmiana trybu chodzenia nie działa klikiem na pasku.

### ISSUE THREAD

**Issue by ftpd** [tjurczyk/arkadia-skrypty#293]
Jak w temacie - przy kliknięciu w puste pole lub w 'ja' lub 'ja w +d' nie powinno przypadkiem zmieniać trybu na 'następny'?

**Comment by tjurczyk** [comment]
@ftpd wlasnie sprawdzilem, u mnie dziala. Czy to nadal wystepuje? Czy mozesz sprawdzic na czystej wersji skryptow na nowym profilu?

**Comment by ftpd** [comment]
@tjurczyk zrobiłem to, czyste 3.8 na nowym profilu na Mudlecie 3.7.1 (macOS 10.13.3) - nadal nie działa. I nie jestem raczej odosobniony, bo założyłem ten ticket po poście Vidgis na forum: http://arkadia.rpg.pl/forum/viewtopic.php?f=15&t=704&start=90#p54151

**Comment by ftpd** [comment]
(Dopiero teraz zauważyłem, że stestowałem na 3.8, które jeszcze nie wyszło - wziąłem z www paczkę opisaną jako skrypty_master3.zip. Nie wiem, skąd wziąć 3.7, tutaj jest jakiś staroć (3.1?)).

**Comment by tjurczyk** [comment]
Poprawione od nastepnej aktualizacji.
