### ISSUE TITLE
Bloker - Wezendorf wodospad

### ISSUE THREAD

**Issue by filipbober** [tjurczyk/arkadia-skrypty#299]
Jesli wpiszemy 'przejdz przez wodospad' bez wpisania uprzednio 'wejdz do wody' nie zmieniamy lokacji, a mapper przeskakuje.

Woda wydaje ci sie tak zimna, ze jednak decydujesz sie nie przeskakiwac przez sciane wody. Moze lepiej najpierw oswoic sie z chlodna woda...

**Comment by tjurczyk** [comment]
Dodane w 3.8.
