### ISSUE TITLE
Brak blokera dla wozu w Tilei.

### ISSUE THREAD

**Issue by ctarx** [tjurczyk/arkadia-skrypty#300]
`Nie mozesz sie tam udac, gdyz musisz najpierw zejsc z wozu.`

**Comment by tjurczyk** [comment]
Czy taki komunikat pojawi sie tez jesli wprowadzimy kierunek, ktory nie istnieje? czy wtedy pojawi sie "Nie ma wyjscia na..."?

**Comment by ftpd** [comment]
Przy wprowadzeniu nieistniejącego jest standardowe 'Nie widzisz zadnego wyjscia' i bloker działa.

**Comment by tjurczyk** [comment]
Dodane.
