### ISSUE TITLE
Brak odliczania czasu dla wycofania legionisty przy tarczy z Warowni

### ISSUE THREAD

**Issue by chlebik** [tjurczyk/arkadia-skrypty#302]
Unosisz swoja owalna masywna tarcze z umbem i szybko przesuwasz sie za XXXXX, kryjac sie przed 
atakami okrutnego kamiennego trolla.

Tutaj nie lapie odliczania dla wycofki legionisty. Zakladam, ze pattern nie dziala dla 'z umbem'

**Comment by tjurczyk** [comment]
Dzięki, poprawione w 3.8.
