### ISSUE TITLE
Wyswietlanie obecnej wartosci opoznienia

### ISSUE THREAD

**Issue by chlebik** [tjurczyk/arkadia-skrypty#304]
Ustawiajac /opoz XX okreslamy z jaka predkoscia postac idzie na laziku. Daloby sie dodac wersje bezparametrowa, albo inna n. /opoz_pokaz i wtedy po prostu klient wypluje jaka wartosc jest obecnie?

**Comment by animal793** [comment]
domyslnie w katalogu txt sobie ustawiasz jaka ma miec "startowa " wartosc.

**Comment by chlebik** [comment]
Nie no to wiem. Chodzi mi o to, ze czesto jest taki use case.

Biore paczke na poczcie. Zalozmy Mahakam. Odpalam chodzika, ale kwestia jest taka, ze to gory wiec mecze sie szybciej. Zatem ustawiam /idzdo 8 zalozmy. No i ide powoli, nie jestem zmeczony, wylazlem z gor i teraz chce przyspieszyc. Ale w sumie to nie pamietam jaka jest OBECNA predkosc. W sensie moge pamietac, ze ustawilem na 8, moge tez scrollowac liste komend, ale w sumie moglbym wpisac tylko same /opoz i by mi pokazal komunikat 'Twoja predkosc to 8'. No i teraz wiem, ze moge na luzie sobie ustawic na np. 4 czy 6 bo to sa na pewno mniejsze wartosci niz obecna. Teraz nie da sie tego sprawdzic, trzeba dawac idac na pale  /opoz XX.  

Wiem, ze to moze duperel i fanaberia, ale dla noszenia paczek to baaaaaardzo przydatna rzecz.

**Comment by Stokrotka2** [comment]
Gdy włączasz bądź wznawiasz łazik, zawsze pokazuje obecnie ustawioną wartość.

**Comment by chlebik** [comment]
No wlasnie - czyli wymusza to zatrzymanie postaci poprzez wylaczenie lazika. A ja nie chce wylaczac - chce isc dalej tylko z innym tempem.

**Comment by pprraavv** [comment]
Zrób sobie alias:
Alias name: jak_szybko
Pattern: /jak_szybko
Treść: amap:print_log("Ustawione opoznienie: " .. amap.walker_delay)

Użycie komendy /jak_szybko wyświetli aktualną szybkość chodzika.
Alias umieść poza katalogiem skrypty_master, to po aktualizacji nie zniknie (ale i tak będziesz musiał sprawdzić czy nadal działa).

**Comment by chlebik** [comment]
Thx.

**Comment by tjurczyk** [comment]
Dzięki, dobry pomysl.
Dodam cos do sprawdzenia opoznienia + dwie komendy: `/wolniej` i `/szybciej`, ktore beda odejmowaly lub dodawaly 1sek do opoznienia. Chyba, ze inna wartosc jest wskazana?

**Comment by tjurczyk** [comment]
@chlebik Od 3.8

```
| /chodzik - pokaze informacje o chodziku (cel i opoznienie).                    |
| /szybciej - przyspiesza chodzik.                                               |
| /wolniej - zwalnia chodzik.                                                    |
|                                                                                |
```

**Comment by chlebik** [comment]
Super!
