### ISSUE TITLE
Spece miecznika - obszar

### ISSUE THREAD

**Issue by Noisehammer** [tjurczyk/arkadia-skrypty#305]
Przy specach obszarowych miecznika, pierwszy gag markuje drugi cios, a drugi gag pierwszy.

Zgodnie z przykładem:
[JA 2/7] [JA 3/7] Niespodziewanie skrecasz tulow, wyprowadzajac przy tym oburacz dlugie uderzenie polyskliwym smuklym espadonem, ktore plytko
tnie groznego brutalnego czarnego orka w lewe ramie. Korzystajac z dogodnego ustawienia przeciagasz jeszcze cios, lekko raniac barczystego 
ciezkiego czarnego orka samym sztychem broni.

Wiem że wystarczy zamienić kolejność w triggerach tak, aby spec_obszar był wyzej niz spec, wtedy sprawa ze pierwszy gag markuje pierwszy cios, drugi gag drugi cios. Tak jak na obrazku:
https://snag.gy/BRzXTZ.jpg

Ale zgłaszam żeby nie było :)

**Comment by tjurczyk** [comment]
Dzięki za zgloszenie! poprawione od 3.8.
