### ISSUE TITLE
Bug przy specu partka

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#306]
[ .PAR> 3/5]  [PAR 5/7] xxxx dziko hallakujac uderza barczystego szkaradnego orka masywnym zdobionym
buzdyganem, bardzo ciezko raniac go w korpus.

**Comment by tjurczyk** [comment]
Wylaczylem pattern dla <PAR 3/5>, bo wydaje sie byc nieprawidlowy. Trzeba bedzie go doprecyzowac aby nie lapal sie z tym normalnym sc doskokiem. Potrzebny jest dokladny atak z zaskoczenia z "hallakowaniem".
