### ISSUE TITLE
Obsluga zakazanych kierunków na kompasie w belce dolnej

### ISSUE THREAD

**Issue by pprraavv** [tjurczyk/arkadia-skrypty#307]
Niektóre lokacje, np. na pustyni, nie zawierają opisów wyjść, a wręcz przeciwnie, podawane są kierunki, w których nie można iść. Mam wielką prośbę o uwzględnienie tego na kompasie w belce dolnej.

Przykładowymi elementami blokującymi drogę na pustyni mogą być:
> Podroz na polnoc, polnocny-wschod i polnocny-zachod uniemozliwia nieprzebyty masyw gorski.

> Szeroka rozpadlina rozciaga sie po pustyni, czyniac podroz na poludniowy-wschod, poludniowy-zachod i zachod niemozliwa.

> Mury miejskie nie pozwalaja ci isc na polnoc, polnocny-wschod i wschod.

A także ich kombinacje:

> Masyw gorski czyni niemozliwa podroz na zachod, a szeroka rozpadlina - poludniowy-wschod.

> Szeroka rozpadlina zagradza droge na poludnie i poludniowy-zachod, a mury wielkiego miasta - polnoc i polnocny-wschod.

Aby się nie narobić proponuję skorzystać z gotowych triggerów łapiących niestandardowe wyjścia (wyjscia-2_1): `Mozesz podazac traktem na (.*) albo (.*). Natomiast aby zejsc z wytyczonej drogi musisz udac sie na (.*)\.$`

Przy czym zamiast rysować złapane kierunki należy stawiać tam znaczek oznaczający blokadę drogi.
Sprawdziłem kilka opcji i dobrze w tej roli spełnia się cudzysłów ("). Ma rozmiar, który wstawiony zamiast dowolnego kierunku nie dewastuje kompasu. Docelowo dla wymienionych przykładów wyglądało by to jak niżej (sadzę że jest dość czytelnie):
> Podroz na polnoc, polnocny-wschod i polnocny-zachod uniemozliwia nieprzebyty masyw gorski.
```
 "  "  "
 -  o  -
 /  |  \
```
> Szeroka rozpadlina rozciaga sie po pustyni, czyniac podroz na poludniowy-wschod, poludniowy-zachod i zachod niemozliwa.

```
 \  |  /
 "  o  -
 "  |  "
```

> Mury miejskie nie pozwalaja ci isc na polnoc, polnocny-wschod i wschod.

```
 \  "  "
 -  o  "
 /  |  \
```

> Masyw gorski czyni niemozliwa podroz na zachod, a szeroka rozpadlina - poludniowy-wschod.

```
 \  |  /
 "  o  -
 /  |  "
```

> 
Szeroka rozpadlina zagradza droge na poludnie i poludniowy-zachod, a mury wielkiego miasta - polnoc i polnocny-wschod.

```
 \  "  "
 -  o  -
 "  "  \
```

Jaka jest szansa na wprowadzenie takiej opcji?
Coś jeszcze byś potrzebował?

**Comment by tjurczyk** [comment]
Swietna propozycja, bede dodawal w najblizszym czasie. Rysowanie tez ma sens.

Mam jedno pytanie. Jak rozumiem, informacja o tym ktory kierunek nie jest mozliwy jest drukowana **zamiast** informacji w ktorych kierunkach mozna sie wybrac, tak?

**Comment by pprraavv** [comment]
Nie, niestety jest jeszcze inaczej. 
Podane przypadki, gdzie drogę blokuje masyw górski/rozpadlina/mury występują na pustyni Zerrikańskiej. Gdy taka blokada wystąpi podawane są kierunki, w których nie można iść, natomiast w pozostałych (niewymienionych) kierunkach można się udać. 

Czyli jeśli na pustyni są wymieniane zakazane kierunki, to należy narysować pełną róże (wszystkie kierunki), a potem te zakazane zamienić np. na "x".
Można też pokusić się o zastosowanie innego znaczka dla rozpadliny (w którą można wejść), a innego dla murów/masywu górskiego, które są nieprzekraczalne. 

Napisałem skrypt, który to nadpisuje ale odkryłem, że sprawę komplikują jeszcze wyjątkowe przypadki, w których wyjścia są podawane w sposób standardowy (a wiec zadziałają standardowe Triggery wyjscia/wyjscia-2/...). Przykładowo, wejście na pustynie, wejście do miasta, oaza. Stąd to co zakodowałem działa, ale mało stabilnie (nie rozumiem wszystkich mechanizmów rysowania kompasu).
Mimo niepowodzeń wydaje mi się, że na pustyni uniwersalna procedura rysowania (zapisana pseudo kodem) powinna wyglądać tak:
```
if Zerrikania=true then
	if (są_standardowe_wyjścia=true) then
		rysowanie_standardowych_wyjść
	else
		rysowanie_pełnego_kompasu
	end if

	if (są_zablokowane_kierunki=true) then
		nałożenie_zablokowanych_kierunków_na_narysowany_kompas
	end if
end if
```

**Comment by tjurczyk** [comment]
Pustynie mozna z latwoscia dodac. Mozesz podac przyklad kiedy blokada wystepuje razem z kierunkami, w ktorych mozna sie wybrac?

**Comment by tjurczyk** [comment]
Jak na razie mamy cos takiego.
<img width="1128" alt="screen shot 2018-02-25 at 7 55 33 pm" src="https://user-images.githubusercontent.com/1749428/36652825-0576f038-1a66-11e8-95c5-b04daf8c3575.png">
