### ISSUE TITLE
drobna zmiana w /ob

### ISSUE THREAD

**Issue by pprraavv** [tjurczyk/arkadia-skrypty#309]
zamiast: powsun bron do ....
zmienić: powsun dobyta bron do ...

jak się nosi dodatkowe np. sztylety za pasem, to /ob próbuje czasem chować do pochwy bron która jest obecnie za pasem

**Comment by Stokrotka2** [comment]
*/wlb
/ob tylko opuszcza broń

**Comment by pprraavv** [comment]
Ok, dzięki za zwrócenie uwagi. Możliwe że pospieszyłem się z prośbą o zmianę skryptów, bo sporo zależy jeszcze o wpisów w pliku konfiguracji.
U mnie /ob opuszcza broń i chowa ją do pochew ponieważ mam ustawione:
scripts.inv.main_weapons_action = {1, 2}

Ale przeglądając jeszcze raz plik konfiguracyjny trafiłem na linijkę: 
scripts.inv.weapon1_action_off = false

Przetestuję wieczorem zmianę tych wartości na: "powsun dobyta bron do ... " i jak to rozwiąże problem, to ticket będzie do zamknięcia.
