### ISSUE TITLE
do listy blokerow

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#31]
Nie mozesz sie tam udac, gdyz rosly zamaskowany mezczyzna wraz z kamratami blokuja ci droge na 
polnoc.

**Comment by animal793** [comment]
i drugi wylapany:

Kierujesz sie w strone krzakow porastajacych polnocno-wchodnia czesc kotliny, lecz bezradnie 
zatrzymujesz sie przed zwarta sciana kolcow i galezi. Nie znajdujesz sposobu, jak wejsc w chaszcze.

**Comment by tjurczyk** [comment]
Dodane.
