### ISSUE TITLE
upgrade okna states_window

### ISSUE THREAD

**Issue by pprraavv** [tjurczyk/arkadia-skrypty#310]
Wygodne byłoby dodanie do okna states_window linijki, która zawierałaby istotne dla walki informacje, które obecnie występują na belce dolnej. Byłoby to proste kopiowanie elementów z dołu, co wyglądać by mogło przykładowo tak:

```
Zme: [4:9] Zas:3 Roz:ok Alert: ZNI. BRON	
  [ @][-######] JA
  [  ][#######] umiesniony tepy ork
  [  ][#######] zoltooki brutalny ork
```
Po co takie powielanie?

Przy dynamicznych walkach z wieloma użytkownikami kontrola pola bitwy wymaga zasłaniania, przełamywania i atakowania lub wyznaczania celów (ataku/obrony). Operacje te genialnie wykonuje się myszką w oknie z kondycją, ale oprócz obserwacji kto kogo bije jednocześnie trzeba śledzić takie parametry jak:
- zmęczenie (spada przy przełamywaniu, można nie mieć sił na wycofanie się.)
- odliczanie do zasłony
- odliczanie do rozkazu (o ile jest - bo akurat ja nie umiem dowodzić, wymieniam na zapas)
- alerty (wytrącenie->dobycie broni, zatrucie itp.)
- ... (może coś jeszcze istotnego, o czym nie pomyślałem?)
Obserwacja tego wszystkiego wymaga ciągłego przeskakiwania wzrokiem pomiędzy dolną belką, a oknem kondycji. Dużo wygodniej byłoby mieć te informacje w jednym miejscu (w oknie states_window, nad wierszem JA). Bez tego jak jest gorąco, to i tak nie śledzę belki na dole, tylko bezmyślnie klikam na poleceniu zasłony (mimo że jest za wcześnie). 

Jest to w ogóle możliwe?

**Comment by tjurczyk** [comment]
Dobra idea. W 3.8 się nie wyrobie, ale w 3.9 jest to do zakodowania.

**Comment by ftpd** [comment]
Myszką? Naprawdę? ;-)
Ale zgadzam się, pomysł niegłupi.

**Comment by pprraavv** [comment]
Tak, myszką. Jestem RTS-owym klikaczem :P. Sprawniej klikam w imię, niż wpisuję /za B.

**Comment by tjurczyk** [comment]
@pprraavv z klikaniem myszka moze byc problem dopoki nie naprawia problemu z brakiem focusa:
https://github.com/Mudlet/Mudlet/issues/1172
Chyba, ze nie przeszkadza ci to nie przeszkadza.

**Comment by pprraavv** [comment]
Nie przeszkadza mi to, bo okno states_window mam zagnieżdżone. A wówczas nie ma tego problemu, można klikać i pisać.
Ekran podzieliłem sobie na cztery zagnieżdżone okna: główne, states_window, mapę i udało mi się zrobić działające okno z klonowaniem dialogów. :)

**Comment by tjurczyk** [comment]
Na chwilę obecną mam cos takiego. 

* oddzielone `||`
* wybieralne itemy/kolejnosc
* konfiguralne symbole: mozna zmienic `BRON` na cokolwiek sie chce.

<img width="399" alt="screen shot 2018-03-04 at 3 34 59 pm" src="https://user-images.githubusercontent.com/1749428/36952223-ac0fd1e8-1fc1-11e8-9dbe-f9453dfc105a.png">

**Comment by tjurczyk** [comment]
https://github.com/tjurczyk/arkadia-skrypty/issues/250

**Comment by apolios** [comment]
Nie do końca rozumiem, co będzie można wybrać w oknie kondycji dla każdej postaci. Będzie można np kliknąc myszką zaataku/zasłon/przełam, itp? Jeśli tak to proponuję również zaskocz.

**Comment by pprraavv** [comment]
Fakt, przydałoby się zaskakiwanie uruchamiane myszką. Bo wpisanie "zaskocz mezczyzne" możne sprawić, że zaskoczysz... członka drużyny. Komendę trzeba powtórzyć, ale zdarzyło się :P. Skutki bywają ciekawe, zwłaszcza w dużej drużynie, gdy różnie się osoby powspierały. 
Dla osób operujących klawiaturą sprawa jest dość prosta: wystarczy dopisać aliasy /x i /xx (na wzór /z i /zz - tylko z zaskocz).
Dla klikaczy myszką.. hmm.. sprawa jest bardziej skomplikowana, opiszę w oddzielnym tickecie jak wg mnie powinno to działać w przypadku nożownika. A nuż dostanie on status Feature i uda się kiedyś wprowadzić.

**Comment by tjurczyk** [comment]
Od 3.9 wersja pilotowa:

--
-- Czy uzywac paska stanow jako naglowka w oknie stanow
--
scripts.ui.cfg["states_window_navbar"] = false

--
-- Jakie elementy maja znalezc sie w naglowku okna stanow.
-- Dostepne to: "bron", "zaslona", "rozkaz", "ukryty"
-- Kolejnosc bedzie taka, jak wymieniona ponizej.
--
scripts.ui.cfg["states_window_nav_elements"] = {
  "bron",
  "zaslona",
  "rozkaz",
  "ukryty",
}

--
-- Jakie przedrostki maja byc uzywane do poszczegolnego elementu
-- Jesli do "bron" uzyte jest "BRON", to w naglowku pojawi sie:
-- "BRON: on" lub "BRON: off"
--
scripts.ui.cfg["states_window_nav_printable_key_map"] = {
  ["bron"] = "BRON",
  ["zaslona"] = "ZASLONA",
  ["rozkaz"] = "ROZKAZ",
  ["ukryty"] = "UKRYTY",
}
