### ISSUE TITLE
poprawki w talk_window

### ISSUE THREAD

**Issue by pprraavv** [tjurczyk/arkadia-skrypty#311]
Tekst w oknie rozmów nie zawija się poprawnie.
Do funkcji inicjującej okno można dodać setWindowWrap("talk_window", talk_window_wrap).
Zmienną  talk_window_wrap można dopisać do pliku imie.txt jako parametr. Możesz również spróbować wyciągnąć  to z aktualnego rozmiaru okna rozmów (mnie się nie udało, i chyba się nie da).

Druga usprawnienie:
Wg mnie oprócz rozmów do okna warto również przerzucać komunikaty z Gmcp_msgs:
`emotes - emocje skierowane do postaci gracza`
Często uzupełniają one dialogi, a nie jest ich za dużo.  Ewentualnie można to dodać do imie.txt jako kolejny parametr.

**Comment by animal793** [comment]
By nie dodawac nowego ticketa bo to w tym samym temacie.

Bylaby wogole mozliwosc usuniecia z okna spamu od mobow 

bo cale okno ciagle jest zasypane krzykami orkow i goblinow
typu Arrghh moja cie zabic! 
waa zabic kurdupla itp...

**Comment by tjurczyk** [comment]
Nowe opcje:

```
--
-- Zawijanie wierszy w oknie rozmow (jeslo uzywane)
-- Procentowa wartosc. 0.8 (domyslnie) to 80%
-- 0.5 bedzie 50%, itp.
--
scripts.ui.separate_talk_window_p_width = 0.8

--
-- Prefix do kazdego wiersza w oknie rozmow.
-- Jesli ustawi sie "> ", przed kazdym wierszem bedzie sie pojawialo "> "
--
scripts.ui.separate_talk_window_prefix = ""

--
-- Typy komunikatow, ktore maja sie pojawiac w oknie rozmow.
-- Domyslnie sa to rozmowy i emocje. Wszystkie typy wysylane przez arkadie sa tutaj:
-- 
-- Format ma zostac taki jak ponizej: ["typ_komunikatu"] = true
--
scripts.ui.separate_talk_window_msg_types = {["comm"] = true, ["emotes"] = true}
```
