### ISSUE TITLE
Przeglądanie i kupowanie w sklepie na klik.

### ISSUE THREAD

**Issue by apolios** [tjurczyk/arkadia-skrypty#312]
Taka propozycja ode mnie listy przedmiotów u kupców. Po kliknięciu w nazwę wyświetlanie w osobnym oknie opisu przedmiotu z komendy "pokaz x". Po kliknięciu K kupowanie przedmiotu. Dlaczego w osobnym oknie? By nie przewijać okna głównego co chwile po przejrzeniu wielu przedmiotów.
```
-------------------------------------------------------------------------------
|               Nazwa towaru              |Mithryl| Zloto | Srebro| Miedz |Kup|
-------------------------------------------------------------------------------
| Masywna zlocona spinka                  |       |   10  |   3   |   7   | K |
| Blekitna cienka peleryna                |       |   15  |   2   |   11  | K |
| Ciemnoczerwony matowy plaszcz           |       |   3   |   10  |   8   | K |
| Futrzany popielaty plaszcz              |       |   4   |       |   8   | K |
| Dlugi ciemnozielony plaszcz             |       |   3   |   5   |   7   | K |
| Prosty brazowy plaszcz                  |       |   3   |   5   |   7   | K |
| Wyszywany czarny plaszcz z brosza       |       |   4   |   18  |   5   | K |
-------------------------------------------------------------------------------
```
Jak oznaczyć wpis jako feature?

**Comment by tjurczyk** [comment]
@apolios jak rozwiązać sprawę odmiany? 
`Blekitna cienka peleryna` -> `blekitna cienka peleryne`. Skrypt musialby uruchamiac odmiane, wyluskac odmiane i jej uzyc. Mam wrazenie, ze jest to na dzien dzisiejszy nielegalne.

**Comment by apolios** [comment]
Zapomniałem o odmianie. Skoro to nielegalne, to rzeczywiśscie odpada.  A rozwiązaniem mogłoby być utworzenie np. tablicy odmian bez przymiotników i potem używanie tylko pokaz/kup 1. spinke, pokaz/kup 2. spinke. Choć i tak trzeba by było nazbierać nazw przedmiotów od kupców i potem ją sukcesywnie uatualniać, zatem sporo roboty. Myślałem, że arka przesyła informacje o przedmiotach w jakiś bardziej usystematyzowany sposób, który łatwiej ogarnąć.

**Comment by tjurczyk** [comment]
Z tego co wiem to gmcp ma w koncu miec support do przedmiotow, ale nie wiem czy bedzie to dotyczylo itemow sklepie.
