### ISSUE TITLE
Pojemniki do dodania (listowanie)

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#316]
ob kosz
Wysoki na ponad trzy stopy wielki pleciony kosz. Jest to najlepsze miejsce do odkladania ekwipunku,
zarowno nadajacego sie do przyszlego wykorzystania, jak i tego tylko do wyrzucenia.
Jest otwarty.
Otwarty kosz zawiera wielobarwny turmalin,

ob stojak
Zbite z kilku solidnych desek stojaki na bron ustawiono w namiocie tak, by bez przeszkod mozna bylo
w pospiechu siegnac po znajdujace sie wewnatrz sztuki oreza. Na kazdym z nich wypalono znak Czarnego 
Gryfa, zas ich drewniane konstrukcje po zamknieciu stanowia gotowe do transportu skrzynie.
Jest otwarty.
Na stojakach zauwazasz miedzy innymi poszczerbiony obureczny miecz,

**Comment by pprraavv** [comment]
Podejrzewam, że potrzebne będą przykłady opisów nie pustych stojaków/pojemników (w stylu: Solidny stojak na bron zawiera: duzy miecz i dwa sztylety). Wówczas można by to dopisać jako trigger do pojemników.

**Comment by animal793** [comment]
juz poprawilem.

**Comment by tjurczyk** [comment]
Dodane.
