### ISSUE TITLE
Mozliwosc wyboru komendy dla klikniecia 'bron' na pasku UI.

### ISSUE THREAD

**Issue by ctarx** [tjurczyk/arkadia-skrypty#32]
Obecnie `scripts.inv.weapons.click_id` okresla z ktorej pochwy ma brac/wkladac przy naciskaniu 'bron', ale klikniecie na 'bron' w pasku wykonuje komendy /db i /ob.

Wiec przy ustawieniu `scripts.inv.main_weapons_action = {}` nasza postac jedynie dobedzie, badz opusci bron, co powoduje ze powyzsze ustawienia nie maja znaczenia.

Wedlug mnie powinna byc mozliwosc okreslenia co ma wykonac klik na pasku.
Ja chce klikajac dobywac bron ze zdefiniowanej pochwy, a komenda /db /ob dobywac/opuszczac bron bez wsuwania jej gdziekolwiek.

Przy ustawieniu `scripts.inv.main_weapons_action = {1}` dziala klikanie tak jak chce, ale komenda /db wykonuje wtedy to samo co /db1 co jest dla mnie bezsensu.

**Comment by animal793** [comment]
ja bym dodal by do tego paska mozna bylo sobie dodac komendy ktore wykonuje.

Np.

gzdobadz/gzopusc

gzporwij;gzpozycja/ gzopusc.


by emotami mozna bylo dobywac i opuszczac za pomoca paska.

**Comment by ftpd** [comment]
-1
Po to jest właśnie scripts.inv.weaponN_action_on, scripts.inv.weaponN_action_off i scripts.inv.main_weapons_action żeby sobie zrobić dobywanie określoną komendą (czyli to, co wnioskujesz, @animal793), a potem dobywać/chować z /db albo kliknięcie na pasku. Było to zaimplementowane w:
https://github.com/tjurczyk/arkadia-skrypty/issues/9
https://github.com/tjurczyk/arkadia-skrypty/issues/23

Jak chcesz alias do samego dobywania (po co on komu? przecież wszyscy nosimy w pochwie/pojemniku, bo waga), to sobie zrób swój ;-)

**Comment by tjurczyk** [comment]
Ok, to zamykam. `click_id` już nie ma w configu. Należy używać:

```
scripts.inv.main_weapons_action = {}
```
