### ISSUE TITLE
Aktualizacja zawodu Barbarzyncy

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#320]
Kolejny Finisher

Wykonujesz potezny zamach jednorecznym stalowym mlotem rycerskim i wkladajac w cios cala swa sile,
uderzasz na odlew malego chichoczacego goblina. Twa bron ze zlowrogim jekiem rozrywanego powietrza 
miazdzy jego witalne organy, w jednym momencie odbierajac zycie. Spogladasz triumfalnie na stygnace 
truchlo, a zapach swiezej posoki dodaje ci sil do dalszej walki.

Twarz XXX wykrzywia grymas wysilku, gdy wykonuje potezny zamach dwurecznym adamantytowym mlotem
bojowym i z ogromna sila uderza na odlew siwego kamiennego trolla. Bron ze zlowrogim jekiem 
rozrywanego powietrza tlucze jego cialo, otwierajac gleboka, tryskajaca krwia rane. Przeciwnik 
probuje jeszcze ustac, walczac o kazda sekunde, po chwili jednak osuwa sie martwy na ziemie, a na 
zbryzganym szkarlatem obliczu XXX pojawia sie triumfalny, bezlitosny usmiech.

**Comment by tjurczyk** [comment]
Dodane w nastepnej aktualizacji.
