### ISSUE TITLE
Zmiana szyku

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#321]
przy kazdym dolaczeniu odlaczeniu do druzyny wyswietla sie takie info

XXX rozwiazuje druzyne.
Modul objects jest juz wlaczony.

Modul gmcp_msgs jest juz wlaczony.

tak ma byc?

**Comment by tjurczyk** [comment]
Tak, ma sie to pojawiac. Wczesniej byl uzywany nieoficjalny tryb wysylania danych. Teraz korzystam arkadiowych komend do gmcp i to ma sie pojawiac.
