### ISSUE TITLE
Mapper zagubiony przy komendzie idz

### ISSUE THREAD

**Issue by filipbober** [tjurczyk/arkadia-skrypty#324]
Mapper zaczyna zmieniać lokacje po wpisaniu komendy 'idź' dopiero po pierwszej zmianie lokacji, dlatego zawsze pozostaje w tyle o jedno przejście.

**Comment by tjurczyk** [comment]
@filipbober u mnie `idz` dziala od pierwsze lokacji. Czy mozesz stanac na jakims trakcie (tylko dwa mozliwe wyjscia) i sprawdzic. Ew., jesli pojawia sie error w debug to przeslac.

**Comment by filipbober** [comment]
Stanąłem na lokacji na trakcie, z dwoma wyjściami. Żadnych błędów. Natomiast błąd występuje: wklepuję 'idz marszem', postać przechodzi jedną lokację, mapper stoi, postać przechodzi następną lokację, mapper rusza się o poprzedni kierunek (czyli jest jedną lokację z tyłu)..

**Comment by tjurczyk** [comment]
`idz marszem` poprawione. Powinno juz dzialac ok.
