### ISSUE TITLE
Wsparcie ataków z zaskoczenia (gagi, okno)

### ISSUE THREAD

**Issue by pprraavv** [tjurczyk/arkadia-skrypty#329]
Tytułem wstępu poniżej logi jak wygląda zaskakiwanie wroga z perspektywy nożownika.
Po pierwsze (i chyba oczywiste) zaskakiwanie może zostać wykonane tylko gdy postać jest ukryta.
[miejsce na log z komunikatem przy próbnie zaskoczenia bez ukrycia się]
Po ukryciu się komenda  „zaskocz xxx” może mieć dwa efekty:
1. przeciwnik uciekł - nie ma kogo zaskoczyć - można natychmiast ponownie zaskoczyć inny cel lub podążyć za wrogiem np.:
```
> zaskocz snotlinga
Kilkoma cichymi, plytkimi wdechami uspokajasz serce. Przecierasz dlonie z potu by chwyt na motylkowym nilfgaardzkim sztylecie i dlugim waskim sztylecie byl pewny i przygotowujesz sie do niespodziewanego ataku na niskiego siakajacego snotlinga. 
Niski siakajacy snotling podaza na polnoc.
Nie widzac nigdzie niskiego siakajacego snotlinga rezygnujesz z wyprowadzenia ciosu.
```

2. przeciwnik został zaatakowany (nieważne czy skutecznie, czy nieskutecznie) - wywiązuje się walka.
```
> zaskocz snotlinga
Kilkoma cichymi, plytkimi wdechami uspokajasz serce. Przecierasz dlonie z potu by chwyt na dwoch koscianych mlecznobialych sztyletach byl pewny i przygotowujesz sie do niespodziewanego ataku na bezzebnego chichoczacego snotlinga
(…)
Bezszelestnie skracasz dystans dzielacy cie od bezzebnego chichoczacego snotlinga i zdecydowanym pchnieciem wbijasz dwa kosciane mlecznobiale sztylety w jego korpus! Cialem przeciwnika wstrzasa ledwie zauwazalny spazm bolu.
Bezzebny chichoczacy snotling ledwo muska cie kuchennym wyszczerbionym nozem, trafiajac cie w korpus.
Obracajac w reku swym koscianym mlecznobialym sztyletem wykonujesz nagly zwod i trafiasz bezzebnego chichoczacego snotlinga pozostawiajac tylko nieznaczne obrazenia.
[… dalsza walka… ]
```

Dla osób operujących klawiaturą sprawa jest dość prosta: wystarczy dopisać aliasy /x i /xx (na wzór /z i /zz - tylko z zaskocz).

Dla osób posługujących się myszką w oknie „states_window” opiszę dokładniej jak bym to widział:
Sądzę, że dobrym rozwiązaniem jest dodanie opcjonalnej pozycji: "Zaskocz: ok" (najlepiej w oknie statusów nad JA). Będzie on równocześnie liczniem czasu do kolejnego zaskoczenia. Po kliknięciu na ten przycisk: 

1. jeśli aktywna jest opcja "Ok, nie bede numerowal nie-wrogow" chwilowo włączane jest numerowanie wszystkich (poprzez funkcję /numeruj) Dlaczego? Atak z zaskoczenia prawie zawsze jest wykonywany z ukrycia przed nawiązaniem walki, gdy postać jeszcze nie jest wrogiem.
2. klikniecie w numerek np. 2 wysyła zaskocz 2 (zamiast zabij 2)

I tu mamy kilka ścieżek zgodnie z logami wyżej:
a) jeśli przeciwnik wyjdzie z lokacji 
- można zaznaczyć strzałką gdzie on poszedł (tak jak dla ucieczki) – zaskakiwanie jest nadal aktywne, wszyscy na lokacji są numerowani, można wybrać innego wroga, przemknąć się za obecnym celem lub zrezygnować z zaskoczenia (klikając ponownie w zaskocz: ok)

b) jeśli przeciwnik nigdzie nie poszedł, a atak z zaskoczenia został wykonany:

- numerowanie wrogów wraca do pozycji wyjściowej
- klikanie na numerki wysyla zabij XXX (można zmieniać cele ataku i walczyć tak jak bez opcji Zaskocz)
- przycisk „Zaskocz: ok” zmienia się na „Zaskocz: XX” - czas XX stoi w miejscu

Po skończonej walce uruchamia się licznik odliczający czas XX, oznaczający kiedy będzie można ponownie zaskoczyć kolejnego wroga. O ile pamiętam jest on chyba dłuższy od czasu do ukrycia, postaram się sprawdzić ile to sekund (chyba że ktoś wie).

c) ujawnienie podczas przygotowania 

- hipotetycznie może się zdarzyć przypadek, gdy ktoś ujawni nas w ciągu tych kilku sekund pomiędzy komendą > zaskocz XXX,  a samym atakiem. Nie wiem co wtedy. Prawdopodobnie trzeba automatycznie wyłączyć opcję zaskakiwania (przywrócić numerowanie wrogów, klik na cyfrze oznacza zabij xxx). Nie trafił mi się taki przypadek, ale chyba jest możliwy.

**Całość opisałem z perspektywy nożownika. Cenne byłyby uwagi i logi od pozostałych postaci mogących zaatakować z zaskoczenia.**

**Comment by pprraavv** [comment]
Po przeczytaniu swoich wypocin przyszedł mi do głowy drugi, chyba prostszy w implementacji sposób na zaskakiwania wrogów. Prostszy, więc może łatwiejszy do zakodowania.
"Zaskocz: ok"  pełni funkcję tylko licznika czasu do zaskoczenia. Zaskakiwanie jest połączone z ukrywaniem się.

Bez ukrycia się okno states window wygląda standardowo, dla przypomnienia:
```
  [ @][#######] JA
  [  A][#######] Członek_druzyny
  [  ][#######] dojrzala jasnowlosa kobieta
  [  ][#######] barczysty postawny mezczyzna
  [  1][#######] mały snotling

```
Gdy postać jest ukryta, okno to przyjmuje postać 
```
  [ @][  ][#######] JA
  [ A][  ][#######] Członek drużyny
  [  ][z1][#######] dojrzala jasnowlosa kobieta
  [  ][z2][#######] barczysty postawny mezczyzna
  [ 1][z3][#######] mały snotling
```

- Kliknięcie na [zX] – wysyła zaskocz X
- Można zaskoczyć również nie-wrogów takich jak snotling (znaczy jeszcze nie-wrogow) 
- Nie można zaskoczyć członków drużyny, nawias przy nich jest pusty
- Nie zabieramy opcji normalnego atakowania wrogów: klik na [ 1] (bo np. odliczanie do zaskoczenia jeszcze trwa, a my chcemy atakować już teraz, zaraz...)
- Po skutecznym zaskoczeniu/ujawnieniu postać przestaje być ukryta, więc okno automatycznie wraca do widoku standardowego (nawiasy [zX ] znikają)

Całość oczywiście w konfiguracji można włączyć/wyłączyć.

**Comment by apolios** [comment]
Dobrze opisane. Drugi pomysł jest według mnie lepszym rozwiązaniem. Nie trzeba nawet kodować zmiany okna stanów. Druga postać okna byłaby jedynym a zX byłyby puste gdyby nie było możliwości zaatakowania z zaskoczenia. By jeszcze uprościć kod, z1..zX byłyby zawsze dostępne do kliknięcia, po prostu po kliknięciu w zaskocz, gdy nie ma takiej możliwości pojawiłby się standardowy arkadyjski komunikat o braku takiej możliwości.
Uważam nawet iż zmiana podczas walki okna na różne jej odmiany nie jest dobrym pomysłem gdyż można missclicknąć przez to.

**Comment by pprraavv** [comment]
Zaproponowałem wyświetlanie opcji ataku z zaskoczenia tylko wtedy gdy postać jest ukryta po to, aby uniknąć zaśmiecania okna statusu. Przez 99% czasu walki postać nie jest ukryta - przyciski są zbędne. Zaskoczenie przeciwnika wykonywane jest zazwyczaj sporadycznie, przy rozpoczęciu starcia. Potem zazwyczaj nie ma czasu na wycofanie się i skuteczne ukrycie (ochłoń od walki!). 
W zasadzie najlepiej byłoby gdyby było to konfigurowalne w imie.txt:
zaskok = 0 - brak opcji zaskoku
zaskok = 1 - linki [zX] widoczne tylko po ukryciu 
zaskok = 2 - linki [zX] widoczne cały czas

**Comment by tjurczyk** [comment]
Od 3.9:

```
-- Ustawienie zaskakiwania w oknie stanow.
-- Domyslnie na 0, czyli brak opcji zaskakiwania.
--
-- Jesli wybierze sie 1 to wiersz bedzie wygladal mniej wiecej:
-- [ 1][xx][#######] ...
-- po kliknieciu na [xx], postac zaskoczy 'xx'
-- wiersz bedzie sie tylko pokazywal wtedy, kiedy postac moze zaskoczyc
-- (warunek to czas od ukrycia, konfigurowalny ponizej)
--
-- Jesli wybierze sie 2 to czesc wiersza [xx] bedzie 
-- zawsze pokazywana
ateam.sneaky_attack = 0

-- Ustawienie jak dlugo (czas sekund badz "ok") 
-- ma minac od ukrycia sie, aby pokazala sie czesc wiersza [xx].
-- Ta wartosc jest uzywana gdy w 'ateam.sneaky_attack' wybierze sie 1.
--
-- Dozwolone wartosci sa od 0 do 14 lub "ok".
ateam.sneaky_attack_cond = "ok"
```
