### ISSUE TITLE
poludniowy kurhan bagna kolo witten / banici

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#33]
po uzyciu podpietych przejsc specjalnych pod lokacje

Zlap za pnacze;przeskocz nad pulapka

Mapper ( kropka) frezzuje sie i nie podaza dalej. Nie dziala w obie strony.

====
Lapiesz sie za zwisajace pnacze i silnym szarpnieciem sprawdzasz jego wytrzymalosc. Z gory leci 
nieco piachu, lecz korzen wydaje sie trzymac mocno. 
Cofasz sie o krok do tylu i odbijajac sie silnie, zawisasz na korzeniu, lecac na nim nisko nad 
ziemia! Udalo ci sie przeskoczyc na druga strone! Uf.. 

=======

banici wyjscie z wozu od ogra
LOK ID: 16107  -> na zewnatrz -> 16099
[4]..... na zewnatrz.
Centrum obozu.
Sa tutaj cztery widoczne wyjscia: poludniowy-zachod, polnoc, poludnie i wschod.

Po uzycia przejscia specjalnego przypietego kropa takze nie wskakuje do wozu.

**Comment by tjurczyk** [comment]
Od updateu mapy poprawione.
