### ISSUE TITLE
imie.txt kolory

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#331]
-- scripts.people.colored_guilds = {
-- ["AL"] = "orangered",
-- ["KG"] = "green",
-- ["OK"] = "orangered",
-- ["GL"] = "orangered",

Te kolory mi nie dzialaja i nakladaja sie na nie zamiast moich ustawien z imie txt ustawienia z kolorow arki " znani" itp.

**Comment by ftpd** [comment]
Ale wiesz, że początek linii '--' to komentarz? Jak ma zadziałać coś zakomentowane?

**Comment by tjurczyk** [comment]
Poza tym nie ma koloru `orangered` z tego co widze.
