### ISSUE TITLE
Ziola

### ISSUE THREAD

**Issue by DarkTriss** [tjurczyk/arkadia-skrypty#333]
Z cyklu "marzenia ściętej głowy":

1) Skoro już istnieje baza ziół to czy dużym problemem jest dorobienie do niej opcji przeszukiwania jak w bazie imion. W sensie po nazwie, shorcie, fragmencie shorta? Tak żeby baza zwracała mi informacje typu: deliona zloty jasny kwiat zjedz: -zmc
Czasem by się przydało.

2) Opcja premium dla mnie zbierającej zioła to nazwa zioła w nawiasie kiedy to zioło widzę. W sensie: Znajdujesz/ktoś daje ci/wskazuje zloty jasny kwiat (deliona).

**Comment by tjurczyk** [comment]
@DarkTriss Dodane w 3.11:

<img width="613" alt="screen shot 2018-09-30 at 11 39 34 pm" src="https://user-images.githubusercontent.com/1749428/46275915-60918480-c513-11e8-926c-215976497d7c.png">

Z wyroznianie ktore ma sie w workach.

W dodatku, dodana opcja:

```
-- Czy uzywac triggerow dodawajacych nazwy ziol
-- (zolty jasny kwiat -> zolty jasny kwiat (deliona))
herbs["use_herb_triggers"] = true
```

<img width="504" alt="screen shot 2018-10-01 at 12 46 35 am" src="https://user-images.githubusercontent.com/1749428/46275940-799a3580-c513-11e8-8a12-5f127b6de6c8.png">
