### ISSUE TITLE
[3.9] atak z zaskoczenia w states_window nie działa przy wyłączonym numerowaniu.

### ISSUE THREAD

**Issue by ftpd** [tjurczyk/arkadia-skrypty#334]
Przy ateam.all_numbering = false pojawia się wprawdzie [xx], ale jest nieklikalne. Podobnej sytuacji spodziewałem się w /oceniaj, ale tam wstawia ob_<cyferki>, może dałoby się i do zaskoku?

**Comment by tjurczyk** [comment]
Dodane od nastepnej aktualizacji.
