### ISSUE TITLE
Gnomia mowa nie wyłapuje mówienia do kogoś.

### ISSUE THREAD

**Issue by ctarx** [tjurczyk/arkadia-skrypty#338]
W przypadku ustawienia własnych opcji dotyczących mowy, czyli przykłądowo:
```
misc.lang["aliases"] = {["p"] = "potoczna"}
misc.lang["aliases_prefix"] = {["p"] = "ochryple"}
misc.lang["gnome_speech"] = true
```
i próbie powiedzenia do kogoś :
```
p do dziecka co jest
Mowisz ochryple: DoDzieckaCoJest.
```
przy ustawieniu **misc.lang["gnome_speech"] = false**
wszystko działa poprawnie:

```
p do dziecka co
Mowisz ochryple do slicznego rozczochranego dziecka: Co.
```

**Comment by tjurczyk** [comment]
Zastanawiam sie jak to rozwiazac, bo nie jest mozliwym wylapanie ktora czesc odpowiada za `do ...`:

`p do dziecka co jest`
`p do rozczochranego dziecka co jest`
`p do brudnego rozczochranego dziecka co jest`

**Comment by tjurczyk** [comment]
@ctarx Jedyne co mi przychodzi do glowy to zastosowanie jakiegos splittera:

```
p do dziecka$ co jest
p do rozczochranego dziecka$ co jest
p do brudnego rozczochranego dziecka$ co jest
```

Czy takie cos bedzie funkcjonalne?

**Comment by ctarx** [comment]
Czyli używać $ mówiąc do kogoś (z zadanym przymiotnikiem)? 
Myślę, że jest to jakieś rozwiązanie i lepsze to niż cuda w stylu 

> DoDzieckaCoJest.

**Comment by tjurczyk** [comment]
Dwie spacje to separator:

```
p do mieszczanina  witam cie towarzyszu
"do mieszczanina WitamCieTowarzyszu"

Mowisz do szpakowatego zrezygnowanego mieszczanina: WitamCieTowarzyszu
```

Pomoedzy `do mieszczanina` a `witam cie towarzyszu` sa dwie space. W ten sposob oddzieli do kogos a faktyczna mowe. W 3.11.
