### ISSUE TITLE
Minimalne postępy liczone jako 1

### ISSUE THREAD

**Issue by Nookie87** [tjurczyk/arkadia-skrypty#339]
Poczyniles minimalne [1/16] postepy, od momentu kiedy wszedles do gry.

Czy można zmienić liczenie postepów, tak aby dopiero od nieznacznym był liczone?

Poczyniles minimalne [0/15] postepy, od momentu kiedy wszedles do gry.
Poczyniles nieznaczne [1/15] postepy, od momentu kiedy wszedles do gry.
itp

**Comment by tjurczyk** [comment]
Dodane w 3.11.
