### ISSUE TITLE
Komendy przed lub po wykonaniu ruchu zintegrowane z mapperem.

### ISSUE THREAD

**Issue by ssnakey** [tjurczyk/arkadia-skrypty#34]
Na bagnach pustyniach czy lasach, albo w innych miejscach przydalaby sie mozliwosc
zastapienia kierunkow rozy wiatrow, kierunkami rozy wiatrow poprzedzonymi jakas komenda (lub komendami wystepujacymi po tych kierunkach) mogla by to byc dowolna komenda definiowana przez uzytkownika.

W momencie kiedy wejde na lokacje lezaca w moim zainteresowaniu np pierwsza lokacja pustyni, bagien, lasu. I tam klepie alias:

aliasnr1 "/rozazmiana_przed /rozazmiana_po"
dodaje do mapy znacznik i pyta czy od tego miejsca na mapie w ktorym aktualnie sie znajduje ma przed kierunkiem (lub po) wstawic jakies komendy a jesli tak to jakie np (przetnij linke, sprawdz kierunek, przetnij rzemien itd) i zapisywal ta informacje gdzies zeby tej czynnosci za kazdym razem nie powtarzac tylko poprostu gdy kazdym nastepnym razem wejde na ta lokacje skrypt bedzie wiedzial ze od tego miejsca ma zmienic kierunki z rozy az do chwili gdy trafi na "znacznik" z aliasa ponizej.

aliasrnr2 "/rozanormal"
dodaje do mapy znacznik i  przywraca kierunki z rozy wiatrow do domyslnych ustawien od momentu wejscia na lokacje na ktorej ten alias  zostal wywolany.

**Comment by ftpd** [comment]
W sumie to zdublowałem to w https://github.com/tjurczyk/arkadia-skrypty/issues/41, bo zatytułowałeś ticket tak, że nie idzie się skapnąć, o co chodzi.

**Comment by tjurczyk** [comment]
Od 2.18.
