### ISSUE TITLE
atakowanie z binda

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#342]
-- Atakowanie osoby z bindow
scripts.keybind.configuration.attack_bind_obj.modifier = {}
scripts.keybind.configuration.attack_bind_obj.key = "F1"

Atak z F1 nie dziala wyskakuje komunikat " nie widze takiej osoby" gdy wrog wchodzi na lokacje.

**Comment by tjurczyk** [comment]
Rozwiazane w 3.9a
