### ISSUE TITLE
amap.shorten_exits - popsute

### ISSUE THREAD

**Issue by baranno** [tjurczyk/arkadia-skrypty#344]
w kodzie triggerow od wyjsc:

```
if amap.shorten_exits then
  selectCurrentLine()
  deleteLine()
  local str = "\n-----:"

  for i, dir in pairs(dirs) do
    str = str .. " " .. string.upper(dir)
  end
  str = str .. "\n"

  cecho("<orange>" .. str)
end

```

dirs zawiera teraz slownik nazwawyjscia-true/false

a wiec przekazywana jest wartosc true lub false do upper

powinno byc tak:
```
if amap.shorten_exits then
  selectCurrentLine()
  deleteLine()
  local str = "\n-----:"

  for i, dir in pairs(dirs) do
    str = str .. " " .. string.upper(i)
  end
  str = str .. "\n"

  cecho("<orange>" .. str)
end
```

**Comment by ctarx** [comment]
Niestety, podane rozwiązanie nie naprawia wszędzie tego błędu i powstają przykładowo takie wyjscia:
```
Pustkowia.
-----: 1 E W
```

**Comment by tjurczyk** [comment]
@ctarx mozesz podac te testowe lokacje? Przyda sie gdy bede to poprawial aby przetestowac.

**Comment by ctarx** [comment]
Teraz to dziwnie się zrobiło po 3.9.a

Przykładowo:
```
Tawerna u Grubego Mario.
Ogromny gruby mezczyzna (Mario, NPC).
```
i nie pokazuje żadnych wyjść, a także zniknęła róża kierunków.

ale na lokacji **6398**
róża pokazuje kierunek, ale brak wyjść w opisie 
```
 Niewielka polanka wsrod gestych krzakow.
```
No i teraz przykładowa lokacja gdzie były cyfry zamiast kierunków:
lokacja **13639**
```
Droga Czaszek.
-----: N NW W SW S SE E NE
```
są kierunki w opisie, ale róża kierunków nic nie wyświetla.

**Comment by tjurczyk** [comment]
Powinno dzialac w 3.11, poprawilem wszystkie triggery rysujace skrocone kierunki. Jesli bedzie jakis problem, zaloz nowy issue.
