### ISSUE TITLE
Spece glada

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#346]
[GLA 2/7] [GLA 2/7] Ciosem czarnoblekitnego pulsujacego morgensterna w nogi XXX zadaje ci nieduza
rane i uderzeniem okraglej wzmacnianej tarczy odpycha w tyl.

to juz kiedys bylo naprawione jak i u barba  to dublowanie i tez wyszlo na nowo po ostatniej aktualce.

**Comment by tjurczyk** [comment]
Poprawione w 3.11.
