### ISSUE TITLE
Brakujacy bloker plywania

### ISSUE THREAD

**Issue by filipbober** [tjurczyk/arkadia-skrypty#347]
Bloker:
`Nie masz sil plynac.`

**Comment by tjurczyk** [comment]
Czy jesli kliknie sie kierunek nieistniejacy na mapie to tez wyskoczy ten tekst?

**Comment by tjurczyk** [comment]
@filipbober zamykam, gdyz nie otrzymalem odpowiedzi. Dowiedz sie prosze, czy jak klikniesz cokolwiek to tez wyskoczy ten tekst. To jest istotne w blokerach.
Jesli nie, zaloz prosze issue z odpowiednia informacja.
