### ISSUE TITLE
Strzałki przy tropieniu.

### ISSUE THREAD

**Issue by jsenny** [tjurczyk/arkadia-skrypty#349]
Strzałki pokazujące trop jak przy pogoni (arrow). Jeżeli trop pewny niebieska strzałka, jeżeli niepewny żółta.

**Comment by jsenny** [comment]
Nie znajdujesz zadnych sladow.
Jestes w stanie wyroznic kilka sladow na ziemi. Najswiezsze prowadza prawdopodobnie na {@kierunek}
Jestes w stanie wyroznic kilka sladow na ziemi. Najswiezsze prowadza na {@kierunek}

**Comment by tjurczyk** [comment]
Dodam przy nastepnej wersji

**Comment by tjurczyk** [comment]
Dodane w 3.11.
