### ISSUE TITLE
Blokowanie ( pilne)

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#35]
Mam prosbe przy wyroznieniu bloka by dodac
Dodac:

=====================

XXXXXXXXXXXXXXXXXXXXXX

Blok

XXXXXXXXXXXXXXXXXXXXXXX

====================

Mamy ostatnio walki po 20/25 osob
I nawet opcje opisywanie swojej wlaczone nie wiele daje.
A idzie masa blokow na wejscie potrafi leciec i szesc siedem blokow na raz na rozne osoby
Ginie to w tlumie
W ciagu 2 sekund
Juz masz przewiniety caly ekran.

Do tego prosilbym o dodanie dzwieku na blok w nasza osobe inny niz ten co jest na dylizanse.

**Comment by ftpd** [comment]
Ale wiesz, że to wszystko możesz sobie dodać samemu? O, na przykład tak: https://i.imgur.com/RLlqiLQ.png i potem wygląda to tak: https://i.imgur.com/OdRvDXH.png

**Comment by ftpd** [comment]
Duży -1 ode mnie, jestem za spójnością całości, a nie tu taki komunikat, tam taki.

**Comment by ftpd** [comment]
Zobacz, nawet Ci prościej napisałem:

raiseEvent("playBeep")
selectCurrentLine()
deleteLine()
cecho("\n<red>XXXXXXXXXXXXXXXXXXXX <white>---    WYTRACENIE    <red>--- XXXXXXXXXXXXXXXXXXXX\n")
cecho("<red>XXXXXXXXXXXXXXXXXXXX <white>---    WYTRACENIE    <red>--- XXXXXXXXXXXXXXXXXXXX\n")
cecho("<red>XXXXXXXXXXXXXXXXXXXX <white>---    WYTRACENIE    <red>--- XXXXXXXXXXXXXXXXXXXX\n\n")
cecho("<red>" .. matches[2] .. "\n")
resetFormat()
scripts.ui:info_action_update("WYTRACENIE")

**Comment by ssnakey** [comment]
Dokladnie dodaj sobie samemu, pozniej wszyscy musza wylaczac te pierdy bez znaczenia

**Comment by animal793** [comment]
Ej kurwa , wy tu nie jestescie zadna jebana komisja od decyzji co dodane lub poprawione bedzie badz nie.
Wypierdalac mi z mojego topiku.


Ja to zamieszczam dla Dz. a nie dla was.
