### ISSUE TITLE
Brakujace literowe znaczniki na mapie

### ISSUE THREAD

**Issue by filipbober** [tjurczyk/arkadia-skrypty#351]
Po aktualizacji do Mudleta 3.8.1 brakuje części literowych znaczników na mapie. Komenda `/zaladuj_mape` nie rozwiązuje problemu.

**Comment by tjurczyk** [comment]
Wyjasnilo sie cos w tym temacie? Czy najnowszy mudlet tez ma ten problem?

**Comment by filipbober** [comment]
Cały czas tak samo. W najnowszej wersji Mudleta i skryptów gdy wpiszę `/zaladuj_mape` po włączeniu klienta, ale przed zalogowaniem wydaje się być w porządku już po zalogowaniu, jeśli jednak w trakcie gry wpiszę `/zaladuj_mape` to znaczniki znikają i pojawiają sie dopiero na dosyć mocnym przybliżeniu.

**Comment by tjurczyk** [comment]
@filipbober Na mudlecie 3.13 i kwadratowych lokacjach dziala po zrobieniu `/zaladuj_mape`. Musimy pozostac na tym, gdyz jest to najwyrazniej spowodowane mudletem.
