### ISSUE TITLE
Mudlet 3.8.1 crash przy probie bindowania statkow / dylizansow

### ISSUE THREAD

**Issue by aprensivo** [tjurczyk/arkadia-skrypty#352]
Hej!
Siedze na Linuksie, distro: Linux Mint 18.3.
Zaktualizowalem skrytpy do 3.9, i od tego czasu uporczywie przy kazej okazji, gdy trigger probuje zaladowac mi binda do wsiadania na statek lub do dylizansu (gdy taki przybywa na lokacje), caly Mudlet robi natychmiastowy crash.
Deaktywacja katalogu triggerow skrypty_master3/skrypty/misc/ships umozliwia granie.

Edit: trigger na otrzymanie nowej pocztyrobi dokladnie to samo.

**Comment by aprensivo** [comment]
Trigger na nowa poczte powoduje dokladnie to samo.

**Comment by tjurczyk** [comment]
Hej,

niestety nie mam linuxa dlatego nie bede mial jak zreplikowac. Czy mozesz sprobowac zreplikowac?
Wpisz w linii komand:

`Masz nowa poczte od Ogra.`

i sprawdz czy za kazdym razem bedzie sie zwieszal. Zajrzyj tez do okna Debug i jesli pojawia sie tam cos przed zwisem, to przeslij prosze.

**Comment by aprensivo** [comment]
Wiesza sie za kazdym razem, w debugu nic nie ma :/
Dodatkowo, dzis okazalo sie, ze pekniecie broni poduje dokladnie to samo.
Jesli masz gdzies wersje skryptow online, mozesz mi wyslac prosze linka, sprawdze poprzednia paczke... Troche niebezpiecznie gra sie nie wiedzac, co powoduje te force exity...
Z gory dzieki!

**Comment by aprensivo** [comment]
yghhhh odkrylem, co sie dzieje. Nie wiem, czy zostawic to jako problem ze skryptami czy z moim setupem, wiec na razie nie zamkne tego tematu:

wyglada na to, ze kazdy skrypt probujacy wywloac event "playBeep" crashuje Mudleta. Jesli ze skryptu wywale wszystkie eventy z "playBeep", wszystko smiga (ale oczywiscie nie ma dzwieku).

Oczywiscie, katalog "sounds" z beep.wav siedzi, gdzie trzeba.

wrzuce to na forum, moze ktos da rade to rozwiazac...

**Comment by tjurczyk** [comment]
Dowiedzielismy sie czegos? Jesli nie to bedzie mozna zglosic na githubie Mudleta.

**Comment by aprensivo** [comment]
Hej, dowiedzielismy... Ponoc mudelt na Ubuntu nie gra dziekow. I koniec. Bug znany, ale chyba nikt sie tym za bardzo nie zajmuje: https://github.com/Mudlet/Mudlet/issues/511
Sa jakies obejscia, ale nie mam do nich cierpliwosci.
Ciekawostka - na poprzedniej wersji Minta mialem poprzedniego Mudleta, ze skryptami 3.8, nie mialem nawet katalogu z dzwiekami - no ale na byl na tyle laskawy, ze nie crashowal mi calego mudleta :)

Tak czy inaczej - watek zamykam, jako ze to nie problem ze skryptami.

Dzieki!
