### ISSUE TITLE
Brakuje blokera na pajakach przy Bodrog

### ISSUE THREAD

**Issue by filipbober** [tjurczyk/arkadia-skrypty#354]
Przy samodzielnym poruszaniu bloker działa.

Przy podążaniu za drużyną po takim komunikacie:
```
Probujesz sie ruszyc na polnoc, jednak pajecze sieci, w ktore sie w miedzyczasie
zaplatales, uniemozliwiaja ci to.
```
Kiedy drużyna ruszyła "dalej", mapper nas cofa do poprzedniej lokacji, więc lądujemy w zupełnie innym miejscu.

**Comment by tjurczyk** [comment]
Dodane od nastepnej wersji.
