### ISSUE TITLE
Pomysl na F2 - bind do przelamywania

### ISSUE THREAD

**Issue by Noisehammer** [tjurczyk/arkadia-skrypty#356]
Cześć 

używam bindu F2 gdy jestem w druzynie do przelamywania.
F2:
przestan kryc sie za zaslona
przelam obrone celu ataku
nazabij cel ataku

Sam dopisalem sobie do tego jeszcze:
rozkaz druzynie zaatakowac cel ataku

Ale pytanie takie - czy istnialaby mozliwosc, aby ten bind mial rozkazywanie badz nie, w zaleznosci od tego czy mam ustawione AW czy AWR  ?

Z gory dzieki

**Comment by tjurczyk** [comment]
Jasne, dobry pomysl.

**Comment by tjurczyk** [comment]
@Noisehammer czy to aby nie dziala w ten sposob? Sprawdzilem wlasnie co sie dzieje po nacisnieciu F2:

```
function callback_break_defense()
  sendAll("przestan kryc sie za zaslona", "przelam obrone celu ataku", true)
  expandAlias("/zz cel ataku", true)
end
```

`/zz <opis>` wywoluje funkcje `zab2(...)`

```
function ateam:zab2_func(desc)
  send(ateam:get_attack_string() .. desc, false)

  if table.size(ateam.team) > 1 and ateam.team[ateam.my_id] == "@" and ateam.attack_mode > 1 then
    send("wskaz " .. desc .. " jako cel ataku", false)
  
    if ateam.attack_mode > 2 then
      send("rozkaz druzynie zaatakowac " .. desc, false)
    end
  end
end
```

funkcja ta jest uzalezniona od `ateam.attack_mode`, ktory ma wartosc zalezna od AWR. Dziala to na tej samej zasadzie co `zab_func(...)`. Sprawdze jeszcze jak bede mial mozliwosc, ale to powinno juz dzialac.

**Comment by tjurczyk** [comment]
Zakladam, ze to dziala zgodnie z tym co opisalem powyzej. Jesli wciaz nie dziala to tak jak oczekujesz, zaloz prosze nowy issue.
