### ISSUE TITLE
Z okienka kondycji nie sa wysylane komendy zdefiniowane w pliku txt postaci

### ISSUE THREAD

**Issue by ssnakey** [tjurczyk/arkadia-skrypty#358]
przy kliku w okienku kondycji jest wysylana komenda "zabij" a nie komenda zdefiniowana w pliku txt dla postaci

**Comment by tjurczyk** [comment]
A jaki dokladnie element okna klikasz? Ustawilem 

```
ateam.attack_commands = {"gzzabij"}
```

I klikam w numerki wrogow, i wysylana jest poprawna komenda: `gzzabij <id>`.

**Comment by tjurczyk** [comment]
@ssnakey zamykam, bo nie otrzymalem odpowiedzi. Sprawdzilem wlasnie i w 3.10 ten problem nie wystepuje. Jesli wystepuje u ciebie, pokaz prosze kawalek pliku imie.txt i loga.
