### ISSUE TITLE
Kolory

### ISSUE THREAD

**Issue by Noisehammer** [tjurczyk/arkadia-skrypty#359]
Po ostatnich aktualizacjach niektóre kolorowanie tekstu nie działa.

Konkretnie, walka osób trzecich, wcześniej ustawiona na np. kolor CYAN, po aktualizacjach ostatnich ma kolor biały i w żaden sposób nie można tego zmienić.
Tak jakby skrypt blokował kolory arki.
Dodam, że ta koolorystyka wybierana jest / była z poziomu Mudleta (setting - color ).

Po powrocie do starszych ustawień, tekst kolorwany jest ponownie i wszystko działa

**Comment by tjurczyk** [comment]
Mozesz zrobic screenshoty i wkleic? Przed i po aktualizacji.

**Comment by tjurczyk** [comment]
Zamykam, bo nie otrzymalem odpowiedzi.
