### ISSUE TITLE
przejscia specjalne

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#36]
Jezeli przykladowo jest noc w gorach nie widac wyjsc specjalnych, dopiero gdy zapale lampe, pokazuja sie.

Tak nie powinno byc, olej moze sie skonczyc, jezeli noc tak dziala na mapper to i mgla czy sniezyca napewno tez.

przejscia specjalne kolo rozy musza sie wyswietlac bez wzgledu na warunki.
To co mialo byc usprawieniem takim nie jest to pewne.

=====
 ne
Gdzies w Gorach Imperium.
Wielki weszacy niedzwiedz.
 e
Gdzies w Gorach Imperium.
Maly gipsowy kamien.
 e
Gdzies w Gorach Imperium.

Chmury wciaz gruba warstwa zalegaja nad twoja glowa, na cale szczescie nie wydaja sie zapowiadac 
opadow.
s
Gdzies w Gorach Imperium.
Duza zwinna kozica i jasnobrazowa plocha kozica.
 se
Gdzies w Gorach Imperium.
Malutki diorytowy kamien.
 /zap
Zapalasz gornicza lampe.

Doliczyles sie trzech sztuk.
(skrypty): Butelki: masz 3 sztuk

Bierzesz pekata butelke oleju z otwartej skorzanej krasnoludzkiej torby.
 Dopelniasz zapalona gornicza lampe z pekatej butelki oleju.
 Zapalona gornicza lampa juz jest zapalona.
 zerknij
Gdzies w Gorach Imperium.
Sa tutaj dwa widoczne wyjscia: polnocny-zachod i poludniowy-zachod.
Malutki diorytowy kamien.
wejdz na gore
Zaczynasz wspinac sie na gore.

**Comment by tjurczyk** [comment]
To spróbuj pobiegać sobie po łąkach w Bretonii na poprzednim rysowaniu róży :)
Wcześniejszy sposób rysowania róży na pewno nie wróci.

**Comment by animal793** [comment]
nie mowie o powrocie do wczesniejszego... no ale nie powinno byc tak ze w nocy w gorach nie widac przejsc specjalnych... dochodzisz do lokacji z wejdz na gore i nie odpalisz binda na wspinanie poki lampy nie zapalisz.

Sprawdze jeszcze mgle i sniezyce bo moze sie okazac ze podczas jak one beda to wogole nie bedzie mozna korzystac z przejsc specjalnych bo ich mapper nie bedzie widzial.

**Comment by tjurczyk** [comment]
Hmm, specjalne powinny się pojawiać bez względu na normalne kierunki, jeśli się nie pojawiają to błąd.
Sprawdzę to.

**Comment by animal793** [comment]
Dziekuje tylko o to mi chodzi.

**Comment by tjurczyk** [comment]
Ok, od 2.17 poprawiona funkcjonalność róży, powinna działać znacznie lepiej.
