### ISSUE TITLE
klick na wlasny pasek kondycji

### ISSUE THREAD

**Issue by Walkir** [tjurczyk/arkadia-skrypty#361]
Taki pomysl by klikniecie na wlasny pasek kondycji automatycznie wysylalo rozkaz zasloniecia siebie.

**Comment by tjurczyk** [comment]
Wystarczy, ze klikniesz na puste pole przed swoim ID, wtedy wskazesz siebie jako cel obrony.
Wtedy jak klikniesz na zielonej strzalce, to wykona rozkaz zasloniecia ciebie.
