### ISSUE TITLE
Liczenie procentow treningowych

### ISSUE THREAD

**Issue by Roslinek** [tjurczyk/arkadia-skrypty#364]
Zeby zamiast takiego czegos:
trenuj
spec           5 miedziakow

bylo 
trenuj
spec (5%)     5 miedziakow

**Comment by tjurczyk** [comment]
To przydaloby sie zrobic do kazdej z umiejetnosci, a ceny sa chyba rozne? potrzebne bedzie sporo triggerow. Przede wszystkim potrzebne sa konkretne przeliczniki:

umiejetnosc trenowania -> x pieniedzy -> y%

Zorganizuj takie zestawienie i bedzie mozna to dodac.
