### ISSUE TITLE
Braki w repozytorium i na serwerze.

### ISSUE THREAD

**Issue by ftpd** [tjurczyk/arkadia-skrypty#365]
Hej,
robiłem ostatnio świeżą instalację na dwóch maszynach i stwierdzam, że:
1) w repo na githubie jest 3.8 - fajnie byłoby trzymać aktualną wersję i w 'packu' i tutaj, bo nowi ludzie mogą nie wiedzieć o 'packu' i klonować repozytorium;
2) nie działa /pobierz_mape - nie ma pliku map_master3.dat na arkadia.kamerdyner.net;
3) nie działa /pobierz_baze - nie ma pliku Database_people.db na arkadia.kamerdyner.net.

**Comment by tjurczyk** [comment]
Pobieranie bazy juz dziala:

```
/pobierz_baze
(skrypty): Baza pobrana, zrestartuj Mudleta
```

W mapie byl blad, ze trzeba bylo zrobic `/pobierz_mape`, i pozniej `/zaladuj_mape`, bo samo `/pobierz_mape` mialo literowke. Poprawione w 3.12.
