### ISSUE TITLE
Unifikacja /za /zas

### ISSUE THREAD

**Issue by filipbober** [tjurczyk/arkadia-skrypty#366]
Jako, że numerami oznaczani są wrogowie, a literami drużyna, wystarczyłaby jedna komenda, która z zależności czy mamy literę czy liczbę albo działa jak `zaslon kogos` albo jak `zaslon przed kims`.

**Comment by tjurczyk** [comment]
To nie bedzie mozliwe, bo w 3.12 wprowadzam opcjonalne numerowanie druzyny liczbami.
