### ISSUE TITLE
Ustawialny kolorek przy pokazywaniu postaci z bazy.

### ISSUE THREAD

**Issue by ftpd** [tjurczyk/arkadia-skrypty#367]
W tym momencie skrypty 'na siłę' pokazują postać z bazy na zółto, gildię na pomarańczowo. Fajnie byłoby, jakby było to ustawialne w imie.txt, jak różne inne kolorki.

Konkretnie chodzi o:
see_person_trigger, linie 64 i 69,
trigger_people, linia 9.

**Comment by tjurczyk** [comment]
Dodane w 3.10 w configu

```
scripts.people["name_color"] = "yellow"
scripts.people["guild_color"] = "dark_orange"
```
