### ISSUE TITLE
Baza

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#37]
/widziani  ( nie dzialaja)

Jezeli ktos mi kogos przedstawi nie zapisuje sie mi to w bazie.

Mam duzo osob przedstawionych a jak biore /przypomnij no to niestety lipa.

Tak samo skrypt wybiorczo dodaje sobie i aktualizuje tytuly danych osob.
Nie wiem w czym blad lezy 
ale na okolo 100 osob przedstawionych z titlami moja baza dodala sobie nie wiecej niz pare sztuk.

**Comment by tjurczyk** [comment]
Potrzebne konkrety + baza, które używasz. Jeśli zrobiłeś swoją bazę, coś może być zduplikowane, puste opisy itp. 

U mnie `/widziani` działa.
