### ISSUE TITLE
Hardcodowane stringi do bindów, które można zmienić w configu.

### ISSUE THREAD

**Issue by ftpd** [tjurczyk/arkadia-skrypty#378]
W kilku przypadkach mimo możliwości własnej konfiguracji binda, echo skryptów wywala zawsze to samo, wpisane po prostu na sztywno w kodzie. Znalazłem dwa takie przypadki:
scripts.inv.collect:killed_action() -> "ctrl+3 weź z ciała",
trigger 'przelamanie' -> "CTRL + 1: zabij cel ataku".

**Comment by tjurczyk** [comment]
Dzieki, poprawione w 3.10.

**Comment by ftpd** [comment]
Proszę o reopen, bo:
1) w scripts.inv.collect:team_killed_action() jest nadal hardcoded;
2) string wygląda brzydko (`[bind F2 wez z ciala`), brakuje nawiasu - mała rzecz, a cieszy ;-)
