### ISSUE TITLE
mapper podczas przemykania

### ISSUE THREAD

**Issue by pprraavv** [tjurczyk/arkadia-skrypty#38]
Przy próbie wymknięcia się z lokacji mapper czasem się gubi. Powtarzalna sytuacja, w której pojawia się błąd, to próba wymknięcia się z lokacji, na której nie można się dłużej ukrywać, przy czym wymknąc się trzeba w kierunku którego nie ma mapie. Brzmi dziwnie, wiec najlepiej zobrazuje to przykład.

- zerknij -> Ulica w poblizu kuzni (ID lokacji: 22949)
- przemknij e -> Przepierzone wnetrze kuzni. (...) Jest tu zbyt ciezko sie schowac, wiec jestes widoczny z powrotem. (ID lokacji: 22974)
- przemknij w -> Nie jestes w stanie wymknac sie stad niezauwazenie. (ID lokacji: 22974)
- przemkmnij e -> Nie jestes w stanie wymknac sie stad niezauwazenie. (ID lokacji: 22949)

Jak widać pierwsze przemknięcie w kierunku wyjścia zadziałało poprawnie (mapper się nie ruszył), ale drugie, w kierunku w którym wcale nie ma wyjścia, przemieściło mappera.

**Comment by tjurczyk** [comment]
Nie wiem czy będzie się dało z tym coś zrobić. Problem jest taki, że jak wydajesz polecenie "przemknij e" i nie ma lokacji na "e", to mapper nie dodaje nic do kolejki lokacji. Po pojawieniu się "Nie jestes w stanie...", mapper cofa się o lokację. Ale, że lokacja nie została dodana (bo na "e" nie ma żadnej) to wróci do lokacji przed kuźnią.

To chyba nie jest jakiś duży problem?

**Comment by pprraavv** [comment]
W pewnych sytuacjach to może być problem, ale skoro trudno to wyeliminować w mapperze, to może da się rozwiązać problem z innej strony? Czy komunikaty ujawniające postać typu:
- Jest tu zbyt ciezko sie schowac, wiec jestes widoczny z powrotem. 
- [Ktoś] ujawnia cię! (pisane z pamięci)
- ... (lista do uzupełnienia)

mogły by :
1. Być wyróżnione i sygnalizowane alertem (dość istotna informacja dla kogoś atakującego z ukrycia)
2. Przełączać tryb przemykania na normalne chodzenie (na pewno gdy włączone jest przemykam: ja, nie testowałem co w przypadku, gdy ustawione jest przemykam: ja+drużyna  prowadzący zostaje ujawniony, ale chyba i tak się nie da wtedy przemknąć z drużyną)

Pamiętam jak przemykając po Kreutzhoffen wpadłem na orków, którzy ujawnili mnie i zaatakowali. Zanim w potoku literek ogarnąłem, że nie mogę się wymknąć i wyłączyłem przemykanie, to padłem. :/

**Comment by ftpd** [comment]
+1 z przełączaniem. Ewentualnie duży warning, że nie można się przemknąć w walce. Komunikat to: "Nie mozesz tak po prostu wymknac sie z walki." przy ja i "Nie jestes dowodca zadnej druzyny." przy ja+d.

**Comment by ftpd** [comment]
Swoją drogą to powinien być bloker do mappera.

**Comment by tjurczyk** [comment]
@ftpd @pprraavv przygotujcie proszę listę tego, co brakuje i zróbcie w jednym, zbiorczym tickecie. Robię porządek w ticketach.
