### ISSUE TITLE
Blad na lokacji w opisie (od wersji 3.11)

### ISSUE THREAD

**Issue by Monolith18** [tjurczyk/arkadia-skrypty#383]
Blad sie robi przy przejsciu lokacji

dane z /lok
**> /lok
(mapper): ID lokacji: 5948
(mapper): Rejon lokacji: Polnocna Tilea
(mapper): Koordynaty lokacji: 30, 144, 0
(mapper): Waga lokacji: 1
(mapper): Wyjscia z lokacji: 
{
  east = 5949,
  north = 5842
}
(mapper): Wyjscia specjalne z lokacji: 
{}
(mapper): Nazwa lokacji: 5948**

po wejsciu na te lokacje obojetnie z ktorej strony wyswietla sie co nastepuje:

**Rozstaje.
Trakt wiedzie na polnoc i wschod. Mozna jednak z niego zejsc i udac sie na poludniowy-zachod.{
  e = true,
  sw = true,
  n = true
}**

w wersji skryptow 3.10 tego nie bylo
i wczesniejszych

i to samo na innej lokacji w poblizu
**/lok
(mapper): ID lokacji: 5866
(mapper): Rejon lokacji: Urbimo
(mapper): Koordynaty lokacji: 52, 41, 0
(mapper): Waga lokacji: 1
(mapper): Wyjscia z lokacji: 
{
  northwest = 5867,
  southeast = 5865
}
(mapper): Wyjscia specjalne z lokacji: 
{}
(mapper): Nazwa lokacji: 5866**

wyswietla sie:
**Gosciniec.
Otwarta kuta brama prowadzaca na polnocny-zachod.
Trakt wiedzie na poludniowy-wschod. Mozna jednak z niego zejsc i udac sie na polnocny-zachod.{
  nw = true,
  se = true
}**

i kolejna
**/lok
(mapper): ID lokacji: 5966
(mapper): Rejon lokacji: Polnocna Tilea
(mapper): Koordynaty lokacji: 66, 146, 0
(mapper): Waga lokacji: 1
(mapper): Wyjscia z lokacji: 
{
  northwest = 5965,
  south = 10774,
  southwest = 10771,
  west = 10770,
  east = 5967,
  north = 10957
}
(mapper): Wyjscia specjalne z lokacji: 
{}
(mapper): Nazwa lokacji: 5966**

**Gosciniec.
Trakt wiedzie na polnocny-zachod. Mozna jednak z niego zejsc i udac sie na wschod.{
  nw = true,
  e = true
}**

**Comment by Monolith18** [comment]
Moj Mudlet to 3.13.0, OS Linux, wersja skryptow 3.11, do wersji 3.10 tego bledu nie bylo

**Comment by Monolith18** [comment]
kolejne lokacje:
**> /lok
(mapper): ID lokacji: 7445
(mapper): Rejon lokacji: Reikland
(mapper): Koordynaty lokacji: 81, 68, 0
(mapper): Waga lokacji: 1
(mapper): Wyjscia z lokacji: 
{
  southwest = 7447,
  northwest = 7446,
  east = 7444
}
(mapper): Wyjscia specjalne z lokacji: 
{}
(mapper): Nazwa lokacji: 7445**

**Trakt Reiklandzki.
Trakt wiedzie na wschod i polnocny-zachod. Mozna jednak z niego zejsc i udac sie na poludniowy
-zachod.{
  e = true,
  sw = true,
  nw = true
}**

**Comment by Monolith18** [comment]
**Trakt Reiklandzki.
Trakt wiedzie na wschod i polnocny-zachod. Mozna jednak z niego zejsc i udac sie na poludniowy
-zachod.{
  e = true,
  sw = true,
  nw = true
}
Slup z tabliczka.
> /lok
(mapper): ID lokacji: 7430
(mapper): Rejon lokacji: Reikland
(mapper): Koordynaty lokacji: 93, 70, 0
(mapper): Waga lokacji: 1
(mapper): Wyjscia z lokacji: 
{
  southwest = 7432,
  northwest = 7431,
  east = 7429
}
(mapper): Wyjscia specjalne z lokacji: 
{}
(mapper): Nazwa lokacji: 7430**

**Comment by Monolith18** [comment]
**Trakt Reiklandzki.
Trakt wiedzie na poludniowy-wschod i polnocny-zachod. Mozna jednak z niego zejsc i udac sie na
polnocny-wschod.{
  ne = true,
  nw = true,
  se = true
}**

**/lok
(mapper): ID lokacji: 7411
(mapper): Rejon lokacji: Reikland
(mapper): Koordynaty lokacji: 105, 80, 0
(mapper): Waga lokacji: 1
(mapper): Wyjscia z lokacji: 
{
  northeast = 7412,
  northwest = 7424,
  southeast = 7410
}
(mapper): Wyjscia specjalne z lokacji: 
{}
(mapper): Nazwa lokacji: 7411**

**Comment by Monolith18** [comment]
Nie wiem czy dodawać więcej lokacji czy wystarczy te kilka jako przykład?

**Comment by tjurczyk** [comment]
Mozesz zrobic `/aktualizuj_skrypty`, powinno byc poprawione.
