### ISSUE TITLE
Wyszukiwarka ziół

### ISSUE THREAD

**Issue by DarkTriss** [tjurczyk/arkadia-skrypty#385]
/przeszukaj_ziola deliona
 Znalazlem nastepujace ziola: 

/przeszukaj_ziola zolty jasny kwiat
 Znalazlem nastepujace ziola: 
 (++) zolty jasny kwiat (deliona) -> zjedz: -zmc 

Po nazwach nie działa. Po opisach i sposobach użycia jak najbardziej. Według 
"/ziola" po nazwach też powinno.

Oraz dziekuję bardzo!

**Comment by tjurczyk** [comment]
Dzieki, poprawione w 3.12.

```
/przeszukaj_ziola deliona

 Znalazlem nastepujace ziola: 

 (++) zolty jasny kwiat (deliona) -> zjedz: -zmc 
```
