### ISSUE TITLE
spece goblinoidów

### ISSUE THREAD

**Issue by Walkir** [tjurczyk/arkadia-skrypty#389]
We wszystkich triggach z: ```skrypty -> ui -> color -> color_npc```
Trzebaby usunąć słowo 'goblina' ponieważ te same spece mają także orki, hobgobliny i inne goblinoidy, np:

```(^[ >]*W slepiach [a-z ]+ goblina pojawia sie nienawistny blysk, gdy zdecydowanym uderzeniem [a-z ]+ przecina powietrze tuz przed twoja glowa\.$)```
powinno być:
```(^[ >]*W slepiach [a-z ]+ pojawia sie nienawistny blysk, gdy zdecydowanym uderzeniem [a-z ]+ przecina powietrze tuz przed twoja glowa\.$)```

Tak samo w:
 ```skrypty -> ui -> gags -> delete -> delete_npc```

Można by też w sumie usunąć przedrostek 'gob' z ```local str_replace = "[gob 0/3] "```

**Comment by tjurczyk** [comment]
Poprawione w 3.12. Dzieki :)
