### ISSUE TITLE
Kompas

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#39]
Wczesniej bylo tak ze po wlaczeniu na pasku Kompasu od razu z automatu sprawdzal nam obecna lokacje by moc wykonac krok.

Teraz tego nie robi, trzeba najpierw sie ruszyc by zaczal sprawdzac.

Mozna powrocic do tego by po uruchomieniu na pasku od razu odpalap komende sprawdz kierunki?

**Comment by tjurczyk** [comment]
Dodane od 2.17.
