### ISSUE TITLE
Patterny do tropienia 

### ISSUE THREAD

**Issue by Roslinek** [tjurczyk/arkadia-skrypty#396]
Jestes w stanie wyroznic kilka sladow na ziemi. Najswiezsze zostaly pozostawione prawdopodobnie przez grupe czterech osob i prowadza na poludnie.

Jestes w stanie wyroznic kilka sladow na ziemi. Najswiezsze zostaly pozostawione prawdopodobnie przez grupe kilku osob i prowadza na wschod.

Jestes w stanie wyroznic kilka sladow na ziemi. Najswiezsze zostaly pozostawione prawdopodobnie przez ogra i prowadza na polnocny-wschod.

**Comment by tjurczyk** [comment]
Dodane w 3.12.
