### ISSUE TITLE
Za mało miejsca w "zabici"

### ISSUE THREAD

**Issue by Monolith18** [tjurczyk/arkadia-skrypty#398]
Jak liczba zabitych osiągnie wartości trzy cyfrowe problem z wyświetlaniem (brak miejsca). Parametr nie dostępny do ustawienia w imie.txt jedynie jest hardcoded w skryptach.

 name = "scripts.ui.footer_info_core_1",
     width=120,

Tam są odpowiednio core_1, core_2 do różnych wartości, nie tylko do liczby zabitych. Dobrze by było umożliwić zmianę wartości width do każdego core_n z imie.txt wedle osobistych preferencji.

**Comment by tjurczyk** [comment]
Zwiekszylem to do 130, powinno wystarczyc. Jesli bedzie za malo, zwieksze jeszcze bardziej. Nie chce tego dawac do imie.txt, bo jest to bardzo nisko poziomowa opcja ktora malo kto zmienia. Daj znac czy po 3.12 jest ok.
