### ISSUE TITLE
Opisy parowania z lewaka dla siebie

### ISSUE THREAD

**Issue by apolios** [tjurczyk/arkadia-skrypty#399]
Szlachetna stal dzierzonego przez ciebie zdobionego dlugiego lewaka spiewa dzwiecznie, gdy udaje ci
sie sparowac nadchodzacy cios .*

Wprawnie przyjmujesz cios .* na szeroki jelec swego zdobionego
dlugiego lewaka.

Blyskawicznie skladajac zastawe parujesz cios .* swym zdobionym
dlugim lewakiem.

Skladasz wprawnie zastawe, by sparowac cios .* swym zdobionym dlugim
lewakiem.

**Comment by tjurczyk** [comment]
Dodane w 3.12.
