### ISSUE TITLE
Zbieranie przez ctrl-3

### ISSUE THREAD

**Issue by Monolith18** [tjurczyk/arkadia-skrypty#400]
Aktualnie po zabiciu wroga keybind ctrl-3 zbiera z ciała ustawione rzeczy i wkłada je do pojemnika. Warto dodać swojego/swojej do kodu, aby uniknąć wkładania do nie swojego pojemnika o tej samej nazwie na lokacji.

**Comment by tjurczyk** [comment]
W 3.13 jest nowa konfiguracja pojemnikow.
