### ISSUE TITLE
Dodatki z innego repo

### ISSUE THREAD

**Issue by Monolith18** [tjurczyk/arkadia-skrypty#401]
Dołączenie do kodu dodatków z repo użytkownika "ardcore" ?

Oczywiście za zgodą każdej ze stron

**Comment by apolios** [comment]
Z poprawką, jeśli można, numeracji ocenianych postaci na zgodną z oknem kondycji "komenda: /pw".

**Comment by Monolith18** [comment]
To repo (https://github.com/ardcore/arkadia-skrypty-addons) ma kilka rzeczy do ogarnięcia.

**Comment by tjurczyk** [comment]
Dodane w 3.12.;

**Comment by ardcore** [comment]
Nieco post-factum, ale oczywiście :+1: ode mnie :)
