### ISSUE TITLE
Komenda po wykonaniu ruchu.

### ISSUE THREAD

**Issue by ftpd** [tjurczyk/arkadia-skrypty#41]
Fajnie byłoby mieć coś analogicznego do aktualnie działającego kompasu, tylko żeby user mógł na bieżąco definiować komendę. Włączanie/wyłączanie nadal na pasku, w miejscu 'Kompas'. U mnie to się nazywało /walkcmd, ale nazewnictwo pozostawiam Tobie ;-)

**Comment by tjurczyk** [comment]
Od 2.18 pre i post komendy.
