### ISSUE TITLE
Patterny w skryptach lampy nie uwzględniają pojemników o niestandardowych shortach

### ISSUE THREAD

**Issue by Senareil** [tjurczyk/arkadia-skrypty#416]
Skrypty lampy wywalają się, jeśli użyje się pojemników na olej innych niż "butelka oleju", ponieważ pattern pokrywa tylko "butelki". Nie jestem pewna, ile niestandardowych pojemników jest w świecie, ale na pewno w Scorcio są "butle oleju". Przydatna byłaby zmiana w patternach uwzględniająca tę różnicę.

**Comment by tjurczyk** [comment]
Dodane w 3.13.
