### ISSUE TITLE
Nowe (i poprawione stare) magiki.

### ISSUE THREAD

**Issue by ctarx** [tjurczyk/arkadia-skrypty#417]
Dodaję na prośbę Algornana:

scripts.magic_weapons = {
    ["polyskliwy smukly espadon"] = true,
    ["polyskliwym smuklym espadonem"] = true,
    ["polyskliwego smuklego espadona"] = true,
    ["ogromny ognisty trojzab"] = true,
    ["ogromnego ognistego trojzebu"] = true,
    ["ogromnym ognistym trojzebem"] = true,
    ["polprzezroczysty migotliwy mlot"] = true,
    ["polprzezroczystym migotliwym mlotem"] = true,
    ["polprzezroczystego migotliwego mlota"] = true,
    ["polprzezroczysty migotliwy topor"] = true,
    ["polprzezroczystym migotliwym toporem"] = true,
    ["polprzezroczystego migotliwego topora"] = true,
    ["polprzezroczysty migotliwy drag"] = true,
    ["polprzezroczystego migotliwego draga"] = true,
    ["polprzezroczystym migotliwym dragu"] = true,
    ["polprzezroczystym migotliwym dragiem"] = true,
    ["polprzezroczysty migotliwy miecz"] = true,
    ["polprzezroczystym migotliwym mieczem"] = true,
    ["polprzezroczystego migotliwego miecza"] = true,
    ["polprzezroczysta migotliwa maczuge"] = true,
    ["polprzezroczysta migotliwa maczuga"] = true,
    ["polprzezroczystej migotliwej maczugi"] = true,
    ["polprzezroczysty migotliwy sztylet"] = true,
    ["polprzezroczystym migotliwym sztyletem"] = true,
    ["polprzezroczystego migotliwego sztyletu"] = true,
    ["polprzezroczysta migotliwa wlocznie"] = true,
    ["polprzezroczysta migotliwa wlocznia"] = true,
    ["polprzezroczystej migotliwej wloczni"] = true,
    ["opalizujacy runiczny topor obosieczny"] = true,
    ["opalizujacym runicznym toporem obosiecznym"] = true,
    ["opalizujacego runicznego topora obosiecznego"] = true,
    ["adamantytowy mlot bojowy"] = true,
    ["adamantytowym mlotem bojowym"] = true,
    ["adamantytowego mlota bojowego"] = true,
    ["misterny obosieczny topor"] = true,
    ["misternym obosiecznym toporem"] = true,
    ["misternego obosiecznego topora"] = true,
    ["kosciany kilof"] = true,
    ["koscianym kilofem"] = true,
    ["koscianego kilofa"] = true,
    ["srebrzysta kosa bojowa"] = true,
    ["srebrzysta kose bojowa"] = true,
    ["srebrzystej kosy bojowej"] = true,
    ["czarnoblekitny pulsujacy morgenstern"] = true,
    ["czarnoblekitnym pulsujacym morgensternem"] = true,
    ["czarnoblekitnego pulsujacego morgensterna"] = true,
    ["masywny wyszczerbiony tasak"] = true,
    ["masywnym wyszczerbionym tasakiem"] = true,
    ["masywnego wyszczerbionego tasaka"] = true,
    ["masywnym wyszczerbionym tasaku"] = true,
    ["azurowy koscistobialy amulet"] = true,
    ["niewielki zmatowialy pierscien"] = true,
    ["niebieskawa zdobiona bulawa"] = true,
    ["niebieskawa zdobiona bulawe"] = true,
    ["niebieskawej zdobionej bulawy"] = true,
    ["iskrzaca zdobiona bulawe"] = true,
    ["iskrzaca zdobiona bulawa"] = true,
    ["iskrzacej zdobionej bulawy"] = true,
    ["ciezki krwisty amulet"] = true,
    ["szkarlatny ciernisty pierscien"] = true,
    ["dlugi runiczny korbacz"] = true,
    ["dlugim runicznym korbaczem"] = true,
    ["dlugiego runicznego korbacza"] = true,
    ["blekitno-srebrna herbowa tarcza"] = true,
    ["blekitno-srebrna herbowa tarcze"] = true,
    ["blekitno-srebrnej herbowej tarczy"] = true,
    ["zdobiony jasniejacy mlot bojowy"] = true,
    ["zdobionym jasniejacym mlotem bojowym"] = true,
    ["zdobionego jasniejacego mlota bojowego"] = true,
    ["zdobiony dlugi lewak"] = true,
    ["zdobionym dlugim lewakiem"] = true,
    ["zdobionego dlugiego lewaka"] = true,
    ["upiorny ciemny mlot bojowy"] = true,
    ["upiornym ciemnym mlotem bojowym"] = true,
    ["upiornego ciemnego mlota bojowego"] = true,
    ["kruczoczarny misterny miecz"] = true,
    ["kruczoczarnym misternym mieczem"] = true,
    ["kruczoczarnego misternego miecza"] = true,
    ["antyczny zdobiony sztylet"] = true,
    ["antycznym zdobionym sztyletem"] = true,
    ["antycznego zdobionego sztyletu"] = true,
    ["smukly zmiennoksztaltny miecz"] = true,
    ["smuklym zmiennoksztaltnym mieczem"] = true,
    ["smuklego zmiennoksztaltnego miecza"] = true,
    ["smukly demoniczny miecz"] = true,
    ["smuklym demonicznym mieczem"] = true,
    ["smuklego demonicznego miecza"] = true,
    ["gigantyczny granitowy mlot"] = true,
    ["gigantycznym granitowy mlotem"] = true,
    ["gigantycznego granitowego mlota"] = true,
    ["jasniejacy zdobiony jatagan"] = true,
    ["jasniejacym zdobionym jataganem"] = true,
    ["jasniejacego zdobionego jatagana"] = true,
    ["poszczerbiony obureczny miecz"] = true,
    ["poszczerbionym oburecznym mieczem"] = true,
    ["poszczerbionego oburecznego miecza"] = true,
    ["kunsztowny mithrylowy topor bojowy"] = true,
    ["kunsztownym mithrylowym toporem bojowym"] = true,
    ["kunsztownego mithrylowego topora bojowego"] = true,
    ["krysztalowy dwureczny korbacz"] = true,
    ["krysztalowym dwurecznym korbaczem"] = true,
    ["krysztalowego dwurecznego korbacza"] = true,
    ["krysztalowy swietlisty korbacz"] = true,
    ["krysztalowym swietlistym korbaczem"] = true,
    ["krysztalowego swietlistego korbacza"] = true,
    ["waski kunsztowny sihill"] = true,
    ["waskim kunsztownym sihillem"] = true,
    ["waskiego kunsztownego sihilla"] = true,
    ["czarny zdobiony amulet"] = true,
    ["snieznobialy lsniacy sztylet"] = true,
    ["snieznobialym lsniacym sztyletem"] = true,
    ["snieznobialego lsniacego sztyletu"] = true,
    ["lodowy lsniacy sztylet"] = true,
    ["lodowym lsniacym sztyletem"] = true,
    ["lodowego lsniacego sztyletu"] = true,
    ["lsniaca plomienista tarcza"] = true,
    ["lsniacej plomienistej tarczy"] = true,
    ["lsniaca plomienista tarcze"] = true,
    ["gruba czarna opaska"] = true,
    ["gruba czarna opaske z kolcami"] = true,
    ["lsniacy krysztalowy wisior"] = true,
    ["szmaragdowozielony misterny plaszcz"] = true,
    ["lekka lsniaca para bransolet"] = true,
    ["lekka lsniaca bransoleta"] = true,
    ["lekka lsniaca bransolete"] = true,
    ["masywny oksydowany pas"] = true,
    ["masywny amulet z czarnym opalem"] = true,
    ["szkarlatny dlugi talwar"] = true,
    ["szkarlatnego dlugiego talwara"] = true,
    ["szkarlatnym dlugim talwarem"] = true,
    ["gorejacy dlugi talwar"] = true,
    ["gorejacy dlugi talwar"] = true,
    ["gorejacy dlugi talwar"] = true,
    ["gorejacym dlugim talwarem"] = true,
    ["gorejacego dlugiego talwara"] = true,
    ["starozytna zbroja plytowa pokryta runami"] = true,
    ["starozytna runiczna zbroja plytowa"] = true,
    ["starozytna runiczna zbroje plytowa"] = true,
    ["starozytnej runicznej zbroi plytowej"] = true,
    ["ciemna owalna maska"] = true,
    ["adamantytowa szpiczasta partyzana"] = true,
    ["adamantytowa szpiczasta partyzane"] = true,
    ["adamantytowej szpiczastej partyzany"] = true,
    ["mithrylowy lsniacy amulet"] = true,
    ["ornamentowany kruczoczarny helm wielki"] = true,
    ["snieznobiala luskowa kolczuga"] = true,
    ["snieznobialej luskowej kolczugi"] = true,
    ["snieznobiala luskowa kolczuge"] = true,
    ["niewielka dziesiecioramienna gwiazda z mosiadzu"] = true,
    ["niewielka dziesiecioramienna gwiazde z mosiadzu"] = true,
    ["niewielka dziesiecioramienna gwiazdy z mosiadzu"] = true,
    ["niepozorny barwny pierscien"] = true,
    ["plytach twojego starozytnego pancerza"] = true,
    ["plytach jego starozytnego pancerza"] = true,
    ["plytach jej starozytnego pancerza"] = true,
    ["bialoblekitna smocza zbroja"] = true,
    ["bialoblekitna smocza zbroje"] = true,
    ["snieznobialy lsniacy pancerz"] = true,
    ["snieznobialego lsniacego pancerza"] = true,
    ["snieznobialym lsniacym pancerzem"] = true,
    ["strzelisty zlocisty helm"] = true,
    ["strzelistym zlocistym helmem"] = true,
    ["gruby zlocisty pierscien z hiacyntem"] = true,
    ["grubego zlocistego pierscienia z hiacyntem"] = true,
    ["grubym zlocistym pierscieniem z hiacyntem"] = true,
    ["szmaragdowozielony misterny plaszcz"] = true,
    ["szmaragdowozielonym misternym plaszczem"] = true,
    ["szmaragdowozielonego misternego plaszcza"] = true,
    ["szkarlatna rogata tarcza"] = true,
    ["szkarlatna rogata tarcze"] = true,
    ["szkarlatnej rogatej tarczy"] = true,
    ["mithrylowa mahakamska kolczuga"] = true,
    ["mithrylowa mahakamska kolczuge"] = true,
    ["mithrylowej mahakamskiej kolczudze"] = true,
    ["szara wygodna para butow"] = true,
    ["szara wygodna pare butow"] = true,
    ["szarej wygodnej pary butow"] = true,
    ["pozlacane okulary z niebieskawych szkielek"] = true,
    ["czarny blyszczacy kolczyk"] = true,
    ["skrzydlata pare nareczakow"] = true,
    ["mosiezna duza broszka w ksztalcie liscia debu"] = true,
    ["niewielki krwawnikowy pierscien"] = true,
    ["polyskliwe smukle espadony"] = true,
    ["ogromne ogniste trojzeby"] = true,
    ["polprzezroczyste migotliwe dragi"] = true,
    ["opalizujace runiczne topory obosieczne"] = true,
    ["adamantytowe mloty bojowe"] = true,
    ["misterne obosieczne topory"] = true,
    ["kosciane kilofy"] = true,
    ["srebrzyste kosy bojowe"] = true,
    ["czarnoblekitne pulsujace morgensterny"] = true,
    ["masywne wyszczerbione tasaki"] = true,
    ["azurowe koscistobiale amulety"] = true,
    ["niewielkie zmatowiale pierscienie"] = true,
    ["niebieskawe zdobione bulawy"] = true,
    ["iskrzace zdobione bulawy"] = true,
    ["ciezkie krwiste amulety"] = true,
    ["dlugie runiczne korbacze"] = true,
    ["blekitno-srebrne herbowe tarcze"] = true,
    ["zdobione jasniejace mloty bojowe"] = true,
    ["zdobione dlugie lewaki"] = true,
    ["upiorne ciemne mloty bojowe"] = true,
    ["kruczoczarne misterne miecze"] = true,
    ["antyczne zdobione sztylety"] = true,
    ["smukle zmiennoksztaltne miecze"] = true,
    ["smukle demoniczne miecze"] = true,
    ["gigantyczne granitowe mloty"] = true,
    ["jasniejace zdobione jatagany"] = true,
    ["poszczerbione obureczne miecze"] = true,
    ["kunsztowne mithrylowe topory bojowe"] = true,
    ["krysztalowe dwureczne korbacze"] = true,
    ["waskie kunsztowne sihille"] = true,
    ["czarne zdobione amulety"] = true,
    ["snieznobiale lsniace sztylety"] = true,
    ["lodowe lsniace sztylety"] = true,
    ["lsniace plomieniste tarcze"] = true,
    ["grube czarne opaski"] = true,
    ["lsniace krysztalowe wisiory"] = true,
    ["szmaragdowozielone misterne plaszcze"] = true,
    ["lekkie lsniace pary bransolet"] = true,
    ["masywne oksydowane pasy"] = true,
    ["masywne amulety z czarnym opalem"] = true,
    ["szkarlatne dlugie talwary"] = true,
    ["gorejace dlugie talwary"] = true,
    ["starozytne zbroje plytowe pokryte runami"] = true,
    ["starozytne runiczne zbroje plytowe"] = true,
    ["ciemne owalne maski"] = true,
    ["adamantytowe szpiczaste partyzany"] = true,
    ["mithrylowe lsniace amulety"] = true,
    ["ornamentowane kruczoczarne helmy wielke"] = true,
    ["snieznobiale luskowe kolczugi"] = true,
    ["niewielkie dziesiecioramienne gwiazdy z mosiadzu"] = true,
    ["niepozorne barwne pierscienie"] = true,
    ["bialoblekitne smocze zbroje"] = true,
    ["snieznobiale lsniace pancerze"] = true,
    ["strzeliste zlociste helmy"] = true,
    ["grube zlociste pierscienie z hiacyntem"] = true,
    ["szmaragdowozielone misterne plaszcze"] = true,
    ["szkarlatne rogate tarcze"] = true,
    ["czarny zdobiony helm"] = true,
    ["czarnym zdobionym helmem"] = true,
    ["kunsztowny lekki pancerz"] = true,
    ["kunsztownego lekkiego pancerza"] = true,
    ["kunsztownym lekkim pancerzem"] = true,
    ["szylkretowy falisty sztylet"] = true,
    ["szylkretowym falistym sztyletem"] = true,
   ["szylkretowego falistego sztyletu"] = true,
   ["egzotyczny jadeitowy palasz"] = true,
   ["egzotycznym jadeitowym palaszem"] = true,
   ["egzotyczne jadeitowe palasze"] = true,
   ["lodowata dluga maczuga"] = true,
   ["lodowate dlugie maczugi"] = true,
   ["lodowatej dlugiej maczugi"] = true,
   ["lodowata dluga maczuga"] = true,
   ["archaiczny zdobiony topor"] = true,
   ["archaiczne zdobione topory"] = true,
   ["archaicznego zdobionego topora"] = true,
   ["archaicznym zdobionym toporem"] = true,
   ["niematerialny ulotny szamszir"] = true,
   ["niematerialne ulotne szamsziry"] = true,
   ["niematerialnego ulotnego szamszira"] = true,
   ["niematerialnym ulotnym szamszirem"] = true,
   ["ciernista kobaltowa halabarda"] = true,
   ["cierniste kobaltowe halabardy"] = true,
   ["ciernista kobaltowa halabarde"] = true,
   ["ciernistej kobaltowej halabardy"] = true,
   ["ciemnogranatowy smukly helm"] = true,
   ["ciemnogranatowym smuklym helmem"] = true,
   ["ciemnogranatowe smukle helmy"] = true,
   ["misterna spizowa pawez"] = true,
   ["misterne spizowe paweze"] = true,
   ["misterna spizowa paweza"] = true,
   ["rezonujace krysztalowe mloty"] = true,
   ["rezonujacy krysztalowy mlot"] = true,
   ["rezonujacego krysztalowego mlota"] = true,
   ["rezonujacym krysztalowym mlotem"] = true,
   ["asymetryczne wulkaniczne mloty"] = true,
   ["asymetryczny wulkaniczny mlot"] = true,
   ["asymetrycznego wulkanicznego mlota"] = true,
   ["asymetrycznym wulkanicznym mlotem"] = true,		
		
}

**Comment by tjurczyk** [comment]
3.13.
