### ISSUE TITLE
Mapper Wezendorf

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#42]
Bind kierunkowy nie dziala wykonuje tylko przejdz przez wodospad nie wchodzac do wody.

> /lok
(mapper): ID lokacji: 6673
(mapper): Rejon lokacji: Okolice KZ
(mapper): Koordynaty lokacji: 125, 62, 0
(mapper): Waga lokacji: 1
(mapper): Wyjscia z lokacji: 
{
  east = 6674,
  west = 6672
}
(mapper): Wyjscia specjalne z lokacji: 
{
  ["przejdz przez wodospad"] = 14812
}
(mapper): Bindy kierunkowe: 
{
  north = "wejdz do wody#przejdz przez wodospad"

**Comment by ftpd** [comment]
Było w https://github.com/tjurczyk/arkadia-skrypty/issues/3. @tjurczyk czy to na 100% poprawione wtedy było?

**Comment by tjurczyk** [comment]
@animal793 

To jest zrobione teraz odrobinę inaczej. Naciskasz albo "n" i mapper wykona Ci "wejdz do wody;przejdz przez wodospad" i przeskoczy. Albo robisz ręcznie dwie komendy. W sensie, binda "ctrl-p" nie nalezy już tam używać tylko "n".

**Comment by ftpd** [comment]
To może warto usunąc go z mapy, żeby nie wyświetlał i nie robił konfuzji?
Chociaż słabo, że C-p nie zadziała, jakoś nigdy nie lubiłem iść kierunkami tam, gdzie przejścia specjalne.

**Comment by animal793** [comment]
tak, dzis tam bylem i zawsze uzywalem ctrl + p. Teraz go nie mialem podpietego do lokacji i sam recznie ponownie dodalem go.

Jakby byl na lokacji ctrl + P to nawet bym nie pisal ze cos jest nie tak.

**Comment by tjurczyk** [comment]
Dodałem z powrotem bind na ctrl+p.
