### ISSUE TITLE
Automatyczne puszczanie zasłon

### ISSUE THREAD

**Issue by Monolith18** [tjurczyk/arkadia-skrypty#426]
Czy ta opcja możliwa do włączenia w imię.txt jest zgodna z punktem regulaminu traktującym o świadomym wysyłaniu komend do MUD'a?
IMHO wydaję mi się, że nie.
Pod dyskusję i ewentualne usunięcie nieregulaminowej funkcji.

**Comment by tjurczyk** [comment]
Tak, jest zgodna bo to zwykla komenda ktora jest dodawana do binda zaslony. Czyli zamiast wykonywac `zaslon xxx` po wpisaniu aliasa wykonywane jest `zaslon xxx;przestan zaslaniac`. Nic nie dzieje sie bez twojej kontroli, zadne puszczanie zaslon nie jest wysylane samoistnie przez skrypty.
