### ISSUE TITLE
Wkładanie rzeczy do pojemników

### ISSUE THREAD

**Issue by Monolith18** [tjurczyk/arkadia-skrypty#427]
Dodatkowo do issue #423 
Dołożyć "swojej/swojego" celem wyeliminowania wkładania rzeczy do cudzego pojemnika o takim samym shorcie, ale z niższym numerem na lokacji.
Dodatkowo co poruszone zostało na discordzie, dołożenie możliwości definiowania cech pojemnika np. "bordowe" etc.

**Comment by tjurczyk** [comment]
http://arkadia.kamerdyner.net/pojemniki.html
Dodane w 3.13.
