### ISSUE TITLE
Błedne liczenie zabitych

### ISSUE THREAD

**Issue by Monolith18** [tjurczyk/arkadia-skrypty#428]
Jeśli szefowie snotlingów (wszyscy) i herszt goblinów (Skraśnik) są przedstawieni graczowi z imienia, skrypt nie dolicza +1 do licznika zabitych po zabiciu NPCa. Jeśli wyżej wymienione moby są anonimowe jako snotling/goblin licznik zlicza poprawnie.

**Comment by tjurczyk** [comment]
Poprawione w 3.13.
