### ISSUE TITLE
Brakuje /wdp /wzp w 3.14

### ISSUE THREAD

**Issue by Monolith18** [tjurczyk/arkadia-skrypty#431]
Brakujące aliasy w 3.13

/wdp - wkładanie rzeczy po przecinku do pojemnika other

/wzp - wyjmowanie rzeczy po przecinku z pojemnika other

Aliasy zaczerpnięte z repo ardcore, pominięte w 3.13

**Comment by Monolith18** [comment]
w 3.14 również brakuje

**Comment by tjurczyk** [comment]
Dodane w 3.15.
