### ISSUE TITLE
Błędne bindowanie wrogów

### ISSUE THREAD

**Issue by Monolith18** [tjurczyk/arkadia-skrypty#432]
Jeśli ustawimy w imie.txt wroga np.: "Slav" , to każde imię zawierające "slav" będzie wrogiem.

**Comment by tjurczyk** [comment]
Faktycznie, w budowaniu bindow na wrogow po imieniach bylo zrobione nastepujace zapytanie do bazy:

```
local results = db:fetch(scripts.people.db.people, db:like(scripts.people.db.people.name, "%"..v.."%"))
```

i teraz ta czesc:
```
"%"..v.."%"
```

mogla powodowac, ze kiedy definiowalo sie `slav`, to wracal `slav` i `miroslav`. Zmienilem to na:

```
local results = db:fetch(scripts.people.db.people, db:like(scripts.people.db.people.name, v))
```

czyli bedzie teraz wyszukiwal dokladnie osob o imionach zdefiniowanych w pliku imie.txt. Zmiana bedzie w 3.14. Dzieki za wylapanie!.
