### ISSUE TITLE
Definiowanie większej ilości pojemników na broń

### ISSUE THREAD

**Issue by Senareil** [tjurczyk/arkadia-skrypty#434]
Ostatnie zmiany w pojemnikach wyglądają całkiem obiecująco! Chętnie widziałabym pójście do przodu i zaimplementowanie podobnego systemu w pojemnikach na broń. Chciałabym móc ustawić więcej niż trzy "sloty" na broń - większość zawodów ma więcej rodzajów broni, a niektóre do tego tarczownictwo. W momencie gdy jeden slot jest zabierany przez tarczę, organizowanie się na dwóch pojemnikach to trochę mało. A czasem jeszcze przydałby się sztylet...

**Comment by tjurczyk** [comment]
W wersji 3.14 jest to przerobione: http://arkadia.kamerdyner.net/bronie.html
