### ISSUE TITLE
Dopisanie do listy magików

### ISSUE THREAD

**Issue by Duarus** [tjurczyk/arkadia-skrypty#437]
["zdobiona jasniejaca wlocznia"] = true,
["zdobiona jasniejaca wlocznie"] = true,
["zdobione jasniejace wlocznie"] = true,
["zdobionej jasniejacej wloczni"] = true,

["dluga krasnoludzka bajdane"] = true,
["dluga krasnoludzka bajdana"] = true,

["misterny snieznobialy harpun"] = true,
["misternego snieznobialego harpuna"] = true,
["misternym snieznobialym harpunem"] = true,
    ["misternym snieznobialym harpunie"] = true,   

 			["zielony luskowaty plaszcz"] = true,
    ["zielonym luskowatym plaszczem"] = true,
    ["zielonym luskowatym plaszczu"] = true,

**Comment by tjurczyk** [comment]
Dzieki wielki za podanie od razu przygotowanych do wklejenia! Dodane w 3.14.
