### ISSUE TITLE
Większa liczba obsługiwanych woreczków

### ISSUE THREAD

**Issue by Ichaero** [tjurczyk/arkadia-skrypty#438]
/ziola_buduj obsługuje do 20 woreczków. Zielarzom przydałaby się obsługa większej ilości.

**Comment by tjurczyk** [comment]
Dodalem do 40 w 3.14.
Jesli trzeba wiecej, prosilbym o znalezienie w skryptach `scripts.counted_string_to_int` i dodanie do wiekszej liczby, analogicznie jak jest w skryptach. Wtedy mozesz mi podeslac zmienione struktury i dodam w skryptach.
