### ISSUE TITLE
nowy magiczny amulet

### ISSUE THREAD

**Issue by Monolith18** [tjurczyk/arkadia-skrypty#440]
> odmien amulet
Azurowy polyskujacy amulet z wielobarwnego koralu odmienia sie nastepujaco:

  Mianownik: azurowy polyskujacy amulet z wielobarwnego koralu,
 Dopelniacz: azurowego polyskujacego amuletu z wielobarwnego koralu,
   Celownik: azurowemu polyskujacemu amuletowi z wielobarwnego koralu,
    Biernik: azurowy polyskujacy amulet z wielobarwnego koralu,
  Narzednik: azurowym polyskujacym amuletem z wielobarwnego koralu,
Miejscownik: azurowym polyskujacym amulecie z wielobarwnego koralu.

Rozpoznawane nazwy: amulet, naszyjnik, bizuteria, naszyjnik z wielobarwnego koralu i bizuteria z
wielobarwnego koralu.

**Comment by tjurczyk** [comment]
Dzieki, dodane w 3.14.
