### ISSUE TITLE
Odliczanie do lvl'a

### ISSUE THREAD

**Issue by Roslinek** [tjurczyk/arkadia-skrypty#441]
Mam taki kod:

```
CalkowiteDoLvlaZ = 1300

CalkowiteDoLvlaX = CalkowiteDoLvlaZ - CalkowiteDoLvla 

CalkowiteDoLvlaY = CalkowiteDoLvla / CalkowiteDoLvlaZ
CalkowiteDoLvlaY = CalkowiteDoLvlaY * 100
LEXPGag:setValue(CalkowiteDoLvlaY,CalkowiteDoLvlaZ)
CalkowiteDoLvlaY = string.cut(CalkowiteDoLvlaY, 5)

cecho("\n----------------------------------------------------------------")
cecho("\n ==> Masz juz okolo ".. CalkowiteDoLvlaY  .."% lvla i brakuje Ci "..CalkowiteDoLvlaX.." postepow do "..CalkowiteDoLvlaZ.."!\n")

```
OUTPUT:
==> Masz juz okolo 10% lvla i brakuje Ci 1170 postepow do 1300!

Potrzebuje by zmienna sum z twojego skryptu improve2 dala sie "wyciagnac", bez wywylywania calej tabelki postepow.

Na razie mam tak, ze:
```
    sum = sum + v["val"]
		CalkowiteDoLvla = sum
```

Ale pojawia mi sie cala tabelka jak chce ja wywolac lub policzyc,

Moglbys napisac skrypt np. improve3 gdzie liczy sama liczbe zdobytych postepow, a nie pokazuje tabelki?

|  WSZYSTKICH DO TEJ PORY: 139 postepow                   |

Chodzi mi o sama liczbe.

**Comment by tjurczyk** [comment]
W 3.14 bedziesz mial ja dostepna w `misc.lvl_calc.full_stat`.

<img width="965" alt="image" src="https://user-images.githubusercontent.com/1749428/70860966-48dfc980-1f28-11ea-95ff-62bf6972d843.png">
