### ISSUE TITLE
Za mało miejsca w 'Zabici'

### ISSUE THREAD

**Issue by Monolith18** [tjurczyk/arkadia-skrypty#442]
Informacja w pasku stanu na dole ekranu 'Zabici' ma za mało miejsca na liczby trzycyfrowe. Wartości xxx/xxx już się nie mieszczą poprawnie.

**Comment by tjurczyk** [comment]
@Monolith18 U mnie są, musisz dać więcej miejsca na tę sekcję UI.

<img width="1250" alt="image" src="https://user-images.githubusercontent.com/1749428/70860945-ebe41380-1f27-11ea-84a7-8db96b9012af.png">
