### ISSUE TITLE
Brak zmiany stanu broni

### ISSUE THREAD

**Issue by apolios** [tjurczyk/arkadia-skrypty#443]
`Bierzesz misterny obosieczny topor z otwartego malego kruczoczarnego plecaka.
Chwytasz stylisko misternego obosiecznego topora w garsc i wykonujesz nim kilka probnych wymachow,
oswajajac sie z nietypowym wywazeniem oreza.`

nie powoduje zmiany stanu `Bron `na `on`

**Comment by tjurczyk** [comment]
Dodane w 3.15.
