### ISSUE TITLE
Zdobiony zloty pierscien - magik do podswietlania

### ISSUE THREAD

**Issue by Monolith18** [tjurczyk/arkadia-skrypty#446]
Magiczny pierscien sie nie podswietla na czerwono. Odmiana jak ponizej:

> odmien pierscien
Zdobiony zloty pierscien odmienia sie nastepujaco:

  Mianownik: zdobiony zloty pierscien,
 Dopelniacz: zdobionego zlotego pierscienia,
   Celownik: zdobionemu zlotemu pierscieniowi,
    Biernik: zdobiony zloty pierscien,
  Narzednik: zdobionym zlotym pierscieniem,
Miejscownik: zdobionym zlotym pierscieniu.

Rozpoznawane nazwy: pierscien i bizuteria.

**Comment by tjurczyk** [comment]
Dodane w 3.15.
