### ISSUE TITLE
kalkulacja odległości w pewnych przypadkach jest "kierunkowa"

### ISSUE THREAD

**Issue by Delwing** [tjurczyk/arkadia-skrypty#450]
Nie wiem z czego to wynika, ale np. weźmy sobie dwie lokacje z mapy:

display(getPath(4878,11812))
display(getPath(11812,4878))

W jednym przypadku jest true, w drugim false.
Obydwie lokalizacje mają siebie nawzajem w wyjściach...

Jako, że kalkulacja bazuje m.in. na wyniku getPath to w jedną strone nie jest w stanie znaleźć ścieżki i podać odległości.

**Comment by tjurczyk** [comment]
Dzieje sie tak dlatego, gdyz lokacja 4878 ma zablokowane przejscie na `sw`. Oznacza to, ze nie bedzie tamtedy robiona sciezka. Powinno to byc dodane w miejscach, w ktorych sciezka prowadzi przez tereny, na ktorych mozna sie gubic, itp.
Odblokuj sobie (tj. odznacz przejscie `sw`) i powinno dzialac.

<img width="932" alt="image" src="https://user-images.githubusercontent.com/1749428/73614417-afda4000-45b3-11ea-8148-65e2a3035f5a.png">
