### ISSUE TITLE
Klucz do podswietlenia na zielono - wielki kamienny klucz

### ISSUE THREAD

**Issue by Monolith18** [tjurczyk/arkadia-skrypty#451]
Nie podswietla klucza na zielono:

Wielki kamienny klucz odmienia sie nastepujaco:

  Mianownik: wielki kamienny klucz,
 Dopelniacz: wielkiego kamiennego klucza,
   Celownik: wielkiemu kamiennemu kluczowi,
    Biernik: wielki kamienny klucz,
  Narzednik: wielkim kamiennym kluczem,
Miejscownik: wielkim kamiennym kluczu.

Rozpoznawane nazwy: klucz.

**Comment by tjurczyk** [comment]
Dodane w 3.16.
