### ISSUE TITLE
pomysl - zewnetrzny plik z magikami/kluczami

### ISSUE THREAD

**Issue by Monolith18** [tjurczyk/arkadia-skrypty#453]
Moze zamiast klucze i magiki jak teraz sa zakodowane na sztywno w skryptach, zrobic dwa zewnetrzne pliki tekstowe lub jeden polaczony, w ktorym kazdy moglby dopisywac kolejne artefakty.
Bedzie wieksza elastycznosc i latwosc dodawnia/edycji w stosunku do stanu obecnego.

**Comment by tjurczyk** [comment]
Tak, to dobry pomysl, dodane bedzie w 3.16
