### ISSUE TITLE
Bind na następny kierunek na trakcie

### ISSUE THREAD

**Issue by Tontol** [tjurczyk/arkadia-skrypty#459]
Marzy mi się możliwość podbindowawania następnego kierunku na trakcie w przypadku tylko dwóch wyjść.

**Comment by tjurczyk** [comment]
W 3.16 dodane jest `/nastepny_kierunek`, ktory mozesz sobie wbic pod jakis bind i wykonywac go z `expandAlias("/nastepny_kierunek")`.
