### ISSUE TITLE
bledne zliczanie czasu w /postepy

### ISSUE THREAD

**Issue by apolios** [tjurczyk/arkadia-skrypty#460]
Po wbiciu pierwszego nieznaka i wklepaniu komendy `/expstart` przy trzecim i kolejnych nieznakach czas liczony jest jako roznica obecnego i czasu wklepania `/expstart` a nie poprzedniego nieznaka.
| nieznaczne      : 26/03 10:48:50    : czas 45:38    :  zabici 11/26    |
| bardzo male     : 26/03 11:16:01    : czas 17:44    :  zabici 15/26    |
| male            : 26/03 12:00:58    : czas 62:40    :  zabici 13/31    |

**Comment by tjurczyk** [comment]
Przepisalem generalnie czesc odpowiedzialna za timestamp w liczniku.
Korzysta teraz z systemowego `getEpoch()` zamiast licznika mudletowego, ktory skrypty musialy stopowac, startowac i restartowac, co jak widac nie dzialalo zbyt poprawnie.

Daj znac jesli w 3.16 znalazlbys jakies niescislosci. Przetestowalem to w roznych scenariuszach i wydaje sie dzialac.
