### ISSUE TITLE
przemknij nw;n;ne;w;e;sw;s;se;d;u nie przemieszcza kropki na mapie

### ISSUE THREAD

**Issue by ssnakey** [tjurczyk/arkadia-skrypty#47]
1. przemknij nw;n;ne;w;e;sw;s;se;d;u nie przemieszcza kropki na mapie
2. przemknij z druzyna nw;n;ne;w;e;sw;s;se;d;u (w momencie gdy nie jestem w druzynie) przemieszcza kropke w losowych kierunkach

**Comment by tjurczyk** [comment]
1. Tekst `Nie jestes w stanie wymknac sie stad niezauwazenie.` jest blokerem, wiec radze nie uzywac tego w takim pakiecie. Raczej nie bede obslugiwal tak specjalnych przypadkow.

2. Skoro nie jesteś w druzynie to po co uzywasz przemykania w druzynie? Tekst `Nie jestes dowodca zadnej druzyny.` jest blokerem, wiec mapper cie cofnie, zatem nastepne kierunki beda wykonane z błędnej lokacji. Nic dziwnego, ze przemiesci w blednych kierunkach.

**Comment by ssnakey** [comment]
AD1
hym ja pisze ze podczas poprawnego przemykania nie przemieszcza kropy a ty o blokerach nawijasz :)
jedno z drugim nie ma nic wspolnego.

**Comment by tjurczyk** [comment]
`przemknij s;s;s;s;sw`

U mnie to działa w przypadku poprawnego przemknięcia, mapper się przemieścił. Daj loga albo powiedz jak zreprodukować.

**Comment by ssnakey** [comment]
> przemknij e
Skradajac sie powoli ruszasz na wschod.
Trakt nad jeziorkiem.
-----: SE NE W
> przemknij w
Skradajac sie pospiesznie ruszasz na zachod.
Droga.
-----: E NW
> przemknij e
Skradajac sie najszybciej jak umiesz ruszasz na wschod.
Trakt nad jeziorkiem.
-----: SE NE W
> przemknij w
Skradajac sie najszybciej jak umiesz ruszasz na zachod.
Droga.
-----: E NW
>

**Comment by ssnakey** [comment]
kropa stoi  :/

**Comment by tjurczyk** [comment]
Mapper w trybie `follow`? Nie masz jakiegoś swojego aliasa z przemykaniem? 

Otwórz debug i zrób "przemknij <kierunek>" i sprawdź czy uruchamiany jest alias odpowiadający za przemykanie: https://i.imgur.com/FscTWmJ.png

**Comment by ssnakey** [comment]
tu bedziemy gadac?
