### ISSUE TITLE
ataki nożownika z pierwszej osoby

### ISSUE THREAD

**Issue by pprraavv** [tjurczyk/arkadia-skrypty#54]
Można prosić o dodanie gagów do ataków nożownika widzianych z pierwszej osoby?
Opierając się na paczce color_innych_spece NOZ powyciągałem z logów pasujące przykłady opisów:
- 0 Sprezasz sie do skoku probujac ugodzic zwinna ladna sarne swym koscianym mlecznobialym sztyletem, lecz tracisz koncentracje i twoj niecelny cios mija cel o wlos.
- 1 Wykorzystujac dogodna sytuacje rzucasz sie na zwinna ladna sarne, pragnac pchnac go stalowym waskim sztyletem, jednak twoj nieskoordynowany ruch nie jest w stanie nikogo zaskoczyc.
- 2 Zamierzasz sie na burego duzego wilka swym koscianym mlecznobialym sztyletem, jednak on z latwoscia unika twojego ciosu.
- 3 Wykonujesz szybki wypad by trafic burego duzego wilka swym stalowym waskim sztyletem pozostawiajac na jego ciele nieznaczne drasniecie.
- 4 Odskakujesz do tylu, a kosciany mlecznobialy sztylet, ktory trzymasz w rece, zatacza szeroki luk by ostatecznie trafic krepego dziecinnego snotlinga, zadajac jednak tylko nieznaczne obrazenia.
- 5 Obracajac w reku swym koscianym mlecznobialym sztyletem wykonujesz nagly zwod i trafiasz krepego glupkowatego snotlinga pozostawiajac tylko nieznaczne obrazenia.
- 6 Wykorzystujac chwilowa dekoncentracje krepego glupkowatego snotlinga, wbijasz swoj kosciany mlecznobialy sztylet w jego cialo pozostawiajac lekkie drasniecie.
- 7 Wykorzystujac dogodna chwile doskakujesz do krepego glupkowatego snotlinga, a twoj kosciany mlecznobialy sztylet zostawia po sobie tylko lekkie drasniecie.
- 8 Korzystajac z nieuwagi krepego glupkowatego snotlinga klujesz jego cialo koscianym mlecznobialym sztyletem zostawiajac tylko lekkie drasniecie.
- 9 Wykonujesz pare oszczednych unikow starajac sie zmeczyc malego siakajacego snotlinga i gdy ten przystaje na chwile by zlapac oddech, wbijasz swoj kosciany mlecznobialy sztylet.
- 10 Poziomym cieciem swojego koscianego mlecznobialego sztyletu godzisz w chudego glupkowatego snotlinga, trafiajac w korpus i wywolujac bolesny grymas na jego twarzy.
- 11 Uwaznie sledzisz ruchy chudego glupkowatego snotlinga i trafiajac go w korpus swym  koscianym mlecznobialym sztyletem zostawiasz bolesna rane.
- 12 Wypatrujac luke w obronie burego duzego wilka blyskawicznie skracasz dystans i trafiasz go w leb, a twoj stalowy waski sztylet zostawia po sobie krwawa bruzde.
- 13 Blyskawicznie wyrzucasz przed siebie reke dzierzaca kosciany mlecznobialy sztylet, trafiajac niskiego siakajacego snotlinga w nogi. Ofiara krzywi sie z bolu, a ty wyszarpujesz szybko swa bron, pozostawiajac krwawiaca rane.
- 14 Zaciskasz mocniej palce na koscianym mlecznobialym sztylecie i paskudnie ranisz dlugonosego usmiechnietego snotlinga, trafiajac go w korpus.
- 15 BRAK PRZYKŁADU
- 16 BRAK PRZYKŁADU
- 17 Celujac w korpus niskiego siakajacego snotlinga zaglebiasz kosciany mlecznobialy sztylet az po rekojesc, a gdy wyciagasz go z rany zauwazasz, ze cala jest czerwona od krwi.
- 18 BRAK PRZYKŁADU
- 19 Zwinnym, kocim ruchem przypadasz do ziemi, by nagle doskoczyc do dlugonosego usmiechnietego snotlinga i wyrzucajac blyskawicznie swa dlon dzierzaca kosciany mlecznobialy sztylet wbic go w korpus przeciwnika. Nim zdazy sie on otrzasnac z szoku, doprawiasz dziela silnym kopniakiem, odrzucajac go i wyciagajac swa bron z jego ciala. Ofiara z trudem podnosi sie na nogi, a z potwornej rany natychmiast zaczyna plynac krew.
- 20 BRAK PRZYKŁADU
- 21 Zrecznym ruchem parujesz cios pogryzionego duzego wilka, rownoczesnie zachodzac go od tylu. Starannie wymierzonym pchnieciem wbijasz motylkowy nilfgaardzki sztylet w jego plecy, tuz miedzy lopatkami. Oczy pogryzionego duzego wilka rozszerzaja sie z bolu, gdy osuwa sie on z cichym jekiem na ziemie. Dla niego to juz koniec walki.
- 22 Unikajac uderzenia krepego dziecinnego snotlinga blyskawicznie doskakujesz do niego i wbijasz az po rekojesc swoj kosciany mlecznobialy sztylet w jego cialo. Na chwile zamierasz w bezruchu, z satysfakcja czujac, jak z twej ofiary uchodzi zycie. krepy dziecinny snotling z cichym jekiem osuwa sie na ziemie, a ty wyszarpujesz swa bron z ciala i noga odsuwasz zwloki na bok, rozgladajac sie za kolejnymi przeciwnikami.
- 23 Wykorzystujac dekoncentracje i oslabienie niskiego siakajacego snotlinga, silnym kopnieciem podcinasz go, rownoczesnie wyrzucajac do przodu swa reke z koscianym mlecznobialym sztyletem. Przeciwnik traci rownowage i osuwa sie na twa bron, ta zas zaglebia sie w jego cialo, odbierajac mu ostatnie sily. Z zimnym usmiechem wyciagasz zakrwawiony kosciany mlecznobialy sztylet z osuwajacego sie na ziemie ciala.
- 24 BRAK PRZYKŁADU (chyba z pierwszej osoby identyczne z 22)

Nie wiem czy gagowane są ataki z zaskoczenia, mam trzy przykłady:

- Pewnym, lekkim krokiem ruszasz w kierunku bialej zwinnej norki. Zaciskasz mocniej palce na rekojesci stalowego waskiego sztyletu gotow do zadania morderczego pchniecia. Jestes juz tuz, tuz przy ofierze gdy nagle jeden niewlasciwy krok przesadza o wszystkim! Zahaczasz o cos stopa i przy wtorze zdradzajacego twa obecnosc loskotu z trudem lapiesz rownowage!
- Bezszelestnie skracasz dystans dzielacy cie od czarnej malej kozy i zdecydowanym pchnieciem wbijasz stalowy waski sztylet w jej jedna z nog! Cialem przeciwniczki wstrzasa ledwie zauwazalny spazm bolu.
- Bezszelestnie niczym cien odrywasz sie od otoczenia i pozornie beztroskim krokiem zblizasz sie do burego ospalego krolika. Pelnym wyrachowania oraz chlodnej precyzji ciosem tniesz stalowym waskim sztyletem po gardle swego przeciwnika, a on ledwo trzymajac sie na nogach odwraca sie nienaturalnie powoli w twoja strone, by z zasnutymi mgla oczami pasc martwy u twych stop.

Chyba jako unik powinien się gagować taki ruch:

- Ustawiasz sie bokiem wobec kedzierzawego usmiechnietego snotlinga i gdy ten odbija sie od ziemi zamaszystym uderzeniem koscianego mlecznobialego sztyletu odrzucasz go dobre kilka stop na bok.

**Comment by tjurczyk** [comment]
Spece i unik dodane, z ukrycia chyba nie ma jeszcze z 3 osoby, więc trzeba najpierw tamte zebrać.
