### ISSUE TITLE
Bagna kolo witten 

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#58]
Nie wiem dlaczego ale za kazdym razem po przejsciu pulapek na bagnach do ozywka mapper przestaje dzialac i sledzic.
uzywam sciezek do przechodzenia pod golema.

Kropa zatrzymuje sie na lokacji z golemem i juz nie rusza sie.

Ustawianie recznie swojej lokalizacji przestawia mi kropke ale ona dalej nie podaza dalej... wyjde z kurhanu i dalej jest to samo ustawianie nic nie daje. Musze wyjsc na trakt/ do wioski wklepac /zlok i dopiero mapper sie odmula i dziala dalej normalnie.

Sprawa jest notoryczna.

**Comment by tjurczyk** [comment]
@animal793 

Prawdopodobnie jest tam jakiś pauser, który wyłącza mapper chwilowo (to samo co działa w trakcie szukania/czytania itp), ale brakuje mi tekstu na wyłączanie pausera. Prześlij mi loga na forum albo gdziekolwiek, żebym mógł wyłapać.
