### ISSUE TITLE
mala poprawka w /sprzet

### ISSUE THREAD

**Issue by pprraavv** [tjurczyk/arkadia-skrypty#62]
Nosząc dwie bronie skrypt `/sprzet` pomija drugą broń.

**Comment by ftpd** [comment]
Mi nic nie pomija:

 srebrzysty wezowaty nadziak ........ -- [6/7] w dobrym stanie.
 srebrzysty wezowaty nadziak ........ -- [5/7] liczne walki wyryly na nim swoje pietno.
 folgowa misterna para naudziakow ... -- [max] w znakomitym stanie.
 turniejowa kunsztowna zbroja plytowa -- [max] w znakomitym stanie.

**Comment by pprraavv** [comment]
Hmm, przetestowałem i jest dziwnie.  Skrypt pomija w podsumowaniu `Dlugi waski sztylet` (wyrób kowala pod Mariborem). Poniżej zrzut z opisu. Podejrzewam, że przeszkadza niestandardowy tekst (pogrubiony)

======= Oceniasz starannie dlugi waski sztylet. ========

Jest to obustronnie ostrzony sztylet o dlugiej, waskiej klindze, z niewielkim zbroczem po srodku. 
Oblozona skora rekojesc zakonczona jest nieznacznym, wykonanym z tego samego co ostrze metalu, 
jelcem.
Wyglada na to, ze jest w znakomitym stanie. [max]
**Na ostrzu tej broni wyryto trzy litery - duze 'BK' oraz umieszczone tuz obok nich, malutkie J.**

Oceniasz, ze dlugi waski sztylet wazy 760 gramow, zas jego objetosc wynosi 230 mililitrow.
Wydaje ci sie, ze jest wart okolo 830 miedziakow, czyli 3 zl, 9 sr, 2 mdz.

 Typ broni: sztylet                Chwyt: w dowolnej rece            
 Obrazenia: klute i ciete                    
 Wywazenie: doskonale [12/14]      Skutecznosc: niezwykle skuteczne [11/14]

**Comment by tjurczyk** [comment]
Poprawione od następnej wersji.
