### ISSUE TITLE
Wyroznienie tekstu o przygotowaniu do ataku z zaskoczenia.

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#67]
Jakby mozna bylo wyroznic to info

[Rafgart] przygotowuje sie do ataku na ciebie!

Plus... ewentualnie

XXX dochodzi do siebie. ( po ogluszeniu)
XXX wychodzi z ukrycia.
Nad twoja glowa zbiera sie duza chmura gestego purpurowego pylu.

**Comment by ssnakey** [comment]
czlowieku... wez sobie sam to pokoloruj a nie truj dupy o rzeczy ktore kazdy i tak ustawi sobie po swojemu pokolorowanie linijki to chyba nie jest zbyt wielki problem? Ja naprzyklad lubie miec ta informacje na szaro.

**Comment by animal793** [comment]
w dupie mam twoje zale.

Ten post jest nie do ciebie, wiec sie nie wpierdalaj.

Wiem co mam zglaszac i komu i nie z toba ustalam co jak kiedy i dlaczego.

**Comment by ftpd** [comment]
Ale to nie są skrypty 'tylko dla animalacyferki, co nie umie ticketa nawet zatytułować jak człowiek'. Nie są dla Ciebie i pod Ciebie. To ma być silnik, a pierdolenie typu 'kolorek na dwa słowa' każdy robi sam zgodnie z tym, jak lubi.
No chyba, że jesteś aż takim zjebem, że nie potrafisz prostego pokolorowania - ale to wtedy może do przedszkola wróć, a nie w gry dla dorosłych graj.

**Comment by animal793** [comment]
jak juz mowilem nie jestescie zadnym komitetem zatwierdzajacym zmiany.

Jak ktos bedzie decydowac co bedzie dodane a co nie to Dzordzyk a nie wy maloty.

**Comment by tjurczyk** [comment]
To trzeba pozbierać wszystkie opisy zaskoków - dla GP, partka, i noża i ewentualnie zrobić ticketa.
