### ISSUE TITLE
Errory -

### ISSUE THREAD

**Issue by baranno** [tjurczyk/arkadia-skrypty#68]
[ERROR:] object:<event handler function> function:<gmcp_handler_other>
         <[string "function ateam:start_ateam()..."]:171: attempt to index field '?' (a nil value)>

         <[string "function scripts.utils.bind_functional(comm..."]:28: bad argument #2 to 'find' 
(string expected, got nil)>

Pozbylem sie tego lokalnie, ale zglaszam... sypanie tych errorow powoduje u mnie dziwne zachowania m.in z timerami.

**Comment by tjurczyk** [comment]
Ale kiedy to występuje?

**Comment by baranno** [comment]
Zazwyczaj jak chodzik z predkoscia 0 leci...

**Comment by tjurczyk** [comment]
Ok, dzięki, poprawione.
