### ISSUE TITLE
Pasek Alert / Zabici/ odmiana

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#69]
Alert : DOBADZ

Po dobyciu zwiesil sie i nie znika

Zabici 32/16 wyswietla zamiast 32/160 nie miesci sie trzecia cyfra mozna by troszke odsunac bo miejsce jest.

======

Schodzac z barki w Queen zle nas gps lokalizuje bo wysadza nas w miejscu oczekiwania na sattek do bodrog 

NULN;
Podjezdzajacy dylizans w nuln stojac na lokacji z fontanna odpala nam gps i lokalizuje nas jakbysmy stali na polnoc od oxenfurtu.
Trzeba uzywac /zlok by sie ustawic ponownie w nuln tam gdzie jestesmy.

=============
odmiana pojedyncza do dodania:
"blekitno-srebrna herbowa tarcze"
"niepozorny barwny pierscien"
"zdobiony dlugi lewak"
Cala odmiana do dodania:
"starozytna runiczna zbroje plytowa"

**Comment by tjurczyk** [comment]
Co do belki, w configu zwiększ sobie to:

`scripts.ui.footer_info_width_p = 46`

Np do 48 lub 50.
