### ISSUE TITLE
Suby do oceny ubrań.

### ISSUE THREAD

**Issue by ftpd** [tjurczyk/arkadia-skrypty#7]
Zgodnie z 'poziomy znoszenia ubran':
   calkiem nowe, w miare nowe, troche znoszone, prawie calkiem
   znoszone i gotowe rozpasc sie w kazdej chwili.

**Comment by ftpd** [comment]
; zużycie
/def -mregexp -Fp2 -t'(calkiem now.).'           _stan_ekwipunku5 = /_sub 5/5
/def -mregexp -Fp2 -t'(w miare now.).'           _stan_ekwipunku4 = /_sub 4/5

; ekwipunek
/def -mregexp -Fp2 -t'(troche zuzyty).'          _stan_ekwipunku3 = /_sub 3/5
/def -mregexp -Fp2 -t'(w duzym stopniu zuzyty).' _stan_ekwipunku2 = /_sub 2/5
/def -mregexp -Fp2 -t'(kompletnie zuzyty).'      _stan_ekwipunku1 = /_sub 1/5

; ubrania
/def -mregexp -Fp2 -t'troche znoszone'                    _stan_ekwipunku_ubranie_3 = /_sub 3/5
/def -mregexp -Fp2 -t'prawie calkiem znoszone'            _stan_ekwipunku_ubranie_2 = /_sub 2/5
/def -mregexp -Fp2 -t'gotowe rozpasc sie w kazdej chwili' _stan_ekwipunku_ubranie_1 = /_sub 1/5

**Comment by tjurczyk** [comment]
Dodane od 2.14c.
