### ISSUE TITLE
gps

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#76]
Brak Gpsu

wsiadamy w bodrog wysiadamy w quenn --- wysiadajac z barki w quenn zle lokalizuje nas w queen.

**Comment by tjurczyk** [comment]
Takie zgłoszenia nic nie mówią. Trzeba dawać logi, detale.

**Comment by ftpd** [comment]
Tutaj: https://github.com/tjurczyk/arkadia-skrypty/issues/85 masz numery lokacji. Statek z Bodrog zatrzymuje się w 4651.
