### ISSUE TITLE
Spece barba dublowane.

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#79]
=================================================
Zamieszczam bo wersja nowa a ten bug nie rozwiazany to niech bedzie tu co by nie zapomniec.

[BAR OGL] [BAR 2/6] [JA OGL] [JA 2/6] Nie przebierajac w srodkach xxx z calej sily wali siwego 
kamiennego trolla na odlew gigantycznym granitowym mlotem, tlukac mu przy tym tulow. Nieprzyjemne 
chrzakniecie i metny wzrok przeciwnika swiadcza, ze dobrze wymierzony cios musial trafic w jakies 
wrazliwe miejsce.
[BAR 4/6] [JA 4/6] Nie tracac czasu na zbedne manewry xxxx z calej sily wali jaskiniowego 
kamiennego trolla na odlew gigantycznym granitowym mlotem, gruchoczac mu przy tym tulow.
Jaskiniowy kamienny troll powoli dochodzi do siebie.

**Comment by tjurczyk** [comment]
Te są poprawione, gdyby jeszcze jakies sie dublowaly nowy ticket.
