### ISSUE TITLE
Brakujące blokery.

### ISSUE THREAD

**Issue by ftpd** [tjurczyk/arkadia-skrypty#8]
Mapa nie powinna się poruszać przy:

Trwa ladowanie danych postaci
Nie ma takiej komendy. Wpisz "?", zeby uzyskac pomoc, albo "q", zeby wyjsc

**Comment by tjurczyk** [comment]
Dodane od 2.14c.

**Comment by ftpd** [comment]
Przy drugim naciśnięciu 'n' podczas 'Trwa ladowanie danych postaci' kropka się jednak porusza.

**Comment by tjurczyk** [comment]
Jednak naprawione przy dostosowywaniu API pod pausery.
