### ISSUE TITLE
Ilosc ludzikow w teamie

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#84]
Fajnie jakby dodac ze nie tylko przy zmianie lokacji wyswietla nam sie

[2] A i B przybywaja za toba z zachodu.

ale jak stoimy na lokacji i chcemy sprawdzic stan druzyny uzywajac "zerknij"

to tez wyswietli na ten czas tego nie robi

 zerknij
Przy wielkim debie.
Sa tutaj dwa widoczne wyjscia: wschod i zachod.
A i B.

**Comment by tjurczyk** [comment]
To jest raczej niemożliwe do zrobienia, bo nie ma tego jak łapać.
