### ISSUE TITLE
Brak Blokera vol 2

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#87]
By plynac musisz miec wolne rece.

**Comment by tjurczyk** [comment]
Załóżmy, że jesteś na lokacji z wyjściami na zachód i wschód. Co się stanie, jeśli spróbujesz pójść na północ (lub jakikolwiek nieistniejący kierunek)? `Nie widzisz wyjscia...` czy ten sam tekst?

**Comment by animal793** [comment]
sprawdze i odpisze.

**Comment by animal793** [comment]
.> w
By plynac musisz miec wolne rece.
.> nw
Nie widzisz zadnego wyjscia prowadzacego na polnocny-zachod.

**Comment by tjurczyk** [comment]
@animal793 Dzięki, dodane.
