### ISSUE TITLE
Bind na Mosiezna lampa z uchwytem 

### ISSUE THREAD

**Issue by edrim** [tjurczyk/arkadia-skrypty#88]
"Mosiezna lampa z uchwytem" nie reaguje na zgaszenie, tzn gasi ale bind ctrl+4 napelnij lampe ciagle sie pojawia do konca sesji.

**Comment by animal793** [comment]
Jak tak sie robi wystarczy zapalic jeszcze raz /zap /zg i powinno zejsc.

Nie zawsze zalapuje.

**Comment by edrim** [comment]
W zasadzie to juz sie nie zacina.
Sprawdze najwyzej otworze nowy case.
