### ISSUE TITLE
Brak Blokera vol 3

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#89]
Brak kolejnego blokera:

Nie mozesz tak po prostu wymknac sie z walki.

**Comment by tjurczyk** [comment]
To nie jest blokerem, bo to samo Ci zwróci Arkadia, gdy będziesz próbował się przemknąć w nieistniejącym kierunku, więc zacznie Ci wracać niepotrzebnie. 
Zostanie dodane, aby rozpoczęta walka/walka po prostu wyłączała tryby skradania.
