### ISSUE TITLE
Gps

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#90]
brak Gpsa  na Ringhornie kursujacym miedzy wstega a blakiven od obu stron

**Comment by ctarx** [comment]
Jaką masz wersję skryptów, bo u mnie działa?

**Comment by animal793** [comment]
2.20c

**Comment by tjurczyk** [comment]
Potrzebne jest więcej informacji:
co krzyczy kapitan, jakie nazwy lokacji z wyjściami (po `zerknij`) po wyjściu ze statku itp.

**Comment by jorhni** [comment]
Drakkar przybija do brzegu.
Sniady spokojny mezczyzna (Jacob, NPC) krzyczy: Doplynelismy do portu Blaviken w krolestwie Redanii! 
Mozna wysiadac!

bind [: zejdz ze statku

Sniady spokojny mezczyzna (Jacob, NPC) schodzi z drakkara na brzeg.
zejdz ze statku
Schodzisz z drakkara.
W niewielkim porcie.
Sa tutaj dwa widoczne wyjscia: polnocny-zachod i poludnie.
Smukly drakkar.
Sniady spokojny mezczyzna (Jacob, NPC).
-- 
Drakkar przybija do brzegu.
Sniady spokojny mezczyzna (Jacob, NPC) krzyczy: Doplynelismy do pomostu na Blekitnej Wstedze! Mozna 
wysiadac!

bind [: zejdz ze statku

Sniady spokojny mezczyzna (Jacob, NPC) schodzi z drakkara na brzeg.
zejdz ze statku
Schodzisz z drakkara.
Pomost u brzegu Blekitnej Wstegi.
Sa tutaj dwa widoczne wyjscia: zachod i wschod.
Smukly drakkar.
Sniady spokojny mezczyzna (Jacob, NPC).

**Comment by tjurczyk** [comment]
@jorhni Dzięki, dodane.
