### ISSUE TITLE
Mapa/bloker

### ISSUE THREAD

**Issue by jorhni** [tjurczyk/arkadia-skrypty#91]
Witam, ja tu po raz pierwszy
Kanały pod Nuln:
jest "połączenie" miedzy 16210 a 16211
powinno być między 7226 a 16211
Poza tym przejście z 16211 do 7226 (w celu prawidłowego prowadzenia drużyny) nie powinno być:
"wejdz we wschodnia sciane" - tylko normalnie na "e"

Kanały pod Nuln
Lokacja 16229 - polecenie "przeszukaj lozko" nie zdejmuje "blokady" z róży po zakończeniu przeszukiwania

**Comment by tjurczyk** [comment]
Co do tego: Lokacja 16229 - polecenie "przeszukaj lozko" nie zdejmuje "blokady" z róży po zakończeniu przeszukiwania

potrzebuje jaki tekst jest zwracany z Arkadii po przeszukaniu.

**Comment by jorhni** [comment]
Udane przeszukiwanie:
> Przeszukujac lozko i lezace na nim ubrania znajdujesz dosc duzy, stalowy klucz.

Nieudane przeszukiwanie:
> Pracowicie przeszukujesz lozko i lezace na nim ubrania, jednak nie znajdujesz niczego interesujacego.

**Comment by tjurczyk** [comment]
@jorhni Dzięki, dodane.
