### ISSUE TITLE
/postepy

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia-skrypty#92]
Dzis mi wywalilo blad mudleta i musialem go odpalic na nowo.

Wyswietlilo sie okienko ze przestal dzialac. I musialem zrobic restart

Jesli da sie jakos zabezpieczyc /postepy i zabitych biezacych przed tym w jakis sposob.

Chociaz ciezko, bo to zwykly crash.

No ale wrzucam jakby co:).

**Comment by tjurczyk** [comment]
`/postepy`, `/zabici` itp. zostaną załadowane poprawnie jeśli:

- wyłączysz mudleta normalnie
- przelogujesz linka

zakończenie (`zakoncz`) spowoduje, ze wszystko się zresetuje.
