### ISSUE TITLE
GPS

### ISSUE THREAD

**Issue by jorhni** [tjurczyk/arkadia-skrypty#93]
Jadąc z Quenelles dyliżansem będąc w Montlac mam coś takiego:

> " Powoli pojazd zaczyna tracic predkosc, by po chwili zatrzymac sie.
bind [: wyjscie
Z zewnatrz dochodzi stlumiony glos woznicy: Postoj, centrum wioski Montlac.
(mapper): GPS: Montlac
(mapper): GPS: Anchor
Dylizans mocno zaskrzypial.
Woznica wola: Nastepny postoj - Merceaux-Descloux!"

Mapper niestety wariuje w chwili, kiedy wysiądziemy.

**Comment by tjurczyk** [comment]
Poprawione od `2.21`.
