### ISSUE TITLE
GPS Temeria - Piana

### ISSUE THREAD

**Issue by jorhni** [tjurczyk/arkadia-skrypty#97]
Brak GPS na tratwie z Temerii pod Piane (w obie strony) - lokacje 3442 - 2624

**Comment by tjurczyk** [comment]
Potrzebne logi: kto i co krzyczy.

**Comment by jorhni** [comment]
Niestety gostek nie raczy zejść z tratwy a gadać zaczyna dopiero, kiedy na tratwę wsiądziemy:

> lokacja  3442
> Droga za poludniowym mostem.
> Jest tutaj jedno widoczne wyjscie: poludniowy-zachod.
> Szeroki drewniany prom przybija do brzegu.
> Szeroki drewniany prom odbija od brzegu.

> Lokacja 2624
> Przystan promowa.
> Jest tutaj jedno widoczne wyjscie: polnocny-wschod.
> Szeroki drewniany prom przybija do brzegu.
> Szeroki drewniany prom odbija od brzegu.

**Comment by tjurczyk** [comment]
@jorhni Te lokacje z wyjściami są dość dwuznaczne. Mamy pewność, że nie ma drugich takich z takimi nazwami i dokładnie takimi wyjściami? Jeśli nie to ok.

**Comment by jorhni** [comment]
@tjurczyk 
Masz rację, ale ja bym tu zrobił jednak tak, że te GPS`y bym ustawił i zobaczył, czy coś "wyjdzie w praniu". Jeśli tak, to wracamy do problemu lecz już wiemy, gdzie szukać, jeśli nie, to sprawa załatwiona. Może to niezbyt profesjonalne, ale ... tak bym zrobił.
