### ISSUE TITLE
Dublowanie opisu gracza z bazy

### ISSUE THREAD

**Issue by jorhni** [tjurczyk/arkadia-skrypty#98]
Tylko na jednej postaci na razie zauwazylem:
Jest to niebieskooki ciemnowlosy mezczyzna (Arrander KS) (Arrander KS) (Arrander KS).
W bazie figuruje tylko raz.

**Comment by tjurczyk** [comment]
To raczej błąd w Twojej bazie. Używasz bazy startowej? Modyfikowałeś ją?

https://i.imgur.com/qp1DnuP.png

**Comment by jorhni** [comment]
Modyfikacje polegają tylko na dodaj/usuń, ręcznych nie było, ale nic, tak myślałem, że coś się właśnie u mnie posypało, albo jakiś "lewy" trigger mi się zrobił, ale to już jutro sprawdzę.

**Comment by jorhni** [comment]
Tak, jak myślałem - wynik wyszukiwania w mudlecie "Arrander" zwraca coś takiego:
[http://imgur.com/GenSvvI](url)
Za pierona nie wiem, jak się tego pozbyć, ale ogólnie temat do zamknięcia.

**Comment by tjurczyk** [comment]
Ale ten trigger powinien być. Skopiuj sobie bazę, którą zmodyfikowałeś w bezpieczne miejsce, zrob `/pobierz_baze`, zrestartuj Mudleta i wtedy zrób takie echo, jakie ja zrobiłem i pokaż wynik. Wtedy będziemy wiedzieli, czy to problem z jakimś wpisem w bazie.

**Comment by jorhni** [comment]
No dobra. Problem jest, ale nie w bazie i polega na tym, że w bazie jest trzech niebieskookich ciemnowlosych mezczyzn - Arrander KS, Agis GL, Matrax GL. 

I teraz, akuratnie tak się złożyło, że zarówno KS jak i GL mam w pliku konfiguracyjnym wpisane jako gildie, które chcę, aby były odpowiednio kolorowane. Przy tej konfiguracji otrzymujemy:
`Jest to niebieskooki ciemnowlosy mezczyzna (Arrander KS) (Arrander KS) (Arrander KS).`

Natomiast w chwili, kiedy te gildie usunę z scripts.people.colored_guilds w pliku konfiguracyjnym wynik wygląda tak:
`Jest to niebieskooki ciemnowlosy mezczyzna (Arrander KS, Agis GL, Matrax GL).`

**Comment by tjurczyk** [comment]
Poprawione. Będzie do kolorowania wzięty tylko pierwszy napotkany wpis z danym shortem.
